services:
  redis:
    image: redis:8-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - classification_service_network

  database:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - classification_service_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - classification_service_network
    env_file:
      - compose.env
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:${SERVER_PORT}/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
volumes:
  pg_data:
    name: classificationservice_pg_data
  redis_data:
    name: classificationservice_redis_data

networks:
  classification_service_network:
    driver: bridge