// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analysis.sql

package kalibr

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAnalyses = `-- name: CountAnalyses :one
SELECT COUNT(*)::bigint AS total_count
FROM analysis_new
WHERE user_id = $1
  AND ($2::TEXT IS NULL OR $2 = '' OR product = $2)
  AND ($3::uuid IS NULL OR id = $3)
  AND ($4::TEXT IS NULL OR $4 = '' OR CAST(id AS TEXT) LIKE $4 || '%')
`

type CountAnalysesParams struct {
	UserID   int64
	Product  string
	IDExact  pgtype.UUID
	IDPrefix string
}

func (q *Queries) CountAnalyses(ctx context.Context, arg CountAnalysesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalyses,
		arg.UserID,
		arg.Product,
		arg.IDExact,
		arg.IDPrefix,
	)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const countAnalysesByIdUsers = `-- name: CountAnalysesByIdUsers :one
SELECT COUNT(*)::bigint AS total_count
FROM analysis_new
WHERE user_id = ANY($1::bigint[])
  AND ($2::TEXT IS NULL OR $2 = '' OR product = $2)
  AND ($3::uuid IS NULL OR id = $3)
  AND ($4::TEXT IS NULL OR $4 = '' OR CAST(id AS TEXT) LIKE $4 || '%')
`

type CountAnalysesByIdUsersParams struct {
	UserIds  []int64
	Product  string
	IDExact  pgtype.UUID
	IDPrefix string
}

func (q *Queries) CountAnalysesByIdUsers(ctx context.Context, arg CountAnalysesByIdUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalysesByIdUsers,
		arg.UserIds,
		arg.Product,
		arg.IDExact,
		arg.IDPrefix,
	)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const getAnalysesList = `-- name: GetAnalysesList :many
SELECT
    id, user_id, source, product, bot_message, files_source, files_output, date_time, scale_mm_pixel
FROM analysis_new
WHERE user_id = $1
  AND ($2::TEXT IS NULL OR $2 = '' OR product = $2)
  AND ($3::uuid IS NULL OR id = $3)
  AND ($4::TEXT IS NULL OR $4 = '' OR CAST(id AS TEXT) LIKE $4 || '%')
ORDER BY
    CASE WHEN $5 = 'date_time' AND $6 = 'asc' THEN date_time END ASC,
    CASE WHEN $5 = 'date_time' AND $6 = 'desc' THEN date_time END DESC,
    CASE WHEN $5 = 'id' AND $6 = 'asc' THEN id END ASC,
    CASE WHEN $5 = 'id' AND $6 = 'desc' THEN id END DESC,
    CASE WHEN $5 = 'product' AND $6 = 'asc' THEN product END ASC,
    CASE WHEN $5 = 'product' AND $6 = 'desc' THEN product END DESC
LIMIT $8::int
OFFSET $7::int
`

type GetAnalysesListParams struct {
	UserID    int64
	Product   string
	IDExact   pgtype.UUID
	IDPrefix  string
	SortBy    interface{}
	SortOrder interface{}
	Offset    int32
	Limit     int32
}

type GetAnalysesListRow struct {
	ID           uuid.UUID
	UserID       int64
	Source       *string
	Product      *string
	BotMessage   *string
	FilesSource  []string
	FilesOutput  []string
	DateTime     time.Time
	ScaleMmPixel *float64
}

func (q *Queries) GetAnalysesList(ctx context.Context, arg GetAnalysesListParams) ([]GetAnalysesListRow, error) {
	rows, err := q.db.Query(ctx, getAnalysesList,
		arg.UserID,
		arg.Product,
		arg.IDExact,
		arg.IDPrefix,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalysesListRow{}
	for rows.Next() {
		var i GetAnalysesListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.Product,
			&i.BotMessage,
			&i.FilesSource,
			&i.FilesOutput,
			&i.DateTime,
			&i.ScaleMmPixel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalysesListByIdUsers = `-- name: GetAnalysesListByIdUsers :many
SELECT
    id, user_id, source, product, bot_message, files_source, files_output, date_time, scale_mm_pixel
FROM analysis_new
WHERE user_id = ANY($1::bigint[])
  AND ($2::TEXT IS NULL OR $2 = '' OR product = $2)
  AND ($3::uuid IS NULL OR id = $3)
  AND ($4::TEXT IS NULL OR $4 = '' OR CAST(id AS TEXT) LIKE $4 || '%')
ORDER BY
    CASE WHEN $5 = 'date_time' AND $6 = 'asc' THEN date_time END ASC,
    CASE WHEN $5 = 'date_time' AND $6 = 'desc' THEN date_time END DESC,
    CASE WHEN $5 = 'id' AND $6 = 'asc' THEN id END ASC,
    CASE WHEN $5 = 'id' AND $6 = 'desc' THEN id END DESC,
    CASE WHEN $5 = 'product' AND $6 = 'asc' THEN product END ASC,
    CASE WHEN $5 = 'product' AND $6 = 'desc' THEN product END DESC
LIMIT $8::int
OFFSET $7::int
`

type GetAnalysesListByIdUsersParams struct {
	UserIds   []int64
	Product   string
	IDExact   pgtype.UUID
	IDPrefix  string
	SortBy    interface{}
	SortOrder interface{}
	Offset    int32
	Limit     int32
}

type GetAnalysesListByIdUsersRow struct {
	ID           uuid.UUID
	UserID       int64
	Source       *string
	Product      *string
	BotMessage   *string
	FilesSource  []string
	FilesOutput  []string
	DateTime     time.Time
	ScaleMmPixel *float64
}

func (q *Queries) GetAnalysesListByIdUsers(ctx context.Context, arg GetAnalysesListByIdUsersParams) ([]GetAnalysesListByIdUsersRow, error) {
	rows, err := q.db.Query(ctx, getAnalysesListByIdUsers,
		arg.UserIds,
		arg.Product,
		arg.IDExact,
		arg.IDPrefix,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalysesListByIdUsersRow{}
	for rows.Next() {
		var i GetAnalysesListByIdUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.Product,
			&i.BotMessage,
			&i.FilesSource,
			&i.FilesOutput,
			&i.DateTime,
			&i.ScaleMmPixel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalysisByID = `-- name: GetAnalysisByID :one
SELECT id, user_id, source, product, bot_message, files_source, files_output, objects, date_time, scale_mm_pixel, analysis_params
FROM analysis_new
WHERE id = $1
`

func (q *Queries) GetAnalysisByID(ctx context.Context, id uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysisByID, id)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Product,
		&i.BotMessage,
		&i.FilesSource,
		&i.FilesOutput,
		&i.Objects,
		&i.DateTime,
		&i.ScaleMmPixel,
		&i.AnalysisParams,
	)
	return i, err
}

const getAnalysisImageMetaByID = `-- name: GetAnalysisImageMetaByID :one
SELECT files_source, files_output, objects
FROM analysis_new
WHERE id = $1
`

type GetAnalysisImageMetaByIDRow struct {
	FilesSource []string
	FilesOutput []string
	Objects     []byte
}

func (q *Queries) GetAnalysisImageMetaByID(ctx context.Context, id uuid.UUID) (GetAnalysisImageMetaByIDRow, error) {
	row := q.db.QueryRow(ctx, getAnalysisImageMetaByID, id)
	var i GetAnalysisImageMetaByIDRow
	err := row.Scan(&i.FilesSource, &i.FilesOutput, &i.Objects)
	return i, err
}
