// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package kalibr

import (
	"time"

	params "csort.ru/analysis-service/internal/params"
	uuid "github.com/google/uuid"
)

type Analysis struct {
	ID             uuid.UUID
	UserID         int64
	Source         *string
	Product        *string
	BotMessage     *string
	FilesSource    []string
	FilesOutput    []string
	Objects        []byte
	DateTime       time.Time
	ScaleMmPixel   *float64
	AnalysisParams *params.Params
}
