package proposal

import (
	"csort.ru/coffeebot/internal/database"
	"csort.ru/coffeebot/internal/weed/stats"
)

// pendingStatsMetrics holds the numeric columns shared by create/update pending weed stats.
type pendingStatsMetrics struct {
	wAvg, wMedian, wMin, wMax                         float32
	lAvg, lMedian, lMin, lMax                         float32
	sqAvg, sqMedian, sqMin, sqMax                     float32
	rAvg, rMedian, rMin, rMax                         float32
	gAvg, gMedian, gMin, gMax                         float32
	bAvg, bMedian, bMin, bMax                         float32
	hAvg, hMedian, hMin, hMax                         float32
	sAvg, sMedian, sMin, sMax                         float32
	vAvg, vMedian, vMin, vMax                         float32
	lwAvg, lwMedian, lwMin, lwMax                     float32
	brtAvg, brtMedian, brtMin, brtMax                 float32
	solidAvg, solidMedian, solidMin, solidMax         float32
	sqSqcrlAvg, sqSqcrlMedian, sqSqcrlMin, sqSqcrlMax float32
}

func metricsFromWeedStatistics(s *stats.WeedStatistics) pendingStatsMetrics {
	return pendingStatsMetrics{
		wAvg:          s.WAvg,
		wMedian:       s.WMedian,
		wMin:          s.WMin,
		wMax:          s.WMax,
		lAvg:          s.LAvg,
		lMedian:       s.LMedian,
		lMin:          s.LMin,
		lMax:          s.LMax,
		sqAvg:         s.SqAvg,
		sqMedian:      s.SqMedian,
		sqMin:         s.SqMin,
		sqMax:         s.SqMax,
		rAvg:          s.RAvg,
		rMedian:       s.RMedian,
		rMin:          s.RMin,
		rMax:          s.RMax,
		gAvg:          s.GAvg,
		gMedian:       s.GMedian,
		gMin:          s.GMin,
		gMax:          s.GMax,
		bAvg:          s.BAvg,
		bMedian:       s.BMedian,
		bMin:          s.BMin,
		bMax:          s.BMax,
		hAvg:          s.HAvg,
		hMedian:       s.HMedian,
		hMin:          s.HMin,
		hMax:          s.HMax,
		sAvg:          s.SAvg,
		sMedian:       s.SMedian,
		sMin:          s.SMin,
		sMax:          s.SMax,
		vAvg:          s.VAvg,
		vMedian:       s.VMedian,
		vMin:          s.VMin,
		vMax:          s.VMax,
		lwAvg:         s.LwAvg,
		lwMedian:      s.LwMedian,
		lwMin:         s.LwMin,
		lwMax:         s.LwMax,
		brtAvg:        s.BrtAvg,
		brtMedian:     s.BrtMedian,
		brtMin:        s.BrtMin,
		brtMax:        s.BrtMax,
		solidAvg:      s.SolidAvg,
		solidMedian:   s.SolidMedian,
		solidMin:      s.SolidMin,
		solidMax:      s.SolidMax,
		sqSqcrlAvg:    s.SqSqcrlAvg,
		sqSqcrlMedian: s.SqSqcrlMedian,
		sqSqcrlMin:    s.SqSqcrlMin,
		sqSqcrlMax:    s.SqSqcrlMax,
	}
}

func metricsFromWeedStat(ws database.WeedStat) pendingStatsMetrics {
	return pendingStatsMetrics{
		wAvg:          ws.WAvg,
		wMedian:       ws.WMedian,
		wMin:          ws.WMin,
		wMax:          ws.WMax,
		lAvg:          ws.LAvg,
		lMedian:       ws.LMedian,
		lMin:          ws.LMin,
		lMax:          ws.LMax,
		sqAvg:         ws.SqAvg,
		sqMedian:      ws.SqMedian,
		sqMin:         ws.SqMin,
		sqMax:         ws.SqMax,
		rAvg:          ws.RAvg,
		rMedian:       ws.RMedian,
		rMin:          ws.RMin,
		rMax:          ws.RMax,
		gAvg:          ws.GAvg,
		gMedian:       ws.GMedian,
		gMin:          ws.GMin,
		gMax:          ws.GMax,
		bAvg:          ws.BAvg,
		bMedian:       ws.BMedian,
		bMin:          ws.BMin,
		bMax:          ws.BMax,
		hAvg:          ws.HAvg,
		hMedian:       ws.HMedian,
		hMin:          ws.HMin,
		hMax:          ws.HMax,
		sAvg:          ws.SAvg,
		sMedian:       ws.SMedian,
		sMin:          ws.SMin,
		sMax:          ws.SMax,
		vAvg:          ws.VAvg,
		vMedian:       ws.VMedian,
		vMin:          ws.VMin,
		vMax:          ws.VMax,
		lwAvg:         ws.LwAvg,
		lwMedian:      ws.LwMedian,
		lwMin:         ws.LwMin,
		lwMax:         ws.LwMax,
		brtAvg:        ws.BrtAvg,
		brtMedian:     ws.BrtMedian,
		brtMin:        ws.BrtMin,
		brtMax:        ws.BrtMax,
		solidAvg:      ws.SolidAvg,
		solidMedian:   ws.SolidMedian,
		solidMin:      ws.SolidMin,
		solidMax:      ws.SolidMax,
		sqSqcrlAvg:    ws.SqSqcrlAvg,
		sqSqcrlMedian: ws.SqSqcrlMedian,
		sqSqcrlMin:    ws.SqSqcrlMin,
		sqSqcrlMax:    ws.SqSqcrlMax,
	}
}

func (m pendingStatsMetrics) toCreatePendingWeedStatsParams(
	pendingWeedID int32,
	excludedJSON []byte,
) database.CreatePendingWeedStatsParams {
	return database.CreatePendingWeedStatsParams{
		PendingWeedID:   pendingWeedID,
		WAvg:            m.wAvg,
		WMedian:         m.wMedian,
		WMin:            m.wMin,
		WMax:            m.wMax,
		LAvg:            m.lAvg,
		LMedian:         m.lMedian,
		LMin:            m.lMin,
		LMax:            m.lMax,
		SqAvg:           m.sqAvg,
		SqMedian:        m.sqMedian,
		SqMin:           m.sqMin,
		SqMax:           m.sqMax,
		RAvg:            m.rAvg,
		RMedian:         m.rMedian,
		RMin:            m.rMin,
		RMax:            m.rMax,
		GAvg:            m.gAvg,
		GMedian:         m.gMedian,
		GMin:            m.gMin,
		GMax:            m.gMax,
		BAvg:            m.bAvg,
		BMedian:         m.bMedian,
		BMin:            m.bMin,
		BMax:            m.bMax,
		HAvg:            m.hAvg,
		HMedian:         m.hMedian,
		HMin:            m.hMin,
		HMax:            m.hMax,
		SAvg:            m.sAvg,
		SMedian:         m.sMedian,
		SMin:            m.sMin,
		SMax:            m.sMax,
		VAvg:            m.vAvg,
		VMedian:         m.vMedian,
		VMin:            m.vMin,
		VMax:            m.vMax,
		LwAvg:           m.lwAvg,
		LwMedian:        m.lwMedian,
		LwMin:           m.lwMin,
		LwMax:           m.lwMax,
		BrtAvg:          m.brtAvg,
		BrtMedian:       m.brtMedian,
		BrtMin:          m.brtMin,
		BrtMax:          m.brtMax,
		SolidAvg:        m.solidAvg,
		SolidMedian:     m.solidMedian,
		SolidMin:        m.solidMin,
		SolidMax:        m.solidMax,
		SqSqcrlAvg:      m.sqSqcrlAvg,
		SqSqcrlMedian:   m.sqSqcrlMedian,
		SqSqcrlMin:      m.sqSqcrlMin,
		SqSqcrlMax:      m.sqSqcrlMax,
		ExcludedObjects: excludedJSON,
	}
}

func (m pendingStatsMetrics) toUpdatePendingWeedStatsParams(
	pendingWeedID int32,
	excludedJSON []byte,
) database.UpdatePendingWeedStatsParams {
	return database.UpdatePendingWeedStatsParams{
		WAvg:            m.wAvg,
		WMedian:         m.wMedian,
		WMin:            m.wMin,
		WMax:            m.wMax,
		LAvg:            m.lAvg,
		LMedian:         m.lMedian,
		LMin:            m.lMin,
		LMax:            m.lMax,
		SqAvg:           m.sqAvg,
		SqMedian:        m.sqMedian,
		SqMin:           m.sqMin,
		SqMax:           m.sqMax,
		RAvg:            m.rAvg,
		RMedian:         m.rMedian,
		RMin:            m.rMin,
		RMax:            m.rMax,
		GAvg:            m.gAvg,
		GMedian:         m.gMedian,
		GMin:            m.gMin,
		GMax:            m.gMax,
		BAvg:            m.bAvg,
		BMedian:         m.bMedian,
		BMin:            m.bMin,
		BMax:            m.bMax,
		HAvg:            m.hAvg,
		HMedian:         m.hMedian,
		HMin:            m.hMin,
		HMax:            m.hMax,
		SAvg:            m.sAvg,
		SMedian:         m.sMedian,
		SMin:            m.sMin,
		SMax:            m.sMax,
		VAvg:            m.vAvg,
		VMedian:         m.vMedian,
		VMin:            m.vMin,
		VMax:            m.vMax,
		LwAvg:           m.lwAvg,
		LwMedian:        m.lwMedian,
		LwMin:           m.lwMin,
		LwMax:           m.lwMax,
		BrtAvg:          m.brtAvg,
		BrtMedian:       m.brtMedian,
		BrtMin:          m.brtMin,
		BrtMax:          m.brtMax,
		SolidAvg:        m.solidAvg,
		SolidMedian:     m.solidMedian,
		SolidMin:        m.solidMin,
		SolidMax:        m.solidMax,
		SqSqcrlAvg:      m.sqSqcrlAvg,
		SqSqcrlMedian:   m.sqSqcrlMedian,
		SqSqcrlMin:      m.sqSqcrlMin,
		SqSqcrlMax:      m.sqSqcrlMax,
		ExcludedObjects: excludedJSON,
		PendingWeedID:   pendingWeedID,
	}
}

func newCreatePendingWeedStatsParams(
	pendingWeedID int32,
	s *stats.WeedStatistics,
	excludedJSON []byte,
) database.CreatePendingWeedStatsParams {
	return metricsFromWeedStatistics(s).toCreatePendingWeedStatsParams(pendingWeedID, excludedJSON)
}

func newUpdatePendingWeedStatsParams(
	pendingWeedID int32,
	s *stats.WeedStatistics,
	excludedJSON []byte,
) database.UpdatePendingWeedStatsParams {
	return metricsFromWeedStatistics(s).toUpdatePendingWeedStatsParams(pendingWeedID, excludedJSON)
}

func newCreatePendingWeedStatsFromWeedStat(
	pendingWeedID int32,
	ws database.WeedStat,
) database.CreatePendingWeedStatsParams {
	return metricsFromWeedStat(ws).toCreatePendingWeedStatsParams(pendingWeedID, ws.ExcludedObjects)
}

func metricsFromPendingWeedStat(ps database.PendingWeedStat) pendingStatsMetrics {
	return pendingStatsMetrics{
		wAvg:          ps.WAvg,
		wMedian:       ps.WMedian,
		wMin:          ps.WMin,
		wMax:          ps.WMax,
		lAvg:          ps.LAvg,
		lMedian:       ps.LMedian,
		lMin:          ps.LMin,
		lMax:          ps.LMax,
		sqAvg:         ps.SqAvg,
		sqMedian:      ps.SqMedian,
		sqMin:         ps.SqMin,
		sqMax:         ps.SqMax,
		rAvg:          ps.RAvg,
		rMedian:       ps.RMedian,
		rMin:          ps.RMin,
		rMax:          ps.RMax,
		gAvg:          ps.GAvg,
		gMedian:       ps.GMedian,
		gMin:          ps.GMin,
		gMax:          ps.GMax,
		bAvg:          ps.BAvg,
		bMedian:       ps.BMedian,
		bMin:          ps.BMin,
		bMax:          ps.BMax,
		hAvg:          ps.HAvg,
		hMedian:       ps.HMedian,
		hMin:          ps.HMin,
		hMax:          ps.HMax,
		sAvg:          ps.SAvg,
		sMedian:       ps.SMedian,
		sMin:          ps.SMin,
		sMax:          ps.SMax,
		vAvg:          ps.VAvg,
		vMedian:       ps.VMedian,
		vMin:          ps.VMin,
		vMax:          ps.VMax,
		lwAvg:         ps.LwAvg,
		lwMedian:      ps.LwMedian,
		lwMin:         ps.LwMin,
		lwMax:         ps.LwMax,
		brtAvg:        ps.BrtAvg,
		brtMedian:     ps.BrtMedian,
		brtMin:        ps.BrtMin,
		brtMax:        ps.BrtMax,
		solidAvg:      ps.SolidAvg,
		solidMedian:   ps.SolidMedian,
		solidMin:      ps.SolidMin,
		solidMax:      ps.SolidMax,
		sqSqcrlAvg:    ps.SqSqcrlAvg,
		sqSqcrlMedian: ps.SqSqcrlMedian,
		sqSqcrlMin:    ps.SqSqcrlMin,
		sqSqcrlMax:    ps.SqSqcrlMax,
	}
}

func weedStatisticsFromPendingWeedStat(
	dbStats database.PendingWeedStat,
	excludedObjects []int64,
) *stats.WeedStatistics {
	m := metricsFromPendingWeedStat(dbStats)
	return &stats.WeedStatistics{
		WAvg:            m.wAvg,
		WMedian:         m.wMedian,
		WMin:            m.wMin,
		WMax:            m.wMax,
		LAvg:            m.lAvg,
		LMedian:         m.lMedian,
		LMin:            m.lMin,
		LMax:            m.lMax,
		SqAvg:           m.sqAvg,
		SqMedian:        m.sqMedian,
		SqMin:           m.sqMin,
		SqMax:           m.sqMax,
		RAvg:            m.rAvg,
		RMedian:         m.rMedian,
		RMin:            m.rMin,
		RMax:            m.rMax,
		GAvg:            m.gAvg,
		GMedian:         m.gMedian,
		GMin:            m.gMin,
		GMax:            m.gMax,
		BAvg:            m.bAvg,
		BMedian:         m.bMedian,
		BMin:            m.bMin,
		BMax:            m.bMax,
		HAvg:            m.hAvg,
		HMedian:         m.hMedian,
		HMin:            m.hMin,
		HMax:            m.hMax,
		SAvg:            m.sAvg,
		SMedian:         m.sMedian,
		SMin:            m.sMin,
		SMax:            m.sMax,
		VAvg:            m.vAvg,
		VMedian:         m.vMedian,
		VMin:            m.vMin,
		VMax:            m.vMax,
		LwAvg:           m.lwAvg,
		LwMedian:        m.lwMedian,
		LwMin:           m.lwMin,
		LwMax:           m.lwMax,
		BrtAvg:          m.brtAvg,
		BrtMedian:       m.brtMedian,
		BrtMin:          m.brtMin,
		BrtMax:          m.brtMax,
		SolidAvg:        m.solidAvg,
		SolidMedian:     m.solidMedian,
		SolidMin:        m.solidMin,
		SolidMax:        m.solidMax,
		SqSqcrlAvg:      m.sqSqcrlAvg,
		SqSqcrlMedian:   m.sqSqcrlMedian,
		SqSqcrlMin:      m.sqSqcrlMin,
		SqSqcrlMax:      m.sqSqcrlMax,
		ExcludedObjects: excludedObjects,
	}
}
