// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package proposal

import (
	database "csort.ru/coffeebot/internal/database"
	pgxconv "csort.ru/coffeebot/internal/pgxconv"
)

type rowConverterImpl struct{}

func (c *rowConverterImpl) ListProposalsParamsToCountDB(source ListProposalsParams) database.CountCatalogProposalsParams {
	var databaseCountCatalogProposalsParams database.CountCatalogProposalsParams
	if source.Status != nil {
		xstring := *source.Status
		databaseCountCatalogProposalsParams.Status = &xstring
	}
	if source.RequestBy != nil {
		xint64 := *source.RequestBy
		databaseCountCatalogProposalsParams.RequestBy = &xint64
	}
	if source.ReviewedBy != nil {
		xint32 := *source.ReviewedBy
		databaseCountCatalogProposalsParams.ReviewedBy = &xint32
	}
	return databaseCountCatalogProposalsParams
}
func (c *rowConverterImpl) ListProposalsParamsToListDB(source ListProposalsParams) database.ListCatalogProposalsWithPendingWeedParams {
	var databaseListCatalogProposalsWithPendingWeedParams database.ListCatalogProposalsWithPendingWeedParams
	if source.Status != nil {
		xstring := *source.Status
		databaseListCatalogProposalsWithPendingWeedParams.Status = &xstring
	}
	if source.RequestBy != nil {
		xint64 := *source.RequestBy
		databaseListCatalogProposalsWithPendingWeedParams.RequestBy = &xint64
	}
	if source.ReviewedBy != nil {
		xint32 := *source.ReviewedBy
		databaseListCatalogProposalsWithPendingWeedParams.ReviewedBy = &xint32
	}
	databaseListCatalogProposalsWithPendingWeedParams.SortOrder = pgxconv.NonEmptyStringPtr(source.SortOrder)
	databaseListCatalogProposalsWithPendingWeedParams.Offset = source.PaginatedRequest.Offset
	databaseListCatalogProposalsWithPendingWeedParams.Limit = source.PaginatedRequest.Limit
	return databaseListCatalogProposalsWithPendingWeedParams
}
func (c *rowConverterImpl) ListRowToItem(source database.ListCatalogProposalsWithPendingWeedRow) ProposalListItem {
	var proposalProposalListItem ProposalListItem
	proposalProposalListItem.ID = source.ID
	proposalProposalListItem.Status = source.Status
	proposalProposalListItem.RequestBy = source.RequestBy
	if source.ReviewedBy != nil {
		xint32 := *source.ReviewedBy
		proposalProposalListItem.ReviewedBy = &xint32
	}
	proposalProposalListItem.ReviewedAt = pgxconv.TimestampToPtr(source.ReviewedAt)
	proposalProposalListItem.SubmittedAt = pgxconv.TimestamptzToPtr(source.SubmittedAt)
	if source.AppliedWeedID != nil {
		xint322 := *source.AppliedWeedID
		proposalProposalListItem.AppliedWeedID = &xint322
	}
	proposalProposalListItem.CreatedAt = pgxconv.TimestampToTime(source.CreatedAt)
	proposalProposalListItem.UpdatedAt = pgxconv.TimestampToTime(source.UpdatedAt)
	proposalProposalListItem.PendingName = source.PendingName
	return proposalProposalListItem
}
