// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot.sql

package database

import (
	"context"
	"time"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (name, token, platform)
VALUES ($1, $2, $3)
RETURNING id, name, token, platform, created_at, updated_at
`

type CreateBotParams struct {
	Name     string `json:"name"`
	Token    []byte `json:"token"`
	Platform string `json:"platform"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error) {
	row := q.db.QueryRow(ctx, createBot, arg.Name, arg.Token, arg.Platform)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBot = `-- name: DeleteBot :exec
DELETE
FROM bots
WHERE id = $1
`

func (q *Queries) DeleteBot(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBot, id)
	return err
}

const getBot = `-- name: GetBot :one
SELECT id, name, created_at, updated_at, token
FROM bots
WHERE id = $1
`

type GetBotRow struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Token     []byte    `json:"token"`
}

func (q *Queries) GetBot(ctx context.Context, id int32) (GetBotRow, error) {
	row := q.db.QueryRow(ctx, getBot, id)
	var i GetBotRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
	)
	return i, err
}

const getBotByName = `-- name: GetBotByName :one
SELECT id, name, token, platform, created_at, updated_at
FROM bots
WHERE name = $1 AND platform = 'telegram'
`

func (q *Queries) GetBotByName(ctx context.Context, name string) (Bot, error) {
	row := q.db.QueryRow(ctx, getBotByName, name)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotByNameAndPlatform = `-- name: GetBotByNameAndPlatform :one
SELECT id, name, token, platform, created_at, updated_at
FROM bots
WHERE name = $1 AND platform = $2
`

type GetBotByNameAndPlatformParams struct {
	Name     string `json:"name"`
	Platform string `json:"platform"`
}

func (q *Queries) GetBotByNameAndPlatform(ctx context.Context, arg GetBotByNameAndPlatformParams) (Bot, error) {
	row := q.db.QueryRow(ctx, getBotByNameAndPlatform, arg.Name, arg.Platform)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBots = `-- name: ListBots :many
SELECT id, name, platform, created_at, updated_at
FROM bots
ORDER BY name
`

type ListBotsRow struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Platform  string    `json:"platform"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListBots(ctx context.Context) ([]ListBotsRow, error) {
	rows, err := q.db.Query(ctx, listBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBotsRow{}
	for rows.Next() {
		var i ListBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotsByPlatform = `-- name: ListBotsByPlatform :many
SELECT id, name, token, platform, created_at, updated_at
FROM bots
WHERE platform = $1
ORDER BY id
`

func (q *Queries) ListBotsByPlatform(ctx context.Context, platform string) ([]Bot, error) {
	rows, err := q.db.Query(ctx, listBotsByPlatform, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bot{}
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotName = `-- name: UpdateBotName :one
UPDATE bots
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, token, platform, created_at, updated_at
`

type UpdateBotNameParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateBotName(ctx context.Context, arg UpdateBotNameParams) (Bot, error) {
	row := q.db.QueryRow(ctx, updateBotName, arg.ID, arg.Name)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotToken = `-- name: UpdateBotToken :one
UPDATE bots
SET token = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, token, platform, created_at, updated_at
`

type UpdateBotTokenParams struct {
	ID    int32  `json:"id"`
	Token []byte `json:"token"`
}

func (q *Queries) UpdateBotToken(ctx context.Context, arg UpdateBotTokenParams) (Bot, error) {
	row := q.db.QueryRow(ctx, updateBotToken, arg.ID, arg.Token)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
