// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bot struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Token     []byte    `json:"token"`
	Platform  string    `json:"platform"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Role struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Service struct {
	ServiceID     string    `json:"service_id"`
	ServiceSecret string    `json:"service_secret"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID               int32       `json:"id"`
	TelegramID       pgtype.Int8 `json:"telegram_id"`
	MaxID            pgtype.Int8 `json:"max_id"`
	Login            pgtype.Text `json:"login"`
	PasswordHash     pgtype.Text `json:"password_hash"`
	OrganizationName pgtype.Text `json:"organization_name"`
	Inn              pgtype.Text `json:"inn"`
	FullName         pgtype.Text `json:"full_name"`
	PhoneNumber      pgtype.Text `json:"phone_number"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type UserRecoveryCode struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type UserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}
