// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	ClearWebCredentials(ctx context.Context, id int32) error
	CopyWebCredentials(ctx context.Context, arg CopyWebCredentialsParams) error
	CountUsersByRole(ctx context.Context, roleID int32) (int64, error)
	CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error)
	CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (UserRecoveryCode, error)
	CreateRole(ctx context.Context, name string) (Role, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithMaxId(ctx context.Context, arg CreateUserWithMaxIdParams) (User, error)
	CreateWebUser(ctx context.Context, arg CreateWebUserParams) (User, error)
	DeleteBot(ctx context.Context, id int32) error
	DeleteRole(ctx context.Context, id int32) error
	DeleteService(ctx context.Context, serviceID string) error
	DeleteUser(ctx context.Context, id int32) error
	GetBot(ctx context.Context, id int32) (GetBotRow, error)
	GetBotByName(ctx context.Context, name string) (Bot, error)
	GetBotByNameAndPlatform(ctx context.Context, arg GetBotByNameAndPlatformParams) (Bot, error)
	GetRole(ctx context.Context, id int32) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetServiceByServiceID(ctx context.Context, serviceID string) (Service, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByLogin(ctx context.Context, lower string) (User, error)
	GetUserByMaxId(ctx context.Context, maxID pgtype.Int8) (User, error)
	GetUserByTelegramId(ctx context.Context, telegramID pgtype.Int8) (User, error)
	GetUserRoles(ctx context.Context, userID int32) ([]Role, error)
	IsServiceExists(ctx context.Context, serviceID string) (bool, error)
	LinkUserMaxId(ctx context.Context, arg LinkUserMaxIdParams) error
	LinkUserTelegramId(ctx context.Context, arg LinkUserTelegramIdParams) error
	ListBots(ctx context.Context) ([]ListBotsRow, error)
	ListBotsByPlatform(ctx context.Context, platform string) ([]Bot, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListServices(ctx context.Context) ([]ListServicesRow, error)
	ListUnusedRecoveryCodesByUser(ctx context.Context, userID int32) ([]UserRecoveryCode, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkRecoveryCodeUsed(ctx context.Context, id int32) error
	ReassignRecoveryCodes(ctx context.Context, arg ReassignRecoveryCodesParams) error
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error
	SetWebCredentials(ctx context.Context, arg SetWebCredentialsParams) (User, error)
	TransferWebCredentials(ctx context.Context, arg TransferWebCredentialsParams) error
	UpdateBotName(ctx context.Context, arg UpdateBotNameParams) (Bot, error)
	UpdateBotToken(ctx context.Context, arg UpdateBotTokenParams) (Bot, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertDevUser(ctx context.Context, arg UpsertDevUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
