// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery_code.sql

package database

import (
	"context"
)

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO user_recovery_codes (user_id, code_hash)
VALUES ($1, $2)
RETURNING id, user_id, code_hash, used_at, created_at
`

type CreateRecoveryCodeParams struct {
	UserID   int32  `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (UserRecoveryCode, error) {
	row := q.db.QueryRow(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	var i UserRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUnusedRecoveryCodesByUser = `-- name: ListUnusedRecoveryCodesByUser :many
SELECT id, user_id, code_hash, used_at, created_at FROM user_recovery_codes
WHERE user_id = $1 AND used_at IS NULL
ORDER BY id
`

func (q *Queries) ListUnusedRecoveryCodesByUser(ctx context.Context, userID int32) ([]UserRecoveryCode, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRecoveryCode{}
	for rows.Next() {
		var i UserRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE user_recovery_codes SET used_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markRecoveryCodeUsed, id)
	return err
}
