// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service.sql

package database

import (
	"context"
	"time"
)

const createService = `-- name: CreateService :one
INSERT INTO services (service_id, service_secret)
VALUES ($1, $2)
RETURNING service_id, service_secret, created_at, updated_at
`

type CreateServiceParams struct {
	ServiceID     string `json:"service_id"`
	ServiceSecret string `json:"service_secret"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService, arg.ServiceID, arg.ServiceSecret)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.ServiceSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE service_id = $1
`

func (q *Queries) DeleteService(ctx context.Context, serviceID string) error {
	_, err := q.db.Exec(ctx, deleteService, serviceID)
	return err
}

const getServiceByServiceID = `-- name: GetServiceByServiceID :one
SELECT service_id, service_secret, created_at, updated_at FROM services
WHERE service_id = $1 LIMIT 1
`

func (q *Queries) GetServiceByServiceID(ctx context.Context, serviceID string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByServiceID, serviceID)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.ServiceSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isServiceExists = `-- name: IsServiceExists :one
SELECT EXISTS(SELECT 1 FROM services WHERE service_id = $1) AS exists
`

func (q *Queries) IsServiceExists(ctx context.Context, serviceID string) (bool, error) {
	row := q.db.QueryRow(ctx, isServiceExists, serviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listServices = `-- name: ListServices :many
SELECT service_id, created_at, updated_at FROM services
ORDER BY created_at DESC
`

type ListServicesRow struct {
	ServiceID string    `json:"service_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesRow{}
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(&i.ServiceID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET service_secret = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE service_id = $1
RETURNING service_id, service_secret, created_at, updated_at
`

type UpdateServiceParams struct {
	ServiceID     string `json:"service_id"`
	ServiceSecret string `json:"service_secret"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService, arg.ServiceID, arg.ServiceSecret)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.ServiceSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
