// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWebCredentials = `-- name: ClearWebCredentials :exec
UPDATE users SET login = NULL, password_hash = NULL WHERE id = $1
`

func (q *Queries) ClearWebCredentials(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, clearWebCredentials, id)
	return err
}

const copyWebCredentials = `-- name: CopyWebCredentials :exec
UPDATE users
SET login = COALESCE(users.login, $2),
    password_hash = COALESCE(users.password_hash, $3)
WHERE id = $1
`

type CopyWebCredentialsParams struct {
	ID           int32       `json:"id"`
	Login        pgtype.Text `json:"login"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CopyWebCredentials(ctx context.Context, arg CopyWebCredentialsParams) error {
	_, err := q.db.Exec(ctx, copyWebCredentials, arg.ID, arg.Login, arg.PasswordHash)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (telegram_id, organization_name, inn, full_name, phone_number)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at
`

type CreateUserParams struct {
	TelegramID       pgtype.Int8 `json:"telegram_id"`
	OrganizationName pgtype.Text `json:"organization_name"`
	Inn              pgtype.Text `json:"inn"`
	FullName         pgtype.Text `json:"full_name"`
	PhoneNumber      pgtype.Text `json:"phone_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TelegramID,
		arg.OrganizationName,
		arg.Inn,
		arg.FullName,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithMaxId = `-- name: CreateUserWithMaxId :one
INSERT INTO users (max_id, organization_name, inn, full_name, phone_number)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at
`

type CreateUserWithMaxIdParams struct {
	MaxID            pgtype.Int8 `json:"max_id"`
	OrganizationName pgtype.Text `json:"organization_name"`
	Inn              pgtype.Text `json:"inn"`
	FullName         pgtype.Text `json:"full_name"`
	PhoneNumber      pgtype.Text `json:"phone_number"`
}

func (q *Queries) CreateUserWithMaxId(ctx context.Context, arg CreateUserWithMaxIdParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithMaxId,
		arg.MaxID,
		arg.OrganizationName,
		arg.Inn,
		arg.FullName,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebUser = `-- name: CreateWebUser :one
INSERT INTO users (login, password_hash, organization_name, inn, full_name, phone_number)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at
`

type CreateWebUserParams struct {
	Login            pgtype.Text `json:"login"`
	PasswordHash     pgtype.Text `json:"password_hash"`
	OrganizationName pgtype.Text `json:"organization_name"`
	Inn              pgtype.Text `json:"inn"`
	FullName         pgtype.Text `json:"full_name"`
	PhoneNumber      pgtype.Text `json:"phone_number"`
}

func (q *Queries) CreateWebUser(ctx context.Context, arg CreateWebUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createWebUser,
		arg.Login,
		arg.PasswordHash,
		arg.OrganizationName,
		arg.Inn,
		arg.FullName,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at FROM users
WHERE LOWER(login) = LOWER($1) LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByMaxId = `-- name: GetUserByMaxId :one
SELECT id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at FROM users
WHERE max_id = $1 LIMIT 1
`

func (q *Queries) GetUserByMaxId(ctx context.Context, maxID pgtype.Int8) (User, error) {
	row := q.db.QueryRow(ctx, getUserByMaxId, maxID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTelegramId = `-- name: GetUserByTelegramId :one
SELECT id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at FROM users
WHERE telegram_id = $1 LIMIT 1
`

func (q *Queries) GetUserByTelegramId(ctx context.Context, telegramID pgtype.Int8) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramId, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkUserMaxId = `-- name: LinkUserMaxId :exec
UPDATE users
SET max_id = $2
WHERE id = $1
`

type LinkUserMaxIdParams struct {
	ID    int32       `json:"id"`
	MaxID pgtype.Int8 `json:"max_id"`
}

func (q *Queries) LinkUserMaxId(ctx context.Context, arg LinkUserMaxIdParams) error {
	_, err := q.db.Exec(ctx, linkUserMaxId, arg.ID, arg.MaxID)
	return err
}

const linkUserTelegramId = `-- name: LinkUserTelegramId :exec
UPDATE users
SET telegram_id = $2
WHERE id = $1
`

type LinkUserTelegramIdParams struct {
	ID         int32       `json:"id"`
	TelegramID pgtype.Int8 `json:"telegram_id"`
}

func (q *Queries) LinkUserTelegramId(ctx context.Context, arg LinkUserTelegramIdParams) error {
	_, err := q.db.Exec(ctx, linkUserTelegramId, arg.ID, arg.TelegramID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at FROM users
ORDER BY full_name NULLS LAST
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.MaxID,
			&i.Login,
			&i.PasswordHash,
			&i.OrganizationName,
			&i.Inn,
			&i.FullName,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignRecoveryCodes = `-- name: ReassignRecoveryCodes :exec
UPDATE user_recovery_codes SET user_id = $2 WHERE user_id = $1
`

type ReassignRecoveryCodesParams struct {
	UserID   int32 `json:"user_id"`
	UserID_2 int32 `json:"user_id_2"`
}

func (q *Queries) ReassignRecoveryCodes(ctx context.Context, arg ReassignRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, reassignRecoveryCodes, arg.UserID, arg.UserID_2)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           int32       `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const setWebCredentials = `-- name: SetWebCredentials :one
UPDATE users
SET login = $2, password_hash = $3
WHERE id = $1
RETURNING id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at
`

type SetWebCredentialsParams struct {
	ID           int32       `json:"id"`
	Login        pgtype.Text `json:"login"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetWebCredentials(ctx context.Context, arg SetWebCredentialsParams) (User, error) {
	row := q.db.QueryRow(ctx, setWebCredentials, arg.ID, arg.Login, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transferWebCredentials = `-- name: TransferWebCredentials :exec
WITH src AS (
    SELECT login, password_hash FROM users WHERE users.id = $2
),
cleared AS (
    UPDATE users SET login = NULL, password_hash = NULL WHERE users.id = $2
)
UPDATE users AS keep
SET
    login = COALESCE(keep.login, src.login),
    password_hash = COALESCE(keep.password_hash, src.password_hash)
FROM src
WHERE keep.id = $1
    AND (src.login IS NOT NULL OR src.password_hash IS NOT NULL)
`

type TransferWebCredentialsParams struct {
	ID   int32 `json:"id"`
	ID_2 int32 `json:"id_2"`
}

func (q *Queries) TransferWebCredentials(ctx context.Context, arg TransferWebCredentialsParams) error {
	_, err := q.db.Exec(ctx, transferWebCredentials, arg.ID, arg.ID_2)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET organization_name = $2, inn = $3, full_name = $4, phone_number = $5
WHERE id = $1
RETURNING id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at
`

type UpdateUserParams struct {
	ID               int32       `json:"id"`
	OrganizationName pgtype.Text `json:"organization_name"`
	Inn              pgtype.Text `json:"inn"`
	FullName         pgtype.Text `json:"full_name"`
	PhoneNumber      pgtype.Text `json:"phone_number"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.OrganizationName,
		arg.Inn,
		arg.FullName,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDevUser = `-- name: UpsertDevUser :one
INSERT INTO users (login, password_hash, telegram_id, full_name)
VALUES ($1, $2, $3, 'Dev User')
ON CONFLICT (login) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    telegram_id = COALESCE(users.telegram_id, EXCLUDED.telegram_id)
RETURNING id, telegram_id, max_id, login, password_hash, organization_name, inn, full_name, phone_number, created_at, updated_at
`

type UpsertDevUserParams struct {
	Login        pgtype.Text `json:"login"`
	PasswordHash pgtype.Text `json:"password_hash"`
	TelegramID   pgtype.Int8 `json:"telegram_id"`
}

func (q *Queries) UpsertDevUser(ctx context.Context, arg UpsertDevUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertDevUser, arg.Login, arg.PasswordHash, arg.TelegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.MaxID,
		&i.Login,
		&i.PasswordHash,
		&i.OrganizationName,
		&i.Inn,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
