/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedUsersRouteImport } from './routes/_protected/users'
import { Route as ProtectedServicesRouteImport } from './routes/_protected/services'
import { Route as ProtectedRolesRouteImport } from './routes/_protected/roles'
import { Route as ProtectedBotsRouteImport } from './routes/_protected/bots'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedServicesRoute = ProtectedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRolesRoute = ProtectedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBotsRoute = ProtectedBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/bots': typeof ProtectedBotsRoute
  '/roles': typeof ProtectedRolesRoute
  '/services': typeof ProtectedServicesRoute
  '/users': typeof ProtectedUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bots': typeof ProtectedBotsRoute
  '/roles': typeof ProtectedRolesRoute
  '/services': typeof ProtectedServicesRoute
  '/users': typeof ProtectedUsersRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/bots': typeof ProtectedBotsRoute
  '/_protected/roles': typeof ProtectedRolesRoute
  '/_protected/services': typeof ProtectedServicesRoute
  '/_protected/users': typeof ProtectedUsersRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/bots' | '/roles' | '/services' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/bots' | '/roles' | '/services' | '/users' | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/bots'
    | '/_protected/roles'
    | '/_protected/services'
    | '/_protected/users'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/services': {
      id: '/_protected/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ProtectedServicesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/roles': {
      id: '/_protected/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof ProtectedRolesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bots': {
      id: '/_protected/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof ProtectedBotsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBotsRoute: typeof ProtectedBotsRoute
  ProtectedRolesRoute: typeof ProtectedRolesRoute
  ProtectedServicesRoute: typeof ProtectedServicesRoute
  ProtectedUsersRoute: typeof ProtectedUsersRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBotsRoute: ProtectedBotsRoute,
  ProtectedRolesRoute: ProtectedRolesRoute,
  ProtectedServicesRoute: ProtectedServicesRoute,
  ProtectedUsersRoute: ProtectedUsersRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
