/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRecoveryRouteImport } from './routes/reset-password-recovery'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMergeRouteImport } from './routes/_authenticated/merge'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedMarkupRouteImport } from './routes/_authenticated/markup'
import { Route as AuthenticatedClassificationRouteImport } from './routes/_authenticated/classification'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog/index'
import { Route as AuthenticatedAnalysisIndexRouteImport } from './routes/_authenticated/analysis/index'
import { Route as AuthenticatedSettingsWebAccessRouteImport } from './routes/_authenticated/settings/web-access'
import { Route as AuthenticatedSettingsLinkRouteImport } from './routes/_authenticated/settings/link'
import { Route as AuthenticatedCatalogAddRouteImport } from './routes/_authenticated/catalog/add'
import { Route as AuthenticatedAnalysisListRouteImport } from './routes/_authenticated/analysis/list'
import { Route as AuthenticatedAnalysisCreateRouteImport } from './routes/_authenticated/analysis/create'
import { Route as AuthenticatedCatalogProposalsIndexRouteImport } from './routes/_authenticated/catalog/proposals/index'
import { Route as AuthenticatedCatalogCatalogItemIdIndexRouteImport } from './routes/_authenticated/catalog/$catalogItemId/index'
import { Route as AuthenticatedCatalogProposalsProposalIdRouteImport } from './routes/_authenticated/catalog/proposals/$proposalId'
import { Route as AuthenticatedCatalogCatalogItemIdEditRouteImport } from './routes/_authenticated/catalog/$catalogItemId/edit'

const ResetPasswordRecoveryRoute = ResetPasswordRecoveryRouteImport.update({
  id: '/reset-password-recovery',
  path: '/reset-password-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMergeRoute = AuthenticatedMergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarkupRoute = AuthenticatedMarkupRouteImport.update({
  id: '/markup',
  path: '/markup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassificationRoute =
  AuthenticatedClassificationRouteImport.update({
    id: '/classification',
    path: '/classification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalysisIndexRoute =
  AuthenticatedAnalysisIndexRouteImport.update({
    id: '/analysis/',
    path: '/analysis/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsWebAccessRoute =
  AuthenticatedSettingsWebAccessRouteImport.update({
    id: '/settings/web-access',
    path: '/settings/web-access',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLinkRoute =
  AuthenticatedSettingsLinkRouteImport.update({
    id: '/settings/link',
    path: '/settings/link',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogAddRoute = AuthenticatedCatalogAddRouteImport.update({
  id: '/catalog/add',
  path: '/catalog/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysisListRoute =
  AuthenticatedAnalysisListRouteImport.update({
    id: '/analysis/list',
    path: '/analysis/list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalysisCreateRoute =
  AuthenticatedAnalysisCreateRouteImport.update({
    id: '/analysis/create',
    path: '/analysis/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogProposalsIndexRoute =
  AuthenticatedCatalogProposalsIndexRouteImport.update({
    id: '/catalog/proposals/',
    path: '/catalog/proposals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCatalogItemIdIndexRoute =
  AuthenticatedCatalogCatalogItemIdIndexRouteImport.update({
    id: '/catalog/$catalogItemId/',
    path: '/catalog/$catalogItemId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogProposalsProposalIdRoute =
  AuthenticatedCatalogProposalsProposalIdRouteImport.update({
    id: '/catalog/proposals/$proposalId',
    path: '/catalog/proposals/$proposalId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCatalogItemIdEditRoute =
  AuthenticatedCatalogCatalogItemIdEditRouteImport.update({
    id: '/catalog/$catalogItemId/edit',
    path: '/catalog/$catalogItemId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-recovery': typeof ResetPasswordRecoveryRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/classification': typeof AuthenticatedClassificationRoute
  '/markup': typeof AuthenticatedMarkupRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/merge': typeof AuthenticatedMergeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/analysis/create': typeof AuthenticatedAnalysisCreateRoute
  '/analysis/list': typeof AuthenticatedAnalysisListRoute
  '/catalog/add': typeof AuthenticatedCatalogAddRoute
  '/settings/link': typeof AuthenticatedSettingsLinkRoute
  '/settings/web-access': typeof AuthenticatedSettingsWebAccessRoute
  '/analysis/': typeof AuthenticatedAnalysisIndexRoute
  '/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/catalog/$catalogItemId/edit': typeof AuthenticatedCatalogCatalogItemIdEditRoute
  '/catalog/proposals/$proposalId': typeof AuthenticatedCatalogProposalsProposalIdRoute
  '/catalog/$catalogItemId/': typeof AuthenticatedCatalogCatalogItemIdIndexRoute
  '/catalog/proposals/': typeof AuthenticatedCatalogProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-recovery': typeof ResetPasswordRecoveryRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/classification': typeof AuthenticatedClassificationRoute
  '/markup': typeof AuthenticatedMarkupRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/merge': typeof AuthenticatedMergeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/analysis/create': typeof AuthenticatedAnalysisCreateRoute
  '/analysis/list': typeof AuthenticatedAnalysisListRoute
  '/catalog/add': typeof AuthenticatedCatalogAddRoute
  '/settings/link': typeof AuthenticatedSettingsLinkRoute
  '/settings/web-access': typeof AuthenticatedSettingsWebAccessRoute
  '/analysis': typeof AuthenticatedAnalysisIndexRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/catalog/$catalogItemId/edit': typeof AuthenticatedCatalogCatalogItemIdEditRoute
  '/catalog/proposals/$proposalId': typeof AuthenticatedCatalogProposalsProposalIdRoute
  '/catalog/$catalogItemId': typeof AuthenticatedCatalogCatalogItemIdIndexRoute
  '/catalog/proposals': typeof AuthenticatedCatalogProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-recovery': typeof ResetPasswordRecoveryRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/classification': typeof AuthenticatedClassificationRoute
  '/_authenticated/markup': typeof AuthenticatedMarkupRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/merge': typeof AuthenticatedMergeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/analysis/create': typeof AuthenticatedAnalysisCreateRoute
  '/_authenticated/analysis/list': typeof AuthenticatedAnalysisListRoute
  '/_authenticated/catalog/add': typeof AuthenticatedCatalogAddRoute
  '/_authenticated/settings/link': typeof AuthenticatedSettingsLinkRoute
  '/_authenticated/settings/web-access': typeof AuthenticatedSettingsWebAccessRoute
  '/_authenticated/analysis/': typeof AuthenticatedAnalysisIndexRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/catalog/$catalogItemId/edit': typeof AuthenticatedCatalogCatalogItemIdEditRoute
  '/_authenticated/catalog/proposals/$proposalId': typeof AuthenticatedCatalogProposalsProposalIdRoute
  '/_authenticated/catalog/$catalogItemId/': typeof AuthenticatedCatalogCatalogItemIdIndexRoute
  '/_authenticated/catalog/proposals/': typeof AuthenticatedCatalogProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-password-recovery'
    | '/admin'
    | '/classification'
    | '/markup'
    | '/menu'
    | '/merge'
    | '/profile'
    | '/analysis/create'
    | '/analysis/list'
    | '/catalog/add'
    | '/settings/link'
    | '/settings/web-access'
    | '/analysis/'
    | '/catalog/'
    | '/catalog/$catalogItemId/edit'
    | '/catalog/proposals/$proposalId'
    | '/catalog/$catalogItemId/'
    | '/catalog/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-password-recovery'
    | '/admin'
    | '/classification'
    | '/markup'
    | '/menu'
    | '/merge'
    | '/profile'
    | '/analysis/create'
    | '/analysis/list'
    | '/catalog/add'
    | '/settings/link'
    | '/settings/web-access'
    | '/analysis'
    | '/catalog'
    | '/catalog/$catalogItemId/edit'
    | '/catalog/proposals/$proposalId'
    | '/catalog/$catalogItemId'
    | '/catalog/proposals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-password-recovery'
    | '/_authenticated/admin'
    | '/_authenticated/classification'
    | '/_authenticated/markup'
    | '/_authenticated/menu'
    | '/_authenticated/merge'
    | '/_authenticated/profile'
    | '/_authenticated/analysis/create'
    | '/_authenticated/analysis/list'
    | '/_authenticated/catalog/add'
    | '/_authenticated/settings/link'
    | '/_authenticated/settings/web-access'
    | '/_authenticated/analysis/'
    | '/_authenticated/catalog/'
    | '/_authenticated/catalog/$catalogItemId/edit'
    | '/_authenticated/catalog/proposals/$proposalId'
    | '/_authenticated/catalog/$catalogItemId/'
    | '/_authenticated/catalog/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResetPasswordRecoveryRoute: typeof ResetPasswordRecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password-recovery': {
      id: '/reset-password-recovery'
      path: '/reset-password-recovery'
      fullPath: '/reset-password-recovery'
      preLoaderRoute: typeof ResetPasswordRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merge': {
      id: '/_authenticated/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof AuthenticatedMergeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/markup': {
      id: '/_authenticated/markup'
      path: '/markup'
      fullPath: '/markup'
      preLoaderRoute: typeof AuthenticatedMarkupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classification': {
      id: '/_authenticated/classification'
      path: '/classification'
      fullPath: '/classification'
      preLoaderRoute: typeof AuthenticatedClassificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis/': {
      id: '/_authenticated/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AuthenticatedAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/web-access': {
      id: '/_authenticated/settings/web-access'
      path: '/settings/web-access'
      fullPath: '/settings/web-access'
      preLoaderRoute: typeof AuthenticatedSettingsWebAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/link': {
      id: '/_authenticated/settings/link'
      path: '/settings/link'
      fullPath: '/settings/link'
      preLoaderRoute: typeof AuthenticatedSettingsLinkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/add': {
      id: '/_authenticated/catalog/add'
      path: '/catalog/add'
      fullPath: '/catalog/add'
      preLoaderRoute: typeof AuthenticatedCatalogAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis/list': {
      id: '/_authenticated/analysis/list'
      path: '/analysis/list'
      fullPath: '/analysis/list'
      preLoaderRoute: typeof AuthenticatedAnalysisListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis/create': {
      id: '/_authenticated/analysis/create'
      path: '/analysis/create'
      fullPath: '/analysis/create'
      preLoaderRoute: typeof AuthenticatedAnalysisCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/proposals/': {
      id: '/_authenticated/catalog/proposals/'
      path: '/catalog/proposals'
      fullPath: '/catalog/proposals/'
      preLoaderRoute: typeof AuthenticatedCatalogProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$catalogItemId/': {
      id: '/_authenticated/catalog/$catalogItemId/'
      path: '/catalog/$catalogItemId'
      fullPath: '/catalog/$catalogItemId/'
      preLoaderRoute: typeof AuthenticatedCatalogCatalogItemIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/proposals/$proposalId': {
      id: '/_authenticated/catalog/proposals/$proposalId'
      path: '/catalog/proposals/$proposalId'
      fullPath: '/catalog/proposals/$proposalId'
      preLoaderRoute: typeof AuthenticatedCatalogProposalsProposalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$catalogItemId/edit': {
      id: '/_authenticated/catalog/$catalogItemId/edit'
      path: '/catalog/$catalogItemId/edit'
      fullPath: '/catalog/$catalogItemId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogCatalogItemIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClassificationRoute: typeof AuthenticatedClassificationRoute
  AuthenticatedMarkupRoute: typeof AuthenticatedMarkupRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedMergeRoute: typeof AuthenticatedMergeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAnalysisCreateRoute: typeof AuthenticatedAnalysisCreateRoute
  AuthenticatedAnalysisListRoute: typeof AuthenticatedAnalysisListRoute
  AuthenticatedCatalogAddRoute: typeof AuthenticatedCatalogAddRoute
  AuthenticatedSettingsLinkRoute: typeof AuthenticatedSettingsLinkRoute
  AuthenticatedSettingsWebAccessRoute: typeof AuthenticatedSettingsWebAccessRoute
  AuthenticatedAnalysisIndexRoute: typeof AuthenticatedAnalysisIndexRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedCatalogCatalogItemIdEditRoute: typeof AuthenticatedCatalogCatalogItemIdEditRoute
  AuthenticatedCatalogProposalsProposalIdRoute: typeof AuthenticatedCatalogProposalsProposalIdRoute
  AuthenticatedCatalogCatalogItemIdIndexRoute: typeof AuthenticatedCatalogCatalogItemIdIndexRoute
  AuthenticatedCatalogProposalsIndexRoute: typeof AuthenticatedCatalogProposalsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClassificationRoute: AuthenticatedClassificationRoute,
  AuthenticatedMarkupRoute: AuthenticatedMarkupRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedMergeRoute: AuthenticatedMergeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAnalysisCreateRoute: AuthenticatedAnalysisCreateRoute,
  AuthenticatedAnalysisListRoute: AuthenticatedAnalysisListRoute,
  AuthenticatedCatalogAddRoute: AuthenticatedCatalogAddRoute,
  AuthenticatedSettingsLinkRoute: AuthenticatedSettingsLinkRoute,
  AuthenticatedSettingsWebAccessRoute: AuthenticatedSettingsWebAccessRoute,
  AuthenticatedAnalysisIndexRoute: AuthenticatedAnalysisIndexRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedCatalogCatalogItemIdEditRoute:
    AuthenticatedCatalogCatalogItemIdEditRoute,
  AuthenticatedCatalogProposalsProposalIdRoute:
    AuthenticatedCatalogProposalsProposalIdRoute,
  AuthenticatedCatalogCatalogItemIdIndexRoute:
    AuthenticatedCatalogCatalogItemIdIndexRoute,
  AuthenticatedCatalogProposalsIndexRoute:
    AuthenticatedCatalogProposalsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResetPasswordRecoveryRoute: ResetPasswordRecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
