package stats

type WeedStatistics struct {
	ExcludedObjects []int64 `json:"excluded_objects,omitempty"`
	WAvg            float32 `json:"w_avg"`
	WMedian         float32 `json:"w_median"`
	WMin            float32 `json:"w_min"`
	WMax            float32 `json:"w_max"`
	LAvg            float32 `json:"l_avg"`
	LMedian         float32 `json:"l_median"`
	LMin            float32 `json:"l_min"`
	LMax            float32 `json:"l_max"`
	SqAvg           float32 `json:"sq_avg"`
	SqMedian        float32 `json:"sq_median"`
	SqMin           float32 `json:"sq_min"`
	SqMax           float32 `json:"sq_max"`
	RAvg            float32 `json:"r_avg"`
	RMedian         float32 `json:"r_median"`
	RMin            float32 `json:"r_min"`
	RMax            float32 `json:"r_max"`
	GAvg            float32 `json:"g_avg"`
	GMedian         float32 `json:"g_median"`
	GMin            float32 `json:"g_min"`
	GMax            float32 `json:"g_max"`
	BAvg            float32 `json:"b_avg"`
	BMedian         float32 `json:"b_median"`
	BMin            float32 `json:"b_min"`
	BMax            float32 `json:"b_max"`
	HAvg            float32 `json:"h_avg"`
	HMedian         float32 `json:"h_median"`
	HMin            float32 `json:"h_min"`
	HMax            float32 `json:"h_max"`
	SAvg            float32 `json:"s_avg"`
	SMedian         float32 `json:"s_median"`
	SMin            float32 `json:"s_min"`
	SMax            float32 `json:"s_max"`
	VAvg            float32 `json:"v_avg"`
	VMedian         float32 `json:"v_median"`
	VMin            float32 `json:"v_min"`
	VMax            float32 `json:"v_max"`
	LwAvg           float32 `json:"lw_avg"`
	LwMedian        float32 `json:"lw_median"`
	LwMin           float32 `json:"lw_min"`
	LwMax           float32 `json:"lw_max"`
	BrtAvg          float32 `json:"brt_avg"`
	BrtMedian       float32 `json:"brt_median"`
	BrtMin          float32 `json:"brt_min"`
	BrtMax          float32 `json:"brt_max"`
	SolidAvg        float32 `json:"solid_avg"`
	SolidMedian     float32 `json:"solid_median"`
	SolidMin        float32 `json:"solid_min"`
	SolidMax        float32 `json:"solid_max"`
	SqSqcrlAvg      float32 `json:"sq_sqcrl_avg"`
	SqSqcrlMedian   float32 `json:"sq_sqcrl_median"`
	SqSqcrlMin      float32 `json:"sq_sqcrl_min"`
	SqSqcrlMax      float32 `json:"sq_sqcrl_max"`
}
