// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merge.sql

package requests

import (
	"context"
)

const mergeReassignRequests = `-- name: MergeReassignRequests :exec
UPDATE requests
SET user_id = $2
WHERE user_id = $1
`

type MergeReassignRequestsParams struct {
	UserID   string
	UserID_2 string
}

func (q *Queries) MergeReassignRequests(ctx context.Context, arg MergeReassignRequestsParams) error {
	_, err := q.db.Exec(ctx, mergeReassignRequests, arg.UserID, arg.UserID_2)
	return err
}
