// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package requests

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RequestStatus string

const (
	RequestStatusCreated                RequestStatus = "created"
	RequestStatusProcessing             RequestStatus = "processing"
	RequestStatusWaitingForConfirmation RequestStatus = "waiting_for_confirmation"
	RequestStatusCompleted              RequestStatus = "completed"
	RequestStatusFailed                 RequestStatus = "failed"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus
	Valid         bool // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type OutboxMessage struct {
	ID          pgtype.UUID
	Topic       string
	Payload     []byte
	Status      string
	CreatedAt   pgtype.Timestamptz
	ClaimedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type Request struct {
	ID             string
	UserID         string
	Platform       string
	Product        string
	Status         RequestStatus
	Year           *string
	MassLiter      *float64
	Location       *string
	Images         []byte
	Classification []byte
	Mass1000       *float64
	Mass           *float64
	TempID         *string
	ErrorMessage   *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
