// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package requests

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxMessages = `-- name: ClaimOutboxMessages :many
WITH to_claim AS (
  SELECT id FROM outbox_messages
  WHERE status = 'pending'
  ORDER BY created_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE outbox_messages m
SET status = 'claimed', claimed_at = now()
FROM to_claim tc
WHERE m.id = tc.id
RETURNING m.id, m.topic, m.payload, m.status, m.created_at, m.claimed_at, m.published_at
`

func (q *Queries) ClaimOutboxMessages(ctx context.Context, limit int32) ([]OutboxMessage, error) {
	rows, err := q.db.Query(ctx, claimOutboxMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxMessage{}
	for rows.Next() {
		var i OutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxMessage = `-- name: CreateOutboxMessage :one
INSERT INTO outbox_messages (
    topic, payload, status
) VALUES (
    $1, $2, $3
)
RETURNING id, topic, payload, status, created_at, claimed_at, published_at
`

type CreateOutboxMessageParams struct {
	Topic   string
	Payload []byte
	Status  string
}

func (q *Queries) CreateOutboxMessage(ctx context.Context, arg CreateOutboxMessageParams) (OutboxMessage, error) {
	row := q.db.QueryRow(ctx, createOutboxMessage, arg.Topic, arg.Payload, arg.Status)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.PublishedAt,
	)
	return i, err
}

const deletePublishedOutboxMessages = `-- name: DeletePublishedOutboxMessages :exec
DELETE FROM outbox_messages
WHERE status = 'published' AND published_at < (now() - INTERVAL '1 day')::TIMESTAMPTZ
`

func (q *Queries) DeletePublishedOutboxMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deletePublishedOutboxMessages)
	return err
}

const markOutboxMessageAsPublished = `-- name: MarkOutboxMessageAsPublished :exec
UPDATE outbox_messages
SET status = 'published', published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxMessageAsPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxMessageAsPublished, id)
	return err
}

const resetStuckClaimedOutboxMessages = `-- name: ResetStuckClaimedOutboxMessages :exec
UPDATE outbox_messages
SET status = 'pending', claimed_at = NULL
WHERE status = 'claimed' AND claimed_at < (now() - INTERVAL '10 minutes')::TIMESTAMPTZ
`

func (q *Queries) ResetStuckClaimedOutboxMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStuckClaimedOutboxMessages)
	return err
}
