// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package requests

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
    id, user_id, platform, product, status, images, classification, year, mass_liter, location, mass_1000, mass, temp_id
) VALUES (
    $1, $2, $3, $4, 'created', $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, platform, product, status, year, mass_liter, location, images, classification, mass_1000, mass, temp_id, error_message, created_at, updated_at
`

type CreateRequestParams struct {
	ID             string
	UserID         string
	Platform       string
	Product        string
	Images         []byte
	Classification []byte
	Year           *string
	MassLiter      *float64
	Location       *string
	Mass1000       *float64
	Mass           *float64
	TempID         *string
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.Product,
		arg.Images,
		arg.Classification,
		arg.Year,
		arg.MassLiter,
		arg.Location,
		arg.Mass1000,
		arg.Mass,
		arg.TempID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Product,
		&i.Status,
		&i.Year,
		&i.MassLiter,
		&i.Location,
		&i.Images,
		&i.Classification,
		&i.Mass1000,
		&i.Mass,
		&i.TempID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests
WHERE id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRequest, id)
	return err
}

const deleteRequestsByIDs = `-- name: DeleteRequestsByIDs :exec
DELETE FROM requests
WHERE id = ANY($1::varchar[])
`

func (q *Queries) DeleteRequestsByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteRequestsByIDs, dollar_1)
	return err
}

const getOldRequestsBatch = `-- name: GetOldRequestsBatch :many
SELECT id, images FROM requests
WHERE (
    (status = 'completed' AND created_at < (now() - INTERVAL '7 days')::TIMESTAMPTZ)
    OR
    (status IN ('failed') AND created_at < (now() - INTERVAL '1 day')::TIMESTAMPTZ)
)
ORDER BY created_at ASC
LIMIT $1
`

type GetOldRequestsBatchRow struct {
	ID     string
	Images []byte
}

func (q *Queries) GetOldRequestsBatch(ctx context.Context, limit int32) ([]GetOldRequestsBatchRow, error) {
	rows, err := q.db.Query(ctx, getOldRequestsBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOldRequestsBatchRow{}
	for rows.Next() {
		var i GetOldRequestsBatchRow
		if err := rows.Scan(&i.ID, &i.Images); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequest = `-- name: GetRequest :one
SELECT id, user_id, platform, product, status, year, mass_liter, location, images, classification, mass_1000, mass, temp_id, error_message, created_at, updated_at FROM requests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Product,
		&i.Status,
		&i.Year,
		&i.MassLiter,
		&i.Location,
		&i.Images,
		&i.Classification,
		&i.Mass1000,
		&i.Mass,
		&i.TempID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestByIDAndUserPairs = `-- name: GetRequestByIDAndUserPairs :one
SELECT id, user_id, platform, product, status, year, mass_liter, location, images, classification, mass_1000, mass, temp_id, error_message, created_at, updated_at FROM requests
WHERE id = $1 AND ((user_id = $2 AND platform = $3) OR (user_id = $4 AND platform = $5))
LIMIT 1
`

type GetRequestByIDAndUserPairsParams struct {
	ID         string
	UserID     string
	Platform   string
	UserID_2   string
	Platform_2 string
}

func (q *Queries) GetRequestByIDAndUserPairs(ctx context.Context, arg GetRequestByIDAndUserPairsParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByIDAndUserPairs,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.UserID_2,
		arg.Platform_2,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Product,
		&i.Status,
		&i.Year,
		&i.MassLiter,
		&i.Location,
		&i.Images,
		&i.Classification,
		&i.Mass1000,
		&i.Mass,
		&i.TempID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStuckProcessingJobsBatch = `-- name: GetStuckProcessingJobsBatch :many
SELECT id, images FROM requests
WHERE status = 'processing'
AND updated_at < (now() - INTERVAL '10 minutes')::TIMESTAMPTZ
ORDER BY updated_at ASC
LIMIT $1
`

type GetStuckProcessingJobsBatchRow struct {
	ID     string
	Images []byte
}

func (q *Queries) GetStuckProcessingJobsBatch(ctx context.Context, limit int32) ([]GetStuckProcessingJobsBatchRow, error) {
	rows, err := q.db.Query(ctx, getStuckProcessingJobsBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStuckProcessingJobsBatchRow{}
	for rows.Next() {
		var i GetStuckProcessingJobsBatchRow
		if err := rows.Scan(&i.ID, &i.Images); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByUserIDAndPlatform = `-- name: ListRequestsByUserIDAndPlatform :many
SELECT
    id, user_id, platform, product, status, year, mass_liter, location, images,
    mass_1000, mass, temp_id, error_message, created_at, updated_at
FROM requests
WHERE user_id = $1 AND platform = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListRequestsByUserIDAndPlatformParams struct {
	UserID   string
	Platform string
	Limit    int32
	Offset   int32
}

type ListRequestsByUserIDAndPlatformRow struct {
	ID           string
	UserID       string
	Platform     string
	Product      string
	Status       RequestStatus
	Year         *string
	MassLiter    *float64
	Location     *string
	Images       []byte
	Mass1000     *float64
	Mass         *float64
	TempID       *string
	ErrorMessage *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListRequestsByUserIDAndPlatform(ctx context.Context, arg ListRequestsByUserIDAndPlatformParams) ([]ListRequestsByUserIDAndPlatformRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByUserIDAndPlatform,
		arg.UserID,
		arg.Platform,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByUserIDAndPlatformRow{}
	for rows.Next() {
		var i ListRequestsByUserIDAndPlatformRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Product,
			&i.Status,
			&i.Year,
			&i.MassLiter,
			&i.Location,
			&i.Images,
			&i.Mass1000,
			&i.Mass,
			&i.TempID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByUserIDAndPlatformAndStatus = `-- name: ListRequestsByUserIDAndPlatformAndStatus :many
SELECT
    id, user_id, platform, product, status, year, mass_liter, location, images,
    mass_1000, mass, temp_id, error_message, created_at, updated_at
FROM requests
WHERE user_id = $1 AND platform = $2 AND status = $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListRequestsByUserIDAndPlatformAndStatusParams struct {
	UserID   string
	Platform string
	Status   RequestStatus
	Limit    int32
	Offset   int32
}

type ListRequestsByUserIDAndPlatformAndStatusRow struct {
	ID           string
	UserID       string
	Platform     string
	Product      string
	Status       RequestStatus
	Year         *string
	MassLiter    *float64
	Location     *string
	Images       []byte
	Mass1000     *float64
	Mass         *float64
	TempID       *string
	ErrorMessage *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListRequestsByUserIDAndPlatformAndStatus(ctx context.Context, arg ListRequestsByUserIDAndPlatformAndStatusParams) ([]ListRequestsByUserIDAndPlatformAndStatusRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByUserIDAndPlatformAndStatus,
		arg.UserID,
		arg.Platform,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByUserIDAndPlatformAndStatusRow{}
	for rows.Next() {
		var i ListRequestsByUserIDAndPlatformAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Product,
			&i.Status,
			&i.Year,
			&i.MassLiter,
			&i.Location,
			&i.Images,
			&i.Mass1000,
			&i.Mass,
			&i.TempID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByUserPlatformPairs = `-- name: ListRequestsByUserPlatformPairs :many
SELECT
    id, user_id, platform, product, status, year, mass_liter, location, images,
    mass_1000, mass, temp_id, error_message, created_at, updated_at
FROM requests
WHERE (user_id = $1 AND platform = $2)
   OR ($3 <> '' AND user_id = $3 AND platform = $4)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListRequestsByUserPlatformPairsParams struct {
	UserID1   string
	Platform1 string
	UserID2   interface{}
	Platform2 string
	Offset    int32
	Limit     int32
}

type ListRequestsByUserPlatformPairsRow struct {
	ID           string
	UserID       string
	Platform     string
	Product      string
	Status       RequestStatus
	Year         *string
	MassLiter    *float64
	Location     *string
	Images       []byte
	Mass1000     *float64
	Mass         *float64
	TempID       *string
	ErrorMessage *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListRequestsByUserPlatformPairs(ctx context.Context, arg ListRequestsByUserPlatformPairsParams) ([]ListRequestsByUserPlatformPairsRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByUserPlatformPairs,
		arg.UserID1,
		arg.Platform1,
		arg.UserID2,
		arg.Platform2,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByUserPlatformPairsRow{}
	for rows.Next() {
		var i ListRequestsByUserPlatformPairsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Product,
			&i.Status,
			&i.Year,
			&i.MassLiter,
			&i.Location,
			&i.Images,
			&i.Mass1000,
			&i.Mass,
			&i.TempID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByUserPlatformPairsAndStatus = `-- name: ListRequestsByUserPlatformPairsAndStatus :many
SELECT
    id, user_id, platform, product, status, year, mass_liter, location, images,
    mass_1000, mass, temp_id, error_message, created_at, updated_at
FROM requests
WHERE ((user_id = $1 AND platform = $2)
    OR ($3 <> '' AND user_id = $3 AND platform = $4))
  AND status = $5
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListRequestsByUserPlatformPairsAndStatusParams struct {
	UserID1   string
	Platform1 string
	UserID2   interface{}
	Platform2 string
	Status    RequestStatus
	Offset    int32
	Limit     int32
}

type ListRequestsByUserPlatformPairsAndStatusRow struct {
	ID           string
	UserID       string
	Platform     string
	Product      string
	Status       RequestStatus
	Year         *string
	MassLiter    *float64
	Location     *string
	Images       []byte
	Mass1000     *float64
	Mass         *float64
	TempID       *string
	ErrorMessage *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListRequestsByUserPlatformPairsAndStatus(ctx context.Context, arg ListRequestsByUserPlatformPairsAndStatusParams) ([]ListRequestsByUserPlatformPairsAndStatusRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByUserPlatformPairsAndStatus,
		arg.UserID1,
		arg.Platform1,
		arg.UserID2,
		arg.Platform2,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByUserPlatformPairsAndStatusRow{}
	for rows.Next() {
		var i ListRequestsByUserPlatformPairsAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Product,
			&i.Status,
			&i.Year,
			&i.MassLiter,
			&i.Location,
			&i.Images,
			&i.Mass1000,
			&i.Mass,
			&i.TempID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRequestAsCompleted = `-- name: MarkRequestAsCompleted :exec
UPDATE requests
SET status = 'completed', temp_id = $2, updated_at = now()
WHERE id = $1
`

type MarkRequestAsCompletedParams struct {
	ID     string
	TempID *string
}

func (q *Queries) MarkRequestAsCompleted(ctx context.Context, arg MarkRequestAsCompletedParams) error {
	_, err := q.db.Exec(ctx, markRequestAsCompleted, arg.ID, arg.TempID)
	return err
}

const markRequestAsCompletedIfWaiting = `-- name: MarkRequestAsCompletedIfWaiting :execrows
UPDATE requests
SET status = 'completed', temp_id = $2, updated_at = now()
WHERE id = $1 AND status = 'waiting_for_confirmation'
`

type MarkRequestAsCompletedIfWaitingParams struct {
	ID     string
	TempID *string
}

func (q *Queries) MarkRequestAsCompletedIfWaiting(ctx context.Context, arg MarkRequestAsCompletedIfWaitingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRequestAsCompletedIfWaiting, arg.ID, arg.TempID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRequestAsFailed = `-- name: MarkRequestAsFailed :exec
UPDATE requests
SET 
    status = 'failed', 
    error_message = $2,
    updated_at = now()
WHERE id = $1
`

type MarkRequestAsFailedParams struct {
	ID           string
	ErrorMessage *string
}

func (q *Queries) MarkRequestAsFailed(ctx context.Context, arg MarkRequestAsFailedParams) error {
	_, err := q.db.Exec(ctx, markRequestAsFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markRequestAsProcessing = `-- name: MarkRequestAsProcessing :exec
UPDATE requests
SET status = 'processing', updated_at = now()
WHERE id = $1 AND status = 'created'
`

func (q *Queries) MarkRequestAsProcessing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRequestAsProcessing, id)
	return err
}

const markRequestAsWaitingForConfirmation = `-- name: MarkRequestAsWaitingForConfirmation :exec
UPDATE requests
SET 
    status = 'waiting_for_confirmation',
    temp_id = $2,
    updated_at = now()
WHERE id = $1
`

type MarkRequestAsWaitingForConfirmationParams struct {
	ID     string
	TempID *string
}

func (q *Queries) MarkRequestAsWaitingForConfirmation(ctx context.Context, arg MarkRequestAsWaitingForConfirmationParams) error {
	_, err := q.db.Exec(ctx, markRequestAsWaitingForConfirmation, arg.ID, arg.TempID)
	return err
}

const markRequestsAsFailedByIDs = `-- name: MarkRequestsAsFailedByIDs :exec
UPDATE requests
SET
    status = 'failed',
    error_message = $1,
    updated_at = now()
WHERE id = ANY($2::varchar[]) AND status = 'processing'
`

type MarkRequestsAsFailedByIDsParams struct {
	ErrorMessage *string
	Column2      []string
}

func (q *Queries) MarkRequestsAsFailedByIDs(ctx context.Context, arg MarkRequestsAsFailedByIDsParams) error {
	_, err := q.db.Exec(ctx, markRequestsAsFailedByIDs, arg.ErrorMessage, arg.Column2)
	return err
}
