// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogProposal struct {
	ID            int32              `json:"id"`
	Status        string             `json:"status"`
	RequestBy     int64              `json:"request_by"`
	TargetWeedID  *int32             `json:"target_weed_id"`
	ReviewedBy    *int32             `json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamp   `json:"reviewed_at"`
	ReviewNotes   *string            `json:"review_notes"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	AppliedBy     *int32             `json:"applied_by"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
	AppliedWeedID *int32             `json:"applied_weed_id"`
	CreatedAt     pgtype.Timestamp   `json:"created_at"`
	UpdatedAt     pgtype.Timestamp   `json:"updated_at"`
}

type PendingWeed struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	LatinName    *string            `json:"latin_name"`
	Description  *string            `json:"description"`
	Length       *float32           `json:"length"`
	Width        *float32           `json:"width"`
	MainGroup    *string            `json:"main_group"`
	MainSubgroup *string            `json:"main_subgroup"`
	Subgroup     *string            `json:"subgroup"`
	IsQuarantine bool               `json:"is_quarantine"`
	Harmfulness  *string            `json:"harmfulness"`
	ProposalID   int32              `json:"proposal_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PendingWeedAnalysis struct {
	ID            int32  `json:"id"`
	PendingWeedID int32  `json:"pending_weed_id"`
	AnalysisID    string `json:"analysis_id"`
}

type PendingWeedImage struct {
	ID            int32              `json:"id"`
	PendingWeedID int32              `json:"pending_weed_id"`
	ImageKey      string             `json:"image_key"`
	IsPrimary     bool               `json:"is_primary"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PendingWeedStat struct {
	ID              int32              `json:"id"`
	PendingWeedID   int32              `json:"pending_weed_id"`
	WAvg            float32            `json:"w_avg"`
	WMedian         float32            `json:"w_median"`
	WMin            float32            `json:"w_min"`
	WMax            float32            `json:"w_max"`
	LAvg            float32            `json:"l_avg"`
	LMedian         float32            `json:"l_median"`
	LMin            float32            `json:"l_min"`
	LMax            float32            `json:"l_max"`
	SqAvg           float32            `json:"sq_avg"`
	SqMedian        float32            `json:"sq_median"`
	SqMin           float32            `json:"sq_min"`
	SqMax           float32            `json:"sq_max"`
	RAvg            float32            `json:"r_avg"`
	RMedian         float32            `json:"r_median"`
	RMin            float32            `json:"r_min"`
	RMax            float32            `json:"r_max"`
	GAvg            float32            `json:"g_avg"`
	GMedian         float32            `json:"g_median"`
	GMin            float32            `json:"g_min"`
	GMax            float32            `json:"g_max"`
	BAvg            float32            `json:"b_avg"`
	BMedian         float32            `json:"b_median"`
	BMin            float32            `json:"b_min"`
	BMax            float32            `json:"b_max"`
	HAvg            float32            `json:"h_avg"`
	HMedian         float32            `json:"h_median"`
	HMin            float32            `json:"h_min"`
	HMax            float32            `json:"h_max"`
	SAvg            float32            `json:"s_avg"`
	SMedian         float32            `json:"s_median"`
	SMin            float32            `json:"s_min"`
	SMax            float32            `json:"s_max"`
	VAvg            float32            `json:"v_avg"`
	VMedian         float32            `json:"v_median"`
	VMin            float32            `json:"v_min"`
	VMax            float32            `json:"v_max"`
	LwAvg           float32            `json:"lw_avg"`
	LwMedian        float32            `json:"lw_median"`
	LwMin           float32            `json:"lw_min"`
	LwMax           float32            `json:"lw_max"`
	BrtAvg          float32            `json:"brt_avg"`
	BrtMedian       float32            `json:"brt_median"`
	BrtMin          float32            `json:"brt_min"`
	BrtMax          float32            `json:"brt_max"`
	SolidAvg        float32            `json:"solid_avg"`
	SolidMedian     float32            `json:"solid_median"`
	SolidMin        float32            `json:"solid_min"`
	SolidMax        float32            `json:"solid_max"`
	SqSqcrlAvg      float32            `json:"sq_sqcrl_avg"`
	SqSqcrlMedian   float32            `json:"sq_sqcrl_median"`
	SqSqcrlMin      float32            `json:"sq_sqcrl_min"`
	SqSqcrlMax      float32            `json:"sq_sqcrl_max"`
	ExcludedObjects []byte             `json:"excluded_objects"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Weed struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	LatinName    *string            `json:"latin_name"`
	Description  *string            `json:"description"`
	Length       *float32           `json:"length"`
	Width        *float32           `json:"width"`
	MainGroup    *string            `json:"main_group"`
	MainSubgroup *string            `json:"main_subgroup"`
	Subgroup     *string            `json:"subgroup"`
	IsQuarantine bool               `json:"is_quarantine"`
	Harmfulness  *string            `json:"harmfulness"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WeedAnalysis struct {
	ID         int32  `json:"id"`
	WeedID     int32  `json:"weed_id"`
	AnalysisID string `json:"analysis_id"`
}

type WeedImage struct {
	ID        int32              `json:"id"`
	WeedID    int32              `json:"weed_id"`
	ImageKey  string             `json:"image_key"`
	IsPrimary bool               `json:"is_primary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WeedNote struct {
	ID        int32              `json:"id"`
	WeedID    int32              `json:"weed_id"`
	Note      string             `json:"note"`
	CreatedBy int32              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WeedStat struct {
	ID              int32              `json:"id"`
	WeedID          int32              `json:"weed_id"`
	WAvg            float32            `json:"w_avg"`
	WMedian         float32            `json:"w_median"`
	WMin            float32            `json:"w_min"`
	WMax            float32            `json:"w_max"`
	LAvg            float32            `json:"l_avg"`
	LMedian         float32            `json:"l_median"`
	LMin            float32            `json:"l_min"`
	LMax            float32            `json:"l_max"`
	SqAvg           float32            `json:"sq_avg"`
	SqMedian        float32            `json:"sq_median"`
	SqMin           float32            `json:"sq_min"`
	SqMax           float32            `json:"sq_max"`
	RAvg            float32            `json:"r_avg"`
	RMedian         float32            `json:"r_median"`
	RMin            float32            `json:"r_min"`
	RMax            float32            `json:"r_max"`
	GAvg            float32            `json:"g_avg"`
	GMedian         float32            `json:"g_median"`
	GMin            float32            `json:"g_min"`
	GMax            float32            `json:"g_max"`
	BAvg            float32            `json:"b_avg"`
	BMedian         float32            `json:"b_median"`
	BMin            float32            `json:"b_min"`
	BMax            float32            `json:"b_max"`
	HAvg            float32            `json:"h_avg"`
	HMedian         float32            `json:"h_median"`
	HMin            float32            `json:"h_min"`
	HMax            float32            `json:"h_max"`
	SAvg            float32            `json:"s_avg"`
	SMedian         float32            `json:"s_median"`
	SMin            float32            `json:"s_min"`
	SMax            float32            `json:"s_max"`
	VAvg            float32            `json:"v_avg"`
	VMedian         float32            `json:"v_median"`
	VMin            float32            `json:"v_min"`
	VMax            float32            `json:"v_max"`
	LwAvg           float32            `json:"lw_avg"`
	LwMedian        float32            `json:"lw_median"`
	LwMin           float32            `json:"lw_min"`
	LwMax           float32            `json:"lw_max"`
	BrtAvg          float32            `json:"brt_avg"`
	BrtMedian       float32            `json:"brt_median"`
	BrtMin          float32            `json:"brt_min"`
	BrtMax          float32            `json:"brt_max"`
	SolidAvg        float32            `json:"solid_avg"`
	SolidMedian     float32            `json:"solid_median"`
	SolidMin        float32            `json:"solid_min"`
	SolidMax        float32            `json:"solid_max"`
	SqSqcrlAvg      float32            `json:"sq_sqcrl_avg"`
	SqSqcrlMedian   float32            `json:"sq_sqcrl_median"`
	SqSqcrlMin      float32            `json:"sq_sqcrl_min"`
	SqSqcrlMax      float32            `json:"sq_sqcrl_max"`
	ExcludedObjects []byte             `json:"excluded_objects"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
