// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package database

import (
	"context"
)

const checkIsAuthorized = `-- name: CheckIsAuthorized :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            weed_notes
        WHERE
            id = $1
            AND created_by = $2
    )
`

type CheckIsAuthorizedParams struct {
	ID        int32 `json:"id"`
	CreatedBy int32 `json:"created_by"`
}

func (q *Queries) CheckIsAuthorized(ctx context.Context, arg CheckIsAuthorizedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIsAuthorized, arg.ID, arg.CreatedBy)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createWeedNote = `-- name: CreateWeedNote :one
INSERT INTO
    weed_notes (weed_id, note, created_by)
VALUES
    (
        $1,
        $2,
        $3
    ) RETURNING id, weed_id, note, created_by, created_at, updated_at
`

type CreateWeedNoteParams struct {
	WeedID    int32  `json:"weed_id"`
	Note      string `json:"note"`
	CreatedBy int32  `json:"created_by"`
}

func (q *Queries) CreateWeedNote(ctx context.Context, arg CreateWeedNoteParams) (WeedNote, error) {
	row := q.db.QueryRow(ctx, createWeedNote, arg.WeedID, arg.Note, arg.CreatedBy)
	var i WeedNote
	err := row.Scan(
		&i.ID,
		&i.WeedID,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWeedNote = `-- name: DeleteWeedNote :exec
DELETE FROM
    weed_notes
WHERE
    id = $1
`

func (q *Queries) DeleteWeedNote(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWeedNote, id)
	return err
}

const editWeedNote = `-- name: EditWeedNote :one
UPDATE
    weed_notes
SET
    note = $1
WHERE
    id = $2 RETURNING id, weed_id, note, created_by, created_at, updated_at
`

type EditWeedNoteParams struct {
	Note string `json:"note"`
	ID   int32  `json:"id"`
}

func (q *Queries) EditWeedNote(ctx context.Context, arg EditWeedNoteParams) (WeedNote, error) {
	row := q.db.QueryRow(ctx, editWeedNote, arg.Note, arg.ID)
	var i WeedNote
	err := row.Scan(
		&i.ID,
		&i.WeedID,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeedNotes = `-- name: GetWeedNotes :many
SELECT
    id, weed_id, note, created_by, created_at, updated_at
FROM
    weed_notes
WHERE
    weed_id = $1
`

func (q *Queries) GetWeedNotes(ctx context.Context, weedID int32) ([]WeedNote, error) {
	rows, err := q.db.Query(ctx, getWeedNotes, weedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeedNote{}
	for rows.Next() {
		var i WeedNote
		if err := rows.Scan(
			&i.ID,
			&i.WeedID,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
