// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proposals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPendingWeedImage = `-- name: AddPendingWeedImage :one
INSERT INTO
    pending_weed_images (pending_weed_id, image_key, is_primary)
VALUES
    (
        $1,
        $2,
        $3
    ) RETURNING id, pending_weed_id, image_key, is_primary, created_at
`

type AddPendingWeedImageParams struct {
	PendingWeedID int32  `json:"pending_weed_id"`
	ImageKey      string `json:"image_key"`
	IsPrimary     bool   `json:"is_primary"`
}

func (q *Queries) AddPendingWeedImage(ctx context.Context, arg AddPendingWeedImageParams) (PendingWeedImage, error) {
	row := q.db.QueryRow(ctx, addPendingWeedImage, arg.PendingWeedID, arg.ImageKey, arg.IsPrimary)
	var i PendingWeedImage
	err := row.Scan(
		&i.ID,
		&i.PendingWeedID,
		&i.ImageKey,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const bulkInsertPendingWeedAnalyses = `-- name: BulkInsertPendingWeedAnalyses :exec
INSERT INTO
    pending_weed_analyses (pending_weed_id, analysis_id)
SELECT
    $1::int,
    unnest(CAST($2 AS text[]))
`

type BulkInsertPendingWeedAnalysesParams struct {
	PendingWeedID int32    `json:"pending_weed_id"`
	AnalysisIds   []string `json:"analysis_ids"`
}

func (q *Queries) BulkInsertPendingWeedAnalyses(ctx context.Context, arg BulkInsertPendingWeedAnalysesParams) error {
	_, err := q.db.Exec(ctx, bulkInsertPendingWeedAnalyses, arg.PendingWeedID, arg.AnalysisIds)
	return err
}

const bulkInsertPendingWeedImages = `-- name: BulkInsertPendingWeedImages :exec
INSERT INTO
    pending_weed_images (pending_weed_id, image_key, is_primary)
SELECT
    $1::int,
    keys.arr [idx.i],
    flags.arr [idx.i]
FROM
    generate_subscripts(CAST($2 AS text[]), 1) AS idx(i)
    CROSS JOIN (
        SELECT
            CAST($2 AS text[]) AS arr
    ) AS keys
    CROSS JOIN (
        SELECT
            CAST($3 AS bool[]) AS arr
    ) AS flags
`

type BulkInsertPendingWeedImagesParams struct {
	PendingWeedID  int32    `json:"pending_weed_id"`
	ImageKeys      []string `json:"image_keys"`
	IsPrimaryFlags []bool   `json:"is_primary_flags"`
}

func (q *Queries) BulkInsertPendingWeedImages(ctx context.Context, arg BulkInsertPendingWeedImagesParams) error {
	_, err := q.db.Exec(ctx, bulkInsertPendingWeedImages, arg.PendingWeedID, arg.ImageKeys, arg.IsPrimaryFlags)
	return err
}

const countCatalogProposals = `-- name: CountCatalogProposals :one
SELECT count(*)
FROM catalog_proposals
WHERE (
    $1::text IS NULL
    OR status = $1
)
AND (
    $2::bigint IS NULL
    OR request_by = $2
)
AND (
    $3::integer IS NULL
    OR reviewed_by = $3
)
`

type CountCatalogProposalsParams struct {
	Status     *string `json:"status"`
	RequestBy  *int64  `json:"request_by"`
	ReviewedBy *int32  `json:"reviewed_by"`
}

func (q *Queries) CountCatalogProposals(ctx context.Context, arg CountCatalogProposalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogProposals, arg.Status, arg.RequestBy, arg.ReviewedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCatalogProposal = `-- name: CreateCatalogProposal :one
INSERT INTO catalog_proposals (
    status,
    request_by,
    target_weed_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, status, request_by, target_weed_id, reviewed_by, reviewed_at, review_notes, submitted_at, applied_by, applied_at, applied_weed_id, created_at, updated_at
`

type CreateCatalogProposalParams struct {
	Status       string `json:"status"`
	RequestBy    int64  `json:"request_by"`
	TargetWeedID *int32 `json:"target_weed_id"`
}

func (q *Queries) CreateCatalogProposal(ctx context.Context, arg CreateCatalogProposalParams) (CatalogProposal, error) {
	row := q.db.QueryRow(ctx, createCatalogProposal, arg.Status, arg.RequestBy, arg.TargetWeedID)
	var i CatalogProposal
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestBy,
		&i.TargetWeedID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.SubmittedAt,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.AppliedWeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPendingWeed = `-- name: CreatePendingWeed :one

INSERT INTO
    pending_weeds (
        name,
        latin_name,
        description,
        length,
        width,
        main_group,
        main_subgroup,
        subgroup,
        is_quarantine,
        harmfulness,
        proposal_id
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11
    ) RETURNING id, name, latin_name, description, length, width, main_group, main_subgroup, subgroup, is_quarantine, harmfulness, proposal_id, created_at, updated_at
`

type CreatePendingWeedParams struct {
	Name         string   `json:"name"`
	LatinName    *string  `json:"latin_name"`
	Description  *string  `json:"description"`
	Length       *float32 `json:"length"`
	Width        *float32 `json:"width"`
	MainGroup    *string  `json:"main_group"`
	MainSubgroup *string  `json:"main_subgroup"`
	Subgroup     *string  `json:"subgroup"`
	IsQuarantine bool     `json:"is_quarantine"`
	Harmfulness  *string  `json:"harmfulness"`
	ProposalID   int32    `json:"proposal_id"`
}

// =====================================================
// Pending Weeds (Proposal Drafts)
// =====================================================
func (q *Queries) CreatePendingWeed(ctx context.Context, arg CreatePendingWeedParams) (PendingWeed, error) {
	row := q.db.QueryRow(ctx, createPendingWeed,
		arg.Name,
		arg.LatinName,
		arg.Description,
		arg.Length,
		arg.Width,
		arg.MainGroup,
		arg.MainSubgroup,
		arg.Subgroup,
		arg.IsQuarantine,
		arg.Harmfulness,
		arg.ProposalID,
	)
	var i PendingWeed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LatinName,
		&i.Description,
		&i.Length,
		&i.Width,
		&i.MainGroup,
		&i.MainSubgroup,
		&i.Subgroup,
		&i.IsQuarantine,
		&i.Harmfulness,
		&i.ProposalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPendingWeedStats = `-- name: CreatePendingWeedStats :one
INSERT INTO
    pending_weed_stats (
        pending_weed_id,
        w_avg,
        w_median,
        w_min,
        w_max,
        l_avg,
        l_median,
        l_min,
        l_max,
        sq_avg,
        sq_median,
        sq_min,
        sq_max,
        r_avg,
        r_median,
        r_min,
        r_max,
        g_avg,
        g_median,
        g_min,
        g_max,
        b_avg,
        b_median,
        b_min,
        b_max,
        h_avg,
        h_median,
        h_min,
        h_max,
        s_avg,
        s_median,
        s_min,
        s_max,
        v_avg,
        v_median,
        v_min,
        v_max,
        lw_avg,
        lw_median,
        lw_min,
        lw_max,
        brt_avg,
        brt_median,
        brt_min,
        brt_max,
        solid_avg,
        solid_median,
        solid_min,
        solid_max,
        sq_sqcrl_avg,
        sq_sqcrl_median,
        sq_sqcrl_min,
        sq_sqcrl_max,
        excluded_objects
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35,
        $36,
        $37,
        $38,
        $39,
        $40,
        $41,
        $42,
        $43,
        $44,
        $45,
        $46,
        $47,
        $48,
        $49,
        $50,
        $51,
        $52,
        $53,
        $54
    ) RETURNING id, pending_weed_id, w_avg, w_median, w_min, w_max, l_avg, l_median, l_min, l_max, sq_avg, sq_median, sq_min, sq_max, r_avg, r_median, r_min, r_max, g_avg, g_median, g_min, g_max, b_avg, b_median, b_min, b_max, h_avg, h_median, h_min, h_max, s_avg, s_median, s_min, s_max, v_avg, v_median, v_min, v_max, lw_avg, lw_median, lw_min, lw_max, brt_avg, brt_median, brt_min, brt_max, solid_avg, solid_median, solid_min, solid_max, sq_sqcrl_avg, sq_sqcrl_median, sq_sqcrl_min, sq_sqcrl_max, excluded_objects, created_at, updated_at
`

type CreatePendingWeedStatsParams struct {
	PendingWeedID   int32   `json:"pending_weed_id"`
	WAvg            float32 `json:"w_avg"`
	WMedian         float32 `json:"w_median"`
	WMin            float32 `json:"w_min"`
	WMax            float32 `json:"w_max"`
	LAvg            float32 `json:"l_avg"`
	LMedian         float32 `json:"l_median"`
	LMin            float32 `json:"l_min"`
	LMax            float32 `json:"l_max"`
	SqAvg           float32 `json:"sq_avg"`
	SqMedian        float32 `json:"sq_median"`
	SqMin           float32 `json:"sq_min"`
	SqMax           float32 `json:"sq_max"`
	RAvg            float32 `json:"r_avg"`
	RMedian         float32 `json:"r_median"`
	RMin            float32 `json:"r_min"`
	RMax            float32 `json:"r_max"`
	GAvg            float32 `json:"g_avg"`
	GMedian         float32 `json:"g_median"`
	GMin            float32 `json:"g_min"`
	GMax            float32 `json:"g_max"`
	BAvg            float32 `json:"b_avg"`
	BMedian         float32 `json:"b_median"`
	BMin            float32 `json:"b_min"`
	BMax            float32 `json:"b_max"`
	HAvg            float32 `json:"h_avg"`
	HMedian         float32 `json:"h_median"`
	HMin            float32 `json:"h_min"`
	HMax            float32 `json:"h_max"`
	SAvg            float32 `json:"s_avg"`
	SMedian         float32 `json:"s_median"`
	SMin            float32 `json:"s_min"`
	SMax            float32 `json:"s_max"`
	VAvg            float32 `json:"v_avg"`
	VMedian         float32 `json:"v_median"`
	VMin            float32 `json:"v_min"`
	VMax            float32 `json:"v_max"`
	LwAvg           float32 `json:"lw_avg"`
	LwMedian        float32 `json:"lw_median"`
	LwMin           float32 `json:"lw_min"`
	LwMax           float32 `json:"lw_max"`
	BrtAvg          float32 `json:"brt_avg"`
	BrtMedian       float32 `json:"brt_median"`
	BrtMin          float32 `json:"brt_min"`
	BrtMax          float32 `json:"brt_max"`
	SolidAvg        float32 `json:"solid_avg"`
	SolidMedian     float32 `json:"solid_median"`
	SolidMin        float32 `json:"solid_min"`
	SolidMax        float32 `json:"solid_max"`
	SqSqcrlAvg      float32 `json:"sq_sqcrl_avg"`
	SqSqcrlMedian   float32 `json:"sq_sqcrl_median"`
	SqSqcrlMin      float32 `json:"sq_sqcrl_min"`
	SqSqcrlMax      float32 `json:"sq_sqcrl_max"`
	ExcludedObjects []byte  `json:"excluded_objects"`
}

func (q *Queries) CreatePendingWeedStats(ctx context.Context, arg CreatePendingWeedStatsParams) (PendingWeedStat, error) {
	row := q.db.QueryRow(ctx, createPendingWeedStats,
		arg.PendingWeedID,
		arg.WAvg,
		arg.WMedian,
		arg.WMin,
		arg.WMax,
		arg.LAvg,
		arg.LMedian,
		arg.LMin,
		arg.LMax,
		arg.SqAvg,
		arg.SqMedian,
		arg.SqMin,
		arg.SqMax,
		arg.RAvg,
		arg.RMedian,
		arg.RMin,
		arg.RMax,
		arg.GAvg,
		arg.GMedian,
		arg.GMin,
		arg.GMax,
		arg.BAvg,
		arg.BMedian,
		arg.BMin,
		arg.BMax,
		arg.HAvg,
		arg.HMedian,
		arg.HMin,
		arg.HMax,
		arg.SAvg,
		arg.SMedian,
		arg.SMin,
		arg.SMax,
		arg.VAvg,
		arg.VMedian,
		arg.VMin,
		arg.VMax,
		arg.LwAvg,
		arg.LwMedian,
		arg.LwMin,
		arg.LwMax,
		arg.BrtAvg,
		arg.BrtMedian,
		arg.BrtMin,
		arg.BrtMax,
		arg.SolidAvg,
		arg.SolidMedian,
		arg.SolidMin,
		arg.SolidMax,
		arg.SqSqcrlAvg,
		arg.SqSqcrlMedian,
		arg.SqSqcrlMin,
		arg.SqSqcrlMax,
		arg.ExcludedObjects,
	)
	var i PendingWeedStat
	err := row.Scan(
		&i.ID,
		&i.PendingWeedID,
		&i.WAvg,
		&i.WMedian,
		&i.WMin,
		&i.WMax,
		&i.LAvg,
		&i.LMedian,
		&i.LMin,
		&i.LMax,
		&i.SqAvg,
		&i.SqMedian,
		&i.SqMin,
		&i.SqMax,
		&i.RAvg,
		&i.RMedian,
		&i.RMin,
		&i.RMax,
		&i.GAvg,
		&i.GMedian,
		&i.GMin,
		&i.GMax,
		&i.BAvg,
		&i.BMedian,
		&i.BMin,
		&i.BMax,
		&i.HAvg,
		&i.HMedian,
		&i.HMin,
		&i.HMax,
		&i.SAvg,
		&i.SMedian,
		&i.SMin,
		&i.SMax,
		&i.VAvg,
		&i.VMedian,
		&i.VMin,
		&i.VMax,
		&i.LwAvg,
		&i.LwMedian,
		&i.LwMin,
		&i.LwMax,
		&i.BrtAvg,
		&i.BrtMedian,
		&i.BrtMin,
		&i.BrtMax,
		&i.SolidAvg,
		&i.SolidMedian,
		&i.SolidMin,
		&i.SolidMax,
		&i.SqSqcrlAvg,
		&i.SqSqcrlMedian,
		&i.SqSqcrlMin,
		&i.SqSqcrlMax,
		&i.ExcludedObjects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePendingWeed = `-- name: DeletePendingWeed :exec
DELETE FROM
    pending_weeds
WHERE
    id = $1
`

func (q *Queries) DeletePendingWeed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePendingWeed, id)
	return err
}

const deletePendingWeedAnalysesByPendingWeedID = `-- name: DeletePendingWeedAnalysesByPendingWeedID :exec
DELETE FROM pending_weed_analyses
WHERE pending_weed_id = $1
`

func (q *Queries) DeletePendingWeedAnalysesByPendingWeedID(ctx context.Context, pendingWeedID int32) error {
	_, err := q.db.Exec(ctx, deletePendingWeedAnalysesByPendingWeedID, pendingWeedID)
	return err
}

const deletePendingWeedImage = `-- name: DeletePendingWeedImage :exec
DELETE FROM
    pending_weed_images
WHERE
    id = $1
`

func (q *Queries) DeletePendingWeedImage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePendingWeedImage, id)
	return err
}

const getCatalogProposalByID = `-- name: GetCatalogProposalByID :one
SELECT id, status, request_by, target_weed_id, reviewed_by, reviewed_at, review_notes, submitted_at, applied_by, applied_at, applied_weed_id, created_at, updated_at
FROM catalog_proposals
WHERE id = $1
`

func (q *Queries) GetCatalogProposalByID(ctx context.Context, id int32) (CatalogProposal, error) {
	row := q.db.QueryRow(ctx, getCatalogProposalByID, id)
	var i CatalogProposal
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestBy,
		&i.TargetWeedID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.SubmittedAt,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.AppliedWeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogProposalByIDForUpdate = `-- name: GetCatalogProposalByIDForUpdate :one
SELECT id, status, request_by, target_weed_id, reviewed_by, reviewed_at, review_notes, submitted_at, applied_by, applied_at, applied_weed_id, created_at, updated_at
FROM catalog_proposals
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCatalogProposalByIDForUpdate(ctx context.Context, id int32) (CatalogProposal, error) {
	row := q.db.QueryRow(ctx, getCatalogProposalByIDForUpdate, id)
	var i CatalogProposal
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestBy,
		&i.TargetWeedID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.SubmittedAt,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.AppliedWeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingWeedAnalyses = `-- name: GetPendingWeedAnalyses :many

SELECT
    id, pending_weed_id, analysis_id
FROM
    pending_weed_analyses
WHERE
    pending_weed_id = $1
`

// =====================================================
// Pending Weed Analyses
// =====================================================
func (q *Queries) GetPendingWeedAnalyses(ctx context.Context, pendingWeedID int32) ([]PendingWeedAnalysis, error) {
	rows, err := q.db.Query(ctx, getPendingWeedAnalyses, pendingWeedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingWeedAnalysis{}
	for rows.Next() {
		var i PendingWeedAnalysis
		if err := rows.Scan(&i.ID, &i.PendingWeedID, &i.AnalysisID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWeedByProposalID = `-- name: GetPendingWeedByProposalID :one
SELECT
    id, name, latin_name, description, length, width, main_group, main_subgroup, subgroup, is_quarantine, harmfulness, proposal_id, created_at, updated_at
FROM
    pending_weeds
WHERE
    proposal_id = $1
`

func (q *Queries) GetPendingWeedByProposalID(ctx context.Context, proposalID int32) (PendingWeed, error) {
	row := q.db.QueryRow(ctx, getPendingWeedByProposalID, proposalID)
	var i PendingWeed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LatinName,
		&i.Description,
		&i.Length,
		&i.Width,
		&i.MainGroup,
		&i.MainSubgroup,
		&i.Subgroup,
		&i.IsQuarantine,
		&i.Harmfulness,
		&i.ProposalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingWeedImageByID = `-- name: GetPendingWeedImageByID :one
SELECT
    id, pending_weed_id, image_key, is_primary, created_at
FROM
    pending_weed_images
WHERE
    id = $1
`

func (q *Queries) GetPendingWeedImageByID(ctx context.Context, id int32) (PendingWeedImage, error) {
	row := q.db.QueryRow(ctx, getPendingWeedImageByID, id)
	var i PendingWeedImage
	err := row.Scan(
		&i.ID,
		&i.PendingWeedID,
		&i.ImageKey,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingWeedImages = `-- name: GetPendingWeedImages :many

SELECT
    id, pending_weed_id, image_key, is_primary, created_at
FROM
    pending_weed_images
WHERE
    pending_weed_id = $1
ORDER BY
    created_at
`

// =====================================================
// Pending Weed Images
// =====================================================
func (q *Queries) GetPendingWeedImages(ctx context.Context, pendingWeedID int32) ([]PendingWeedImage, error) {
	rows, err := q.db.Query(ctx, getPendingWeedImages, pendingWeedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingWeedImage{}
	for rows.Next() {
		var i PendingWeedImage
		if err := rows.Scan(
			&i.ID,
			&i.PendingWeedID,
			&i.ImageKey,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWeedStatsByPendingWeedID = `-- name: GetPendingWeedStatsByPendingWeedID :one

SELECT
    id, pending_weed_id, w_avg, w_median, w_min, w_max, l_avg, l_median, l_min, l_max, sq_avg, sq_median, sq_min, sq_max, r_avg, r_median, r_min, r_max, g_avg, g_median, g_min, g_max, b_avg, b_median, b_min, b_max, h_avg, h_median, h_min, h_max, s_avg, s_median, s_min, s_max, v_avg, v_median, v_min, v_max, lw_avg, lw_median, lw_min, lw_max, brt_avg, brt_median, brt_min, brt_max, solid_avg, solid_median, solid_min, solid_max, sq_sqcrl_avg, sq_sqcrl_median, sq_sqcrl_min, sq_sqcrl_max, excluded_objects, created_at, updated_at
FROM
    pending_weed_stats
WHERE
    pending_weed_id = $1
`

// =====================================================
// Pending Weed Stats
// =====================================================
func (q *Queries) GetPendingWeedStatsByPendingWeedID(ctx context.Context, pendingWeedID int32) (PendingWeedStat, error) {
	row := q.db.QueryRow(ctx, getPendingWeedStatsByPendingWeedID, pendingWeedID)
	var i PendingWeedStat
	err := row.Scan(
		&i.ID,
		&i.PendingWeedID,
		&i.WAvg,
		&i.WMedian,
		&i.WMin,
		&i.WMax,
		&i.LAvg,
		&i.LMedian,
		&i.LMin,
		&i.LMax,
		&i.SqAvg,
		&i.SqMedian,
		&i.SqMin,
		&i.SqMax,
		&i.RAvg,
		&i.RMedian,
		&i.RMin,
		&i.RMax,
		&i.GAvg,
		&i.GMedian,
		&i.GMin,
		&i.GMax,
		&i.BAvg,
		&i.BMedian,
		&i.BMin,
		&i.BMax,
		&i.HAvg,
		&i.HMedian,
		&i.HMin,
		&i.HMax,
		&i.SAvg,
		&i.SMedian,
		&i.SMin,
		&i.SMax,
		&i.VAvg,
		&i.VMedian,
		&i.VMin,
		&i.VMax,
		&i.LwAvg,
		&i.LwMedian,
		&i.LwMin,
		&i.LwMax,
		&i.BrtAvg,
		&i.BrtMedian,
		&i.BrtMin,
		&i.BrtMax,
		&i.SolidAvg,
		&i.SolidMedian,
		&i.SolidMin,
		&i.SolidMax,
		&i.SqSqcrlAvg,
		&i.SqSqcrlMedian,
		&i.SqSqcrlMin,
		&i.SqSqcrlMax,
		&i.ExcludedObjects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCatalogProposalsWithPendingWeed = `-- name: ListCatalogProposalsWithPendingWeed :many
SELECT
    cr.id, cr.status, cr.request_by, cr.target_weed_id, cr.reviewed_by, cr.reviewed_at, cr.review_notes, cr.submitted_at, cr.applied_by, cr.applied_at, cr.applied_weed_id, cr.created_at, cr.updated_at,
    COALESCE(pw.name, '') AS pending_name
FROM
    catalog_proposals cr
    LEFT JOIN pending_weeds pw ON pw.proposal_id = cr.id
WHERE (
    $1::text IS NULL
    OR cr.status = $1
)
AND (
    $2::bigint IS NULL
    OR cr.request_by = $2
)
AND (
    $3::integer IS NULL
    OR cr.reviewed_by = $3
)
ORDER BY
    CASE 
        WHEN $4::text = 'asc' THEN cr.created_at
        ELSE NULL
    END ASC,
    CASE 
        WHEN $4::text = 'desc' OR $4::text IS NULL THEN cr.created_at
        ELSE NULL
    END DESC
LIMIT $6
OFFSET $5
`

type ListCatalogProposalsWithPendingWeedParams struct {
	Status     *string `json:"status"`
	RequestBy  *int64  `json:"request_by"`
	ReviewedBy *int32  `json:"reviewed_by"`
	SortOrder  *string `json:"sort_order"`
	Offset     int32   `json:"offset"`
	Limit      int32   `json:"limit"`
}

type ListCatalogProposalsWithPendingWeedRow struct {
	ID            int32              `json:"id"`
	Status        string             `json:"status"`
	RequestBy     int64              `json:"request_by"`
	TargetWeedID  *int32             `json:"target_weed_id"`
	ReviewedBy    *int32             `json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamp   `json:"reviewed_at"`
	ReviewNotes   *string            `json:"review_notes"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	AppliedBy     *int32             `json:"applied_by"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
	AppliedWeedID *int32             `json:"applied_weed_id"`
	CreatedAt     pgtype.Timestamp   `json:"created_at"`
	UpdatedAt     pgtype.Timestamp   `json:"updated_at"`
	PendingName   string             `json:"pending_name"`
}

func (q *Queries) ListCatalogProposalsWithPendingWeed(ctx context.Context, arg ListCatalogProposalsWithPendingWeedParams) ([]ListCatalogProposalsWithPendingWeedRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProposalsWithPendingWeed,
		arg.Status,
		arg.RequestBy,
		arg.ReviewedBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProposalsWithPendingWeedRow{}
	for rows.Next() {
		var i ListCatalogProposalsWithPendingWeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.RequestBy,
			&i.TargetWeedID,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNotes,
			&i.SubmittedAt,
			&i.AppliedBy,
			&i.AppliedAt,
			&i.AppliedWeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PendingName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCatalogProposalApplied = `-- name: MarkCatalogProposalApplied :one
UPDATE catalog_proposals
SET
    status = 'applied',
    reviewed_by = $1,
    review_notes = $2,
    applied_by = $3,
    applied_weed_id = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, status, request_by, target_weed_id, reviewed_by, reviewed_at, review_notes, submitted_at, applied_by, applied_at, applied_weed_id, created_at, updated_at
`

type MarkCatalogProposalAppliedParams struct {
	ReviewedBy    *int32  `json:"reviewed_by"`
	ReviewNotes   *string `json:"review_notes"`
	AppliedBy     *int32  `json:"applied_by"`
	AppliedWeedID *int32  `json:"applied_weed_id"`
	ID            int32   `json:"id"`
}

func (q *Queries) MarkCatalogProposalApplied(ctx context.Context, arg MarkCatalogProposalAppliedParams) (CatalogProposal, error) {
	row := q.db.QueryRow(ctx, markCatalogProposalApplied,
		arg.ReviewedBy,
		arg.ReviewNotes,
		arg.AppliedBy,
		arg.AppliedWeedID,
		arg.ID,
	)
	var i CatalogProposal
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestBy,
		&i.TargetWeedID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.SubmittedAt,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.AppliedWeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCatalogProposal = `-- name: UpdateCatalogProposal :one
UPDATE catalog_proposals
SET 
    status = $1,
    reviewed_by = $2,
    review_notes = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, status, request_by, target_weed_id, reviewed_by, reviewed_at, review_notes, submitted_at, applied_by, applied_at, applied_weed_id, created_at, updated_at
`

type UpdateCatalogProposalParams struct {
	Status      string  `json:"status"`
	ReviewedBy  *int32  `json:"reviewed_by"`
	ReviewNotes *string `json:"review_notes"`
	ID          int32   `json:"id"`
}

func (q *Queries) UpdateCatalogProposal(ctx context.Context, arg UpdateCatalogProposalParams) (CatalogProposal, error) {
	row := q.db.QueryRow(ctx, updateCatalogProposal,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewNotes,
		arg.ID,
	)
	var i CatalogProposal
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestBy,
		&i.TargetWeedID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.SubmittedAt,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.AppliedWeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCatalogProposalStatus = `-- name: UpdateCatalogProposalStatus :one
UPDATE catalog_proposals
SET 
    status = $1,
    reviewed_by = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, status, request_by, target_weed_id, reviewed_by, reviewed_at, review_notes, submitted_at, applied_by, applied_at, applied_weed_id, created_at, updated_at
`

type UpdateCatalogProposalStatusParams struct {
	Status     string `json:"status"`
	ReviewedBy *int32 `json:"reviewed_by"`
	ID         int32  `json:"id"`
}

func (q *Queries) UpdateCatalogProposalStatus(ctx context.Context, arg UpdateCatalogProposalStatusParams) (CatalogProposal, error) {
	row := q.db.QueryRow(ctx, updateCatalogProposalStatus, arg.Status, arg.ReviewedBy, arg.ID)
	var i CatalogProposal
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestBy,
		&i.TargetWeedID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.SubmittedAt,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.AppliedWeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingWeed = `-- name: UpdatePendingWeed :one
UPDATE
    pending_weeds
SET
    name = $1,
    latin_name = $2,
    description = $3,
    length = $4,
    width = $5,
    main_group = $6,
    main_subgroup = $7,
    subgroup = $8,
    is_quarantine = $9,
    harmfulness = $10
WHERE
    id = $11 RETURNING id, name, latin_name, description, length, width, main_group, main_subgroup, subgroup, is_quarantine, harmfulness, proposal_id, created_at, updated_at
`

type UpdatePendingWeedParams struct {
	Name         string   `json:"name"`
	LatinName    *string  `json:"latin_name"`
	Description  *string  `json:"description"`
	Length       *float32 `json:"length"`
	Width        *float32 `json:"width"`
	MainGroup    *string  `json:"main_group"`
	MainSubgroup *string  `json:"main_subgroup"`
	Subgroup     *string  `json:"subgroup"`
	IsQuarantine bool     `json:"is_quarantine"`
	Harmfulness  *string  `json:"harmfulness"`
	ID           int32    `json:"id"`
}

func (q *Queries) UpdatePendingWeed(ctx context.Context, arg UpdatePendingWeedParams) (PendingWeed, error) {
	row := q.db.QueryRow(ctx, updatePendingWeed,
		arg.Name,
		arg.LatinName,
		arg.Description,
		arg.Length,
		arg.Width,
		arg.MainGroup,
		arg.MainSubgroup,
		arg.Subgroup,
		arg.IsQuarantine,
		arg.Harmfulness,
		arg.ID,
	)
	var i PendingWeed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LatinName,
		&i.Description,
		&i.Length,
		&i.Width,
		&i.MainGroup,
		&i.MainSubgroup,
		&i.Subgroup,
		&i.IsQuarantine,
		&i.Harmfulness,
		&i.ProposalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingWeedStats = `-- name: UpdatePendingWeedStats :one
UPDATE
    pending_weed_stats
SET
    w_avg = $1,
    w_median = $2,
    w_min = $3,
    w_max = $4,
    l_avg = $5,
    l_median = $6,
    l_min = $7,
    l_max = $8,
    sq_avg = $9,
    sq_median = $10,
    sq_min = $11,
    sq_max = $12,
    r_avg = $13,
    r_median = $14,
    r_min = $15,
    r_max = $16,
    g_avg = $17,
    g_median = $18,
    g_min = $19,
    g_max = $20,
    b_avg = $21,
    b_median = $22,
    b_min = $23,
    b_max = $24,
    h_avg = $25,
    h_median = $26,
    h_min = $27,
    h_max = $28,
    s_avg = $29,
    s_median = $30,
    s_min = $31,
    s_max = $32,
    v_avg = $33,
    v_median = $34,
    v_min = $35,
    v_max = $36,
    lw_avg = $37,
    lw_median = $38,
    lw_min = $39,
    lw_max = $40,
    brt_avg = $41,
    brt_median = $42,
    brt_min = $43,
    brt_max = $44,
    solid_avg = $45,
    solid_median = $46,
    solid_min = $47,
    solid_max = $48,
    sq_sqcrl_avg = $49,
    sq_sqcrl_median = $50,
    sq_sqcrl_min = $51,
    sq_sqcrl_max = $52,
    excluded_objects = $53
WHERE
    pending_weed_id = $54 RETURNING id, pending_weed_id, w_avg, w_median, w_min, w_max, l_avg, l_median, l_min, l_max, sq_avg, sq_median, sq_min, sq_max, r_avg, r_median, r_min, r_max, g_avg, g_median, g_min, g_max, b_avg, b_median, b_min, b_max, h_avg, h_median, h_min, h_max, s_avg, s_median, s_min, s_max, v_avg, v_median, v_min, v_max, lw_avg, lw_median, lw_min, lw_max, brt_avg, brt_median, brt_min, brt_max, solid_avg, solid_median, solid_min, solid_max, sq_sqcrl_avg, sq_sqcrl_median, sq_sqcrl_min, sq_sqcrl_max, excluded_objects, created_at, updated_at
`

type UpdatePendingWeedStatsParams struct {
	WAvg            float32 `json:"w_avg"`
	WMedian         float32 `json:"w_median"`
	WMin            float32 `json:"w_min"`
	WMax            float32 `json:"w_max"`
	LAvg            float32 `json:"l_avg"`
	LMedian         float32 `json:"l_median"`
	LMin            float32 `json:"l_min"`
	LMax            float32 `json:"l_max"`
	SqAvg           float32 `json:"sq_avg"`
	SqMedian        float32 `json:"sq_median"`
	SqMin           float32 `json:"sq_min"`
	SqMax           float32 `json:"sq_max"`
	RAvg            float32 `json:"r_avg"`
	RMedian         float32 `json:"r_median"`
	RMin            float32 `json:"r_min"`
	RMax            float32 `json:"r_max"`
	GAvg            float32 `json:"g_avg"`
	GMedian         float32 `json:"g_median"`
	GMin            float32 `json:"g_min"`
	GMax            float32 `json:"g_max"`
	BAvg            float32 `json:"b_avg"`
	BMedian         float32 `json:"b_median"`
	BMin            float32 `json:"b_min"`
	BMax            float32 `json:"b_max"`
	HAvg            float32 `json:"h_avg"`
	HMedian         float32 `json:"h_median"`
	HMin            float32 `json:"h_min"`
	HMax            float32 `json:"h_max"`
	SAvg            float32 `json:"s_avg"`
	SMedian         float32 `json:"s_median"`
	SMin            float32 `json:"s_min"`
	SMax            float32 `json:"s_max"`
	VAvg            float32 `json:"v_avg"`
	VMedian         float32 `json:"v_median"`
	VMin            float32 `json:"v_min"`
	VMax            float32 `json:"v_max"`
	LwAvg           float32 `json:"lw_avg"`
	LwMedian        float32 `json:"lw_median"`
	LwMin           float32 `json:"lw_min"`
	LwMax           float32 `json:"lw_max"`
	BrtAvg          float32 `json:"brt_avg"`
	BrtMedian       float32 `json:"brt_median"`
	BrtMin          float32 `json:"brt_min"`
	BrtMax          float32 `json:"brt_max"`
	SolidAvg        float32 `json:"solid_avg"`
	SolidMedian     float32 `json:"solid_median"`
	SolidMin        float32 `json:"solid_min"`
	SolidMax        float32 `json:"solid_max"`
	SqSqcrlAvg      float32 `json:"sq_sqcrl_avg"`
	SqSqcrlMedian   float32 `json:"sq_sqcrl_median"`
	SqSqcrlMin      float32 `json:"sq_sqcrl_min"`
	SqSqcrlMax      float32 `json:"sq_sqcrl_max"`
	ExcludedObjects []byte  `json:"excluded_objects"`
	PendingWeedID   int32   `json:"pending_weed_id"`
}

func (q *Queries) UpdatePendingWeedStats(ctx context.Context, arg UpdatePendingWeedStatsParams) (PendingWeedStat, error) {
	row := q.db.QueryRow(ctx, updatePendingWeedStats,
		arg.WAvg,
		arg.WMedian,
		arg.WMin,
		arg.WMax,
		arg.LAvg,
		arg.LMedian,
		arg.LMin,
		arg.LMax,
		arg.SqAvg,
		arg.SqMedian,
		arg.SqMin,
		arg.SqMax,
		arg.RAvg,
		arg.RMedian,
		arg.RMin,
		arg.RMax,
		arg.GAvg,
		arg.GMedian,
		arg.GMin,
		arg.GMax,
		arg.BAvg,
		arg.BMedian,
		arg.BMin,
		arg.BMax,
		arg.HAvg,
		arg.HMedian,
		arg.HMin,
		arg.HMax,
		arg.SAvg,
		arg.SMedian,
		arg.SMin,
		arg.SMax,
		arg.VAvg,
		arg.VMedian,
		arg.VMin,
		arg.VMax,
		arg.LwAvg,
		arg.LwMedian,
		arg.LwMin,
		arg.LwMax,
		arg.BrtAvg,
		arg.BrtMedian,
		arg.BrtMin,
		arg.BrtMax,
		arg.SolidAvg,
		arg.SolidMedian,
		arg.SolidMin,
		arg.SolidMax,
		arg.SqSqcrlAvg,
		arg.SqSqcrlMedian,
		arg.SqSqcrlMin,
		arg.SqSqcrlMax,
		arg.ExcludedObjects,
		arg.PendingWeedID,
	)
	var i PendingWeedStat
	err := row.Scan(
		&i.ID,
		&i.PendingWeedID,
		&i.WAvg,
		&i.WMedian,
		&i.WMin,
		&i.WMax,
		&i.LAvg,
		&i.LMedian,
		&i.LMin,
		&i.LMax,
		&i.SqAvg,
		&i.SqMedian,
		&i.SqMin,
		&i.SqMax,
		&i.RAvg,
		&i.RMedian,
		&i.RMin,
		&i.RMax,
		&i.GAvg,
		&i.GMedian,
		&i.GMin,
		&i.GMax,
		&i.BAvg,
		&i.BMedian,
		&i.BMin,
		&i.BMax,
		&i.HAvg,
		&i.HMedian,
		&i.HMin,
		&i.HMax,
		&i.SAvg,
		&i.SMedian,
		&i.SMin,
		&i.SMax,
		&i.VAvg,
		&i.VMedian,
		&i.VMin,
		&i.VMax,
		&i.LwAvg,
		&i.LwMedian,
		&i.LwMin,
		&i.LwMax,
		&i.BrtAvg,
		&i.BrtMedian,
		&i.BrtMin,
		&i.BrtMax,
		&i.SolidAvg,
		&i.SolidMedian,
		&i.SolidMin,
		&i.SolidMax,
		&i.SqSqcrlAvg,
		&i.SqSqcrlMedian,
		&i.SqSqcrlMin,
		&i.SqSqcrlMax,
		&i.ExcludedObjects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
