// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AddPendingWeedImage(ctx context.Context, arg AddPendingWeedImageParams) (PendingWeedImage, error)
	AddWeedImage(ctx context.Context, arg AddWeedImageParams) (WeedImage, error)
	BulkInsertPendingWeedAnalyses(ctx context.Context, arg BulkInsertPendingWeedAnalysesParams) error
	BulkInsertPendingWeedImages(ctx context.Context, arg BulkInsertPendingWeedImagesParams) error
	BulkInsertWeedAnalyses(ctx context.Context, arg BulkInsertWeedAnalysesParams) error
	BulkInsertWeedImages(ctx context.Context, arg BulkInsertWeedImagesParams) error
	CheckIsAuthorized(ctx context.Context, arg CheckIsAuthorizedParams) (bool, error)
	ClearPrimaryImageForWeed(ctx context.Context, weedID int32) error
	CountCatalogProposals(ctx context.Context, arg CountCatalogProposalsParams) (int64, error)
	CountWeeds(ctx context.Context, arg CountWeedsParams) (int64, error)
	CreateCatalogProposal(ctx context.Context, arg CreateCatalogProposalParams) (CatalogProposal, error)
	// =====================================================
	// Pending Weeds (Proposal Drafts)
	// =====================================================
	CreatePendingWeed(ctx context.Context, arg CreatePendingWeedParams) (PendingWeed, error)
	CreatePendingWeedStats(ctx context.Context, arg CreatePendingWeedStatsParams) (PendingWeedStat, error)
	CreateWeed(ctx context.Context, arg CreateWeedParams) (Weed, error)
	CreateWeedNote(ctx context.Context, arg CreateWeedNoteParams) (WeedNote, error)
	CreateWeedStats(ctx context.Context, arg CreateWeedStatsParams) (WeedStat, error)
	DeleteAllWeedImages(ctx context.Context, weedID int32) error
	DeletePendingWeed(ctx context.Context, id int32) error
	DeletePendingWeedAnalysesByPendingWeedID(ctx context.Context, pendingWeedID int32) error
	DeletePendingWeedImage(ctx context.Context, id int32) error
	DeleteWeed(ctx context.Context, id int32) error
	DeleteWeedAnalysesByWeedID(ctx context.Context, weedID int32) error
	DeleteWeedImage(ctx context.Context, id int32) error
	DeleteWeedNote(ctx context.Context, id int32) error
	EditWeedNote(ctx context.Context, arg EditWeedNoteParams) (WeedNote, error)
	GetCatalogProposalByID(ctx context.Context, id int32) (CatalogProposal, error)
	GetCatalogProposalByIDForUpdate(ctx context.Context, id int32) (CatalogProposal, error)
	// =====================================================
	// Pending Weed Analyses
	// =====================================================
	GetPendingWeedAnalyses(ctx context.Context, pendingWeedID int32) ([]PendingWeedAnalysis, error)
	GetPendingWeedByProposalID(ctx context.Context, proposalID int32) (PendingWeed, error)
	GetPendingWeedImageByID(ctx context.Context, id int32) (PendingWeedImage, error)
	// =====================================================
	// Pending Weed Images
	// =====================================================
	GetPendingWeedImages(ctx context.Context, pendingWeedID int32) ([]PendingWeedImage, error)
	// =====================================================
	// Pending Weed Stats
	// =====================================================
	GetPendingWeedStatsByPendingWeedID(ctx context.Context, pendingWeedID int32) (PendingWeedStat, error)
	GetWeedAnalyses(ctx context.Context, weedID int32) ([]WeedAnalysis, error)
	GetWeedByID(ctx context.Context, id int32) (Weed, error)
	GetWeedImageByID(ctx context.Context, id int32) (WeedImage, error)
	GetWeedImages(ctx context.Context, weedID int32) ([]WeedImage, error)
	GetWeedNotes(ctx context.Context, weedID int32) ([]WeedNote, error)
	GetWeedStatsByWeedID(ctx context.Context, weedID int32) (WeedStat, error)
	GetWeedWithPrimaryImage(ctx context.Context, id int32) (GetWeedWithPrimaryImageRow, error)
	ListCatalogProposalsWithPendingWeed(ctx context.Context, arg ListCatalogProposalsWithPendingWeedParams) ([]ListCatalogProposalsWithPendingWeedRow, error)
	ListWeeds(ctx context.Context, arg ListWeedsParams) ([]ListWeedsRow, error)
	MarkCatalogProposalApplied(ctx context.Context, arg MarkCatalogProposalAppliedParams) (CatalogProposal, error)
	SetPrimaryImage(ctx context.Context, id int32) error
	UnsetPrimaryImage(ctx context.Context, id int32) error
	UpdateCatalogProposal(ctx context.Context, arg UpdateCatalogProposalParams) (CatalogProposal, error)
	UpdateCatalogProposalStatus(ctx context.Context, arg UpdateCatalogProposalStatusParams) (CatalogProposal, error)
	UpdatePendingWeed(ctx context.Context, arg UpdatePendingWeedParams) (PendingWeed, error)
	UpdatePendingWeedStats(ctx context.Context, arg UpdatePendingWeedStatsParams) (PendingWeedStat, error)
	UpdateWeed(ctx context.Context, arg UpdateWeedParams) (Weed, error)
	UpdateWeedStats(ctx context.Context, arg UpdateWeedStatsParams) (WeedStat, error)
	WeedHasPrimaryImage(ctx context.Context, weedID int32) (bool, error)
}

var _ Querier = (*Queries)(nil)
