// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weeds.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWeedImage = `-- name: AddWeedImage :one
INSERT INTO
    weed_images (weed_id, image_key)
VALUES
    (
        $1,
        $2
    ) RETURNING id, weed_id, image_key, is_primary, created_at
`

type AddWeedImageParams struct {
	WeedID   int32  `json:"weed_id"`
	ImageKey string `json:"image_key"`
}

func (q *Queries) AddWeedImage(ctx context.Context, arg AddWeedImageParams) (WeedImage, error) {
	row := q.db.QueryRow(ctx, addWeedImage, arg.WeedID, arg.ImageKey)
	var i WeedImage
	err := row.Scan(
		&i.ID,
		&i.WeedID,
		&i.ImageKey,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const bulkInsertWeedAnalyses = `-- name: BulkInsertWeedAnalyses :exec
INSERT INTO
    weed_analyses (weed_id, analysis_id)
SELECT
    $1::int,
    unnest(CAST($2 AS text[]))
`

type BulkInsertWeedAnalysesParams struct {
	WeedID      int32    `json:"weed_id"`
	AnalysisIds []string `json:"analysis_ids"`
}

func (q *Queries) BulkInsertWeedAnalyses(ctx context.Context, arg BulkInsertWeedAnalysesParams) error {
	_, err := q.db.Exec(ctx, bulkInsertWeedAnalyses, arg.WeedID, arg.AnalysisIds)
	return err
}

const bulkInsertWeedImages = `-- name: BulkInsertWeedImages :exec
INSERT INTO
    weed_images (weed_id, image_key, is_primary)
SELECT
    $1::int,
    keys.arr [idx.i],
    flags.arr [idx.i]
FROM
    generate_subscripts(CAST($2 AS text[]), 1) AS idx(i)
    CROSS JOIN (
        SELECT
            CAST($2 AS text[]) AS arr
    ) AS keys
    CROSS JOIN (
        SELECT
            CAST($3 AS bool[]) AS arr
    ) AS flags
`

type BulkInsertWeedImagesParams struct {
	WeedID         int32    `json:"weed_id"`
	ImageKeys      []string `json:"image_keys"`
	IsPrimaryFlags []bool   `json:"is_primary_flags"`
}

func (q *Queries) BulkInsertWeedImages(ctx context.Context, arg BulkInsertWeedImagesParams) error {
	_, err := q.db.Exec(ctx, bulkInsertWeedImages, arg.WeedID, arg.ImageKeys, arg.IsPrimaryFlags)
	return err
}

const clearPrimaryImageForWeed = `-- name: ClearPrimaryImageForWeed :exec
UPDATE
    weed_images
SET
    is_primary = FALSE
WHERE
    weed_id = $1
`

func (q *Queries) ClearPrimaryImageForWeed(ctx context.Context, weedID int32) error {
	_, err := q.db.Exec(ctx, clearPrimaryImageForWeed, weedID)
	return err
}

const countWeeds = `-- name: CountWeeds :one
SELECT
    count(*)
FROM
    weeds w
    LEFT JOIN weed_stats ws ON ws.weed_id = w.id
WHERE
    (
        $1 :: text IS NULL
        OR w.name ILIKE '%' || $1 || '%'
    )
    AND (
        $2 :: real IS NULL OR COALESCE(ws.l_median, w.length) >= $2
    )
    AND (
        $3 :: real IS NULL OR COALESCE(ws.l_median, w.length) <= $3
    )
    AND (
        $4 :: real IS NULL OR COALESCE(ws.w_median, w.width) >= $4
    )
    AND (
        $5 :: real IS NULL OR COALESCE(ws.w_median, w.width) <= $5
    )
    AND (
        $6 :: real IS NULL OR COALESCE(ws.l_median / NULLIF(ws.w_median, 0), w.length / NULLIF(w.width, 0)) >= $6
    )
    AND (
        $7 :: real IS NULL OR COALESCE(ws.l_median / NULLIF(ws.w_median, 0), w.length / NULLIF(w.width, 0)) <= $7
    )
    AND (
        $8 :: real IS NULL OR ws.h_median >= $8
    )
    AND (
        $9 :: real IS NULL OR ws.h_median <= $9
    )
    AND (
        $10 :: real IS NULL OR ws.s_median >= $10
    )
    AND (
        $11 :: real IS NULL OR ws.s_median <= $11
    )
    AND (
        $12 :: real IS NULL OR ws.v_median >= $12
    )
    AND (
        $13 :: real IS NULL OR ws.v_median <= $13
    )
    AND (
        $14 :: real IS NULL OR ws.r_median >= $14
    )
    AND (
        $15 :: real IS NULL OR ws.r_median <= $15
    )
    AND (
        $16 :: real IS NULL OR ws.g_median >= $16
    )
    AND (
        $17 :: real IS NULL OR ws.g_median <= $17
    )
    AND (
        $18 :: real IS NULL OR ws.b_median >= $18
    )
    AND (
        $19 :: real IS NULL OR ws.b_median <= $19
    )
    AND (
        $20 :: real IS NULL OR ws.brt_median >= $20
    )
    AND (
        $21 :: real IS NULL OR ws.brt_median <= $21
    )
    AND (
        $22 :: real IS NULL OR ws.sq_sqcrl_median >= $22
    )
    AND (
        $23 :: real IS NULL OR ws.sq_sqcrl_median <= $23
    )
    AND (
        $24 :: text IS NULL
        OR w.main_group = $24
    )
    AND (
        $25 :: text IS NULL
        OR w.main_subgroup = $25
    )
    AND (
        $26 :: text IS NULL
        OR w.subgroup = $26
    )
    AND (
        $27 :: bool IS NULL
        OR w.is_quarantine = $27
    )
`

type CountWeedsParams struct {
	Name         *string  `json:"name"`
	LMin         *float32 `json:"l_min"`
	LMax         *float32 `json:"l_max"`
	WMin         *float32 `json:"w_min"`
	WMax         *float32 `json:"w_max"`
	LwMin        *float32 `json:"lw_min"`
	LwMax        *float32 `json:"lw_max"`
	HMin         *float32 `json:"h_min"`
	HMax         *float32 `json:"h_max"`
	SMin         *float32 `json:"s_min"`
	SMax         *float32 `json:"s_max"`
	VMin         *float32 `json:"v_min"`
	VMax         *float32 `json:"v_max"`
	RMin         *float32 `json:"r_min"`
	RMax         *float32 `json:"r_max"`
	GMin         *float32 `json:"g_min"`
	GMax         *float32 `json:"g_max"`
	BMin         *float32 `json:"b_min"`
	BMax         *float32 `json:"b_max"`
	BrtMin       *float32 `json:"brt_min"`
	BrtMax       *float32 `json:"brt_max"`
	SqSqcrlMin   *float32 `json:"sq_sqcrl_min"`
	SqSqcrlMax   *float32 `json:"sq_sqcrl_max"`
	MainGroup    *string  `json:"main_group"`
	MainSubgroup *string  `json:"main_subgroup"`
	Subgroup     *string  `json:"subgroup"`
	IsQuarantine *bool    `json:"is_quarantine"`
}

func (q *Queries) CountWeeds(ctx context.Context, arg CountWeedsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWeeds,
		arg.Name,
		arg.LMin,
		arg.LMax,
		arg.WMin,
		arg.WMax,
		arg.LwMin,
		arg.LwMax,
		arg.HMin,
		arg.HMax,
		arg.SMin,
		arg.SMax,
		arg.VMin,
		arg.VMax,
		arg.RMin,
		arg.RMax,
		arg.GMin,
		arg.GMax,
		arg.BMin,
		arg.BMax,
		arg.BrtMin,
		arg.BrtMax,
		arg.SqSqcrlMin,
		arg.SqSqcrlMax,
		arg.MainGroup,
		arg.MainSubgroup,
		arg.Subgroup,
		arg.IsQuarantine,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWeed = `-- name: CreateWeed :one
INSERT INTO
    weeds (
        name,
        latin_name,
        description,
        length,
        width,
        main_group,
        main_subgroup,
        subgroup,
        is_quarantine,
        harmfulness
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    ) RETURNING id, name, latin_name, description, length, width, main_group, main_subgroup, subgroup, is_quarantine, harmfulness, created_at, updated_at
`

type CreateWeedParams struct {
	Name         string   `json:"name"`
	LatinName    *string  `json:"latin_name"`
	Description  *string  `json:"description"`
	Length       *float32 `json:"length"`
	Width        *float32 `json:"width"`
	MainGroup    *string  `json:"main_group"`
	MainSubgroup *string  `json:"main_subgroup"`
	Subgroup     *string  `json:"subgroup"`
	IsQuarantine bool     `json:"is_quarantine"`
	Harmfulness  *string  `json:"harmfulness"`
}

func (q *Queries) CreateWeed(ctx context.Context, arg CreateWeedParams) (Weed, error) {
	row := q.db.QueryRow(ctx, createWeed,
		arg.Name,
		arg.LatinName,
		arg.Description,
		arg.Length,
		arg.Width,
		arg.MainGroup,
		arg.MainSubgroup,
		arg.Subgroup,
		arg.IsQuarantine,
		arg.Harmfulness,
	)
	var i Weed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LatinName,
		&i.Description,
		&i.Length,
		&i.Width,
		&i.MainGroup,
		&i.MainSubgroup,
		&i.Subgroup,
		&i.IsQuarantine,
		&i.Harmfulness,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWeedStats = `-- name: CreateWeedStats :one
INSERT INTO
    weed_stats (
        weed_id,
        w_avg,
        w_median,
        w_min,
        w_max,
        l_avg,
        l_median,
        l_min,
        l_max,
        sq_avg,
        sq_median,
        sq_min,
        sq_max,
        r_avg,
        r_median,
        r_min,
        r_max,
        g_avg,
        g_median,
        g_min,
        g_max,
        b_avg,
        b_median,
        b_min,
        b_max,
        h_avg,
        h_median,
        h_min,
        h_max,
        s_avg,
        s_median,
        s_min,
        s_max,
        v_avg,
        v_median,
        v_min,
        v_max,
        lw_avg,
        lw_median,
        lw_min,
        lw_max,
        brt_avg,
        brt_median,
        brt_min,
        brt_max,
        solid_avg,
        solid_median,
        solid_min,
        solid_max,
        sq_sqcrl_avg,
        sq_sqcrl_median,
        sq_sqcrl_min,
        sq_sqcrl_max,
        excluded_objects
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35,
        $36,
        $37,
        $38,
        $39,
        $40,
        $41,
        $42,
        $43,
        $44,
        $45,
        $46,
        $47,
        $48,
        $49,
        $50,
        $51,
        $52,
        $53,
        $54
    ) RETURNING id, weed_id, w_avg, w_median, w_min, w_max, l_avg, l_median, l_min, l_max, sq_avg, sq_median, sq_min, sq_max, r_avg, r_median, r_min, r_max, g_avg, g_median, g_min, g_max, b_avg, b_median, b_min, b_max, h_avg, h_median, h_min, h_max, s_avg, s_median, s_min, s_max, v_avg, v_median, v_min, v_max, lw_avg, lw_median, lw_min, lw_max, brt_avg, brt_median, brt_min, brt_max, solid_avg, solid_median, solid_min, solid_max, sq_sqcrl_avg, sq_sqcrl_median, sq_sqcrl_min, sq_sqcrl_max, excluded_objects, created_at, updated_at
`

type CreateWeedStatsParams struct {
	WeedID          int32   `json:"weed_id"`
	WAvg            float32 `json:"w_avg"`
	WMedian         float32 `json:"w_median"`
	WMin            float32 `json:"w_min"`
	WMax            float32 `json:"w_max"`
	LAvg            float32 `json:"l_avg"`
	LMedian         float32 `json:"l_median"`
	LMin            float32 `json:"l_min"`
	LMax            float32 `json:"l_max"`
	SqAvg           float32 `json:"sq_avg"`
	SqMedian        float32 `json:"sq_median"`
	SqMin           float32 `json:"sq_min"`
	SqMax           float32 `json:"sq_max"`
	RAvg            float32 `json:"r_avg"`
	RMedian         float32 `json:"r_median"`
	RMin            float32 `json:"r_min"`
	RMax            float32 `json:"r_max"`
	GAvg            float32 `json:"g_avg"`
	GMedian         float32 `json:"g_median"`
	GMin            float32 `json:"g_min"`
	GMax            float32 `json:"g_max"`
	BAvg            float32 `json:"b_avg"`
	BMedian         float32 `json:"b_median"`
	BMin            float32 `json:"b_min"`
	BMax            float32 `json:"b_max"`
	HAvg            float32 `json:"h_avg"`
	HMedian         float32 `json:"h_median"`
	HMin            float32 `json:"h_min"`
	HMax            float32 `json:"h_max"`
	SAvg            float32 `json:"s_avg"`
	SMedian         float32 `json:"s_median"`
	SMin            float32 `json:"s_min"`
	SMax            float32 `json:"s_max"`
	VAvg            float32 `json:"v_avg"`
	VMedian         float32 `json:"v_median"`
	VMin            float32 `json:"v_min"`
	VMax            float32 `json:"v_max"`
	LwAvg           float32 `json:"lw_avg"`
	LwMedian        float32 `json:"lw_median"`
	LwMin           float32 `json:"lw_min"`
	LwMax           float32 `json:"lw_max"`
	BrtAvg          float32 `json:"brt_avg"`
	BrtMedian       float32 `json:"brt_median"`
	BrtMin          float32 `json:"brt_min"`
	BrtMax          float32 `json:"brt_max"`
	SolidAvg        float32 `json:"solid_avg"`
	SolidMedian     float32 `json:"solid_median"`
	SolidMin        float32 `json:"solid_min"`
	SolidMax        float32 `json:"solid_max"`
	SqSqcrlAvg      float32 `json:"sq_sqcrl_avg"`
	SqSqcrlMedian   float32 `json:"sq_sqcrl_median"`
	SqSqcrlMin      float32 `json:"sq_sqcrl_min"`
	SqSqcrlMax      float32 `json:"sq_sqcrl_max"`
	ExcludedObjects []byte  `json:"excluded_objects"`
}

func (q *Queries) CreateWeedStats(ctx context.Context, arg CreateWeedStatsParams) (WeedStat, error) {
	row := q.db.QueryRow(ctx, createWeedStats,
		arg.WeedID,
		arg.WAvg,
		arg.WMedian,
		arg.WMin,
		arg.WMax,
		arg.LAvg,
		arg.LMedian,
		arg.LMin,
		arg.LMax,
		arg.SqAvg,
		arg.SqMedian,
		arg.SqMin,
		arg.SqMax,
		arg.RAvg,
		arg.RMedian,
		arg.RMin,
		arg.RMax,
		arg.GAvg,
		arg.GMedian,
		arg.GMin,
		arg.GMax,
		arg.BAvg,
		arg.BMedian,
		arg.BMin,
		arg.BMax,
		arg.HAvg,
		arg.HMedian,
		arg.HMin,
		arg.HMax,
		arg.SAvg,
		arg.SMedian,
		arg.SMin,
		arg.SMax,
		arg.VAvg,
		arg.VMedian,
		arg.VMin,
		arg.VMax,
		arg.LwAvg,
		arg.LwMedian,
		arg.LwMin,
		arg.LwMax,
		arg.BrtAvg,
		arg.BrtMedian,
		arg.BrtMin,
		arg.BrtMax,
		arg.SolidAvg,
		arg.SolidMedian,
		arg.SolidMin,
		arg.SolidMax,
		arg.SqSqcrlAvg,
		arg.SqSqcrlMedian,
		arg.SqSqcrlMin,
		arg.SqSqcrlMax,
		arg.ExcludedObjects,
	)
	var i WeedStat
	err := row.Scan(
		&i.ID,
		&i.WeedID,
		&i.WAvg,
		&i.WMedian,
		&i.WMin,
		&i.WMax,
		&i.LAvg,
		&i.LMedian,
		&i.LMin,
		&i.LMax,
		&i.SqAvg,
		&i.SqMedian,
		&i.SqMin,
		&i.SqMax,
		&i.RAvg,
		&i.RMedian,
		&i.RMin,
		&i.RMax,
		&i.GAvg,
		&i.GMedian,
		&i.GMin,
		&i.GMax,
		&i.BAvg,
		&i.BMedian,
		&i.BMin,
		&i.BMax,
		&i.HAvg,
		&i.HMedian,
		&i.HMin,
		&i.HMax,
		&i.SAvg,
		&i.SMedian,
		&i.SMin,
		&i.SMax,
		&i.VAvg,
		&i.VMedian,
		&i.VMin,
		&i.VMax,
		&i.LwAvg,
		&i.LwMedian,
		&i.LwMin,
		&i.LwMax,
		&i.BrtAvg,
		&i.BrtMedian,
		&i.BrtMin,
		&i.BrtMax,
		&i.SolidAvg,
		&i.SolidMedian,
		&i.SolidMin,
		&i.SolidMax,
		&i.SqSqcrlAvg,
		&i.SqSqcrlMedian,
		&i.SqSqcrlMin,
		&i.SqSqcrlMax,
		&i.ExcludedObjects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllWeedImages = `-- name: DeleteAllWeedImages :exec
DELETE FROM
    weed_images
WHERE
    weed_id = $1
`

func (q *Queries) DeleteAllWeedImages(ctx context.Context, weedID int32) error {
	_, err := q.db.Exec(ctx, deleteAllWeedImages, weedID)
	return err
}

const deleteWeed = `-- name: DeleteWeed :exec
DELETE FROM
    weeds
WHERE
    id = $1
`

func (q *Queries) DeleteWeed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWeed, id)
	return err
}

const deleteWeedAnalysesByWeedID = `-- name: DeleteWeedAnalysesByWeedID :exec
DELETE FROM weed_analyses
WHERE weed_id = $1
`

func (q *Queries) DeleteWeedAnalysesByWeedID(ctx context.Context, weedID int32) error {
	_, err := q.db.Exec(ctx, deleteWeedAnalysesByWeedID, weedID)
	return err
}

const deleteWeedImage = `-- name: DeleteWeedImage :exec
DELETE FROM
    weed_images
WHERE
    id = $1
`

func (q *Queries) DeleteWeedImage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWeedImage, id)
	return err
}

const getWeedAnalyses = `-- name: GetWeedAnalyses :many
SELECT
    id, weed_id, analysis_id
FROM
    weed_analyses
WHERE
    weed_id = $1
`

func (q *Queries) GetWeedAnalyses(ctx context.Context, weedID int32) ([]WeedAnalysis, error) {
	rows, err := q.db.Query(ctx, getWeedAnalyses, weedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeedAnalysis{}
	for rows.Next() {
		var i WeedAnalysis
		if err := rows.Scan(&i.ID, &i.WeedID, &i.AnalysisID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeedByID = `-- name: GetWeedByID :one
SELECT
    id, name, latin_name, description, length, width, main_group, main_subgroup, subgroup, is_quarantine, harmfulness, created_at, updated_at
FROM
    weeds
WHERE
    id = $1
`

func (q *Queries) GetWeedByID(ctx context.Context, id int32) (Weed, error) {
	row := q.db.QueryRow(ctx, getWeedByID, id)
	var i Weed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LatinName,
		&i.Description,
		&i.Length,
		&i.Width,
		&i.MainGroup,
		&i.MainSubgroup,
		&i.Subgroup,
		&i.IsQuarantine,
		&i.Harmfulness,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeedImageByID = `-- name: GetWeedImageByID :one
SELECT
    id, weed_id, image_key, is_primary, created_at
FROM
    weed_images
WHERE
    id = $1
`

func (q *Queries) GetWeedImageByID(ctx context.Context, id int32) (WeedImage, error) {
	row := q.db.QueryRow(ctx, getWeedImageByID, id)
	var i WeedImage
	err := row.Scan(
		&i.ID,
		&i.WeedID,
		&i.ImageKey,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getWeedImages = `-- name: GetWeedImages :many
SELECT
    id, weed_id, image_key, is_primary, created_at
FROM
    weed_images
WHERE
    weed_id = $1
ORDER BY
    created_at
`

func (q *Queries) GetWeedImages(ctx context.Context, weedID int32) ([]WeedImage, error) {
	rows, err := q.db.Query(ctx, getWeedImages, weedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeedImage{}
	for rows.Next() {
		var i WeedImage
		if err := rows.Scan(
			&i.ID,
			&i.WeedID,
			&i.ImageKey,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeedStatsByWeedID = `-- name: GetWeedStatsByWeedID :one
SELECT
    id, weed_id, w_avg, w_median, w_min, w_max, l_avg, l_median, l_min, l_max, sq_avg, sq_median, sq_min, sq_max, r_avg, r_median, r_min, r_max, g_avg, g_median, g_min, g_max, b_avg, b_median, b_min, b_max, h_avg, h_median, h_min, h_max, s_avg, s_median, s_min, s_max, v_avg, v_median, v_min, v_max, lw_avg, lw_median, lw_min, lw_max, brt_avg, brt_median, brt_min, brt_max, solid_avg, solid_median, solid_min, solid_max, sq_sqcrl_avg, sq_sqcrl_median, sq_sqcrl_min, sq_sqcrl_max, excluded_objects, created_at, updated_at
FROM
    weed_stats
WHERE
    weed_id = $1
`

func (q *Queries) GetWeedStatsByWeedID(ctx context.Context, weedID int32) (WeedStat, error) {
	row := q.db.QueryRow(ctx, getWeedStatsByWeedID, weedID)
	var i WeedStat
	err := row.Scan(
		&i.ID,
		&i.WeedID,
		&i.WAvg,
		&i.WMedian,
		&i.WMin,
		&i.WMax,
		&i.LAvg,
		&i.LMedian,
		&i.LMin,
		&i.LMax,
		&i.SqAvg,
		&i.SqMedian,
		&i.SqMin,
		&i.SqMax,
		&i.RAvg,
		&i.RMedian,
		&i.RMin,
		&i.RMax,
		&i.GAvg,
		&i.GMedian,
		&i.GMin,
		&i.GMax,
		&i.BAvg,
		&i.BMedian,
		&i.BMin,
		&i.BMax,
		&i.HAvg,
		&i.HMedian,
		&i.HMin,
		&i.HMax,
		&i.SAvg,
		&i.SMedian,
		&i.SMin,
		&i.SMax,
		&i.VAvg,
		&i.VMedian,
		&i.VMin,
		&i.VMax,
		&i.LwAvg,
		&i.LwMedian,
		&i.LwMin,
		&i.LwMax,
		&i.BrtAvg,
		&i.BrtMedian,
		&i.BrtMin,
		&i.BrtMax,
		&i.SolidAvg,
		&i.SolidMedian,
		&i.SolidMin,
		&i.SolidMax,
		&i.SqSqcrlAvg,
		&i.SqSqcrlMedian,
		&i.SqSqcrlMin,
		&i.SqSqcrlMax,
		&i.ExcludedObjects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeedWithPrimaryImage = `-- name: GetWeedWithPrimaryImage :one
SELECT
    w.id, w.name, w.latin_name, w.description, w.length, w.width, w.main_group, w.main_subgroup, w.subgroup, w.is_quarantine, w.harmfulness, w.created_at, w.updated_at,
    wi.image_key AS primary_image_key
FROM
    weeds w
    LEFT JOIN weed_images wi ON w.id = wi.weed_id AND wi.is_primary = TRUE
    LEFT JOIN weed_stats ws ON ws.weed_id = w.id
WHERE
    w.id = $1
`

type GetWeedWithPrimaryImageRow struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	LatinName       *string            `json:"latin_name"`
	Description     *string            `json:"description"`
	Length          *float32           `json:"length"`
	Width           *float32           `json:"width"`
	MainGroup       *string            `json:"main_group"`
	MainSubgroup    *string            `json:"main_subgroup"`
	Subgroup        *string            `json:"subgroup"`
	IsQuarantine    bool               `json:"is_quarantine"`
	Harmfulness     *string            `json:"harmfulness"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PrimaryImageKey *string            `json:"primary_image_key"`
}

func (q *Queries) GetWeedWithPrimaryImage(ctx context.Context, id int32) (GetWeedWithPrimaryImageRow, error) {
	row := q.db.QueryRow(ctx, getWeedWithPrimaryImage, id)
	var i GetWeedWithPrimaryImageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LatinName,
		&i.Description,
		&i.Length,
		&i.Width,
		&i.MainGroup,
		&i.MainSubgroup,
		&i.Subgroup,
		&i.IsQuarantine,
		&i.Harmfulness,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryImageKey,
	)
	return i, err
}

const listWeeds = `-- name: ListWeeds :many
SELECT
    w.id, w.name, w.latin_name, w.description, w.length, w.width, w.main_group, w.main_subgroup, w.subgroup, w.is_quarantine, w.harmfulness, w.created_at, w.updated_at,
    wi.image_key AS primary_image_key
FROM
    weeds w
    LEFT JOIN weed_images wi ON w.id = wi.weed_id AND wi.is_primary = TRUE
    LEFT JOIN weed_stats ws ON ws.weed_id = w.id
WHERE
    (
        $1 :: text IS NULL
        OR w.name ILIKE '%' || $1 || '%'
    )
    AND (
        $2 :: text IS NULL
        OR w.main_group = $2
    )
    AND (
        $3 :: text IS NULL
        OR w.main_subgroup = $3
    )
    AND (
        $4 :: text IS NULL
        OR w.subgroup = $4
    )
    AND (
        $5 :: bool IS NULL
        OR w.is_quarantine = $5
    )
    -- Stats range filters (medians by default, with fallbacks for size)
    AND (
        $6 :: real IS NULL OR COALESCE(ws.l_median, w.length) >= $6
    )
    AND (
        $7 :: real IS NULL OR COALESCE(ws.l_median, w.length) <= $7
    )
    AND (
        $8 :: real IS NULL OR COALESCE(ws.w_median, w.width) >= $8
    )
    AND (
        $9 :: real IS NULL OR COALESCE(ws.w_median, w.width) <= $9
    )
    AND (
        $10 :: real IS NULL OR COALESCE(ws.l_median / NULLIF(ws.w_median, 0), w.length / NULLIF(w.width, 0)) >= $10
    )
    AND (
        $11 :: real IS NULL OR COALESCE(ws.l_median / NULLIF(ws.w_median, 0), w.length / NULLIF(w.width, 0)) <= $11
    )
    AND (
        $12 :: real IS NULL OR ws.h_median >= $12
    )
    AND (
        $13 :: real IS NULL OR ws.h_median <= $13
    )
    AND (
        $14 :: real IS NULL OR ws.s_median >= $14
    )
    AND (
        $15 :: real IS NULL OR ws.s_median <= $15
    )
    AND (
        $16 :: real IS NULL OR ws.v_median >= $16
    )
    AND (
        $17 :: real IS NULL OR ws.v_median <= $17
    )
    AND (
        $18 :: real IS NULL OR ws.r_median >= $18
    )
    AND (
        $19 :: real IS NULL OR ws.r_median <= $19
    )
    AND (
        $20 :: real IS NULL OR ws.g_median >= $20
    )
    AND (
        $21 :: real IS NULL OR ws.g_median <= $21
    )
    AND (
        $22 :: real IS NULL OR ws.b_median >= $22
    )
    AND (
        $23 :: real IS NULL OR ws.b_median <= $23
    )
    AND (
        $24 :: real IS NULL OR ws.brt_median >= $24
    )
    AND (
        $25 :: real IS NULL OR ws.brt_median <= $25
    )
    AND (
        $26 :: real IS NULL OR ws.sq_sqcrl_median >= $26
    )
    AND (
        $27 :: real IS NULL OR ws.sq_sqcrl_median <= $27
    )
ORDER BY
    CASE 
        WHEN $28 :: text = 'desc' THEN w.created_at
        ELSE NULL
    END DESC,
    CASE 
        WHEN $28 :: text = 'asc' THEN w.created_at
        ELSE NULL
    END ASC
LIMIT
    $30 OFFSET $29
`

type ListWeedsParams struct {
	Name         *string  `json:"name"`
	MainGroup    *string  `json:"main_group"`
	MainSubgroup *string  `json:"main_subgroup"`
	Subgroup     *string  `json:"subgroup"`
	IsQuarantine *bool    `json:"is_quarantine"`
	LMin         *float32 `json:"l_min"`
	LMax         *float32 `json:"l_max"`
	WMin         *float32 `json:"w_min"`
	WMax         *float32 `json:"w_max"`
	LwMin        *float32 `json:"lw_min"`
	LwMax        *float32 `json:"lw_max"`
	HMin         *float32 `json:"h_min"`
	HMax         *float32 `json:"h_max"`
	SMin         *float32 `json:"s_min"`
	SMax         *float32 `json:"s_max"`
	VMin         *float32 `json:"v_min"`
	VMax         *float32 `json:"v_max"`
	RMin         *float32 `json:"r_min"`
	RMax         *float32 `json:"r_max"`
	GMin         *float32 `json:"g_min"`
	GMax         *float32 `json:"g_max"`
	BMin         *float32 `json:"b_min"`
	BMax         *float32 `json:"b_max"`
	BrtMin       *float32 `json:"brt_min"`
	BrtMax       *float32 `json:"brt_max"`
	SqSqcrlMin   *float32 `json:"sq_sqcrl_min"`
	SqSqcrlMax   *float32 `json:"sq_sqcrl_max"`
	SortOrder    string   `json:"sort_order"`
	Offset       int32    `json:"offset"`
	Limit        int32    `json:"limit"`
}

type ListWeedsRow struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	LatinName       *string            `json:"latin_name"`
	Description     *string            `json:"description"`
	Length          *float32           `json:"length"`
	Width           *float32           `json:"width"`
	MainGroup       *string            `json:"main_group"`
	MainSubgroup    *string            `json:"main_subgroup"`
	Subgroup        *string            `json:"subgroup"`
	IsQuarantine    bool               `json:"is_quarantine"`
	Harmfulness     *string            `json:"harmfulness"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PrimaryImageKey *string            `json:"primary_image_key"`
}

func (q *Queries) ListWeeds(ctx context.Context, arg ListWeedsParams) ([]ListWeedsRow, error) {
	rows, err := q.db.Query(ctx, listWeeds,
		arg.Name,
		arg.MainGroup,
		arg.MainSubgroup,
		arg.Subgroup,
		arg.IsQuarantine,
		arg.LMin,
		arg.LMax,
		arg.WMin,
		arg.WMax,
		arg.LwMin,
		arg.LwMax,
		arg.HMin,
		arg.HMax,
		arg.SMin,
		arg.SMax,
		arg.VMin,
		arg.VMax,
		arg.RMin,
		arg.RMax,
		arg.GMin,
		arg.GMax,
		arg.BMin,
		arg.BMax,
		arg.BrtMin,
		arg.BrtMax,
		arg.SqSqcrlMin,
		arg.SqSqcrlMax,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeedsRow{}
	for rows.Next() {
		var i ListWeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LatinName,
			&i.Description,
			&i.Length,
			&i.Width,
			&i.MainGroup,
			&i.MainSubgroup,
			&i.Subgroup,
			&i.IsQuarantine,
			&i.Harmfulness,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryImage = `-- name: SetPrimaryImage :exec
UPDATE
    weed_images
SET
    is_primary = TRUE
WHERE
    id = $1
`

func (q *Queries) SetPrimaryImage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setPrimaryImage, id)
	return err
}

const unsetPrimaryImage = `-- name: UnsetPrimaryImage :exec
UPDATE
    weed_images
SET
    is_primary = FALSE
WHERE
    id = $1
`

func (q *Queries) UnsetPrimaryImage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, unsetPrimaryImage, id)
	return err
}

const updateWeed = `-- name: UpdateWeed :one
UPDATE
    weeds
SET
    name = $1,
    latin_name = $2,
    description = $3,
    length = $4,
    width = $5,
    main_group = $6,
    main_subgroup = $7,
    subgroup = $8,
    is_quarantine = $9,
    harmfulness = $10
WHERE
    id = $11 RETURNING id, name, latin_name, description, length, width, main_group, main_subgroup, subgroup, is_quarantine, harmfulness, created_at, updated_at
`

type UpdateWeedParams struct {
	Name         string   `json:"name"`
	LatinName    *string  `json:"latin_name"`
	Description  *string  `json:"description"`
	Length       *float32 `json:"length"`
	Width        *float32 `json:"width"`
	MainGroup    *string  `json:"main_group"`
	MainSubgroup *string  `json:"main_subgroup"`
	Subgroup     *string  `json:"subgroup"`
	IsQuarantine bool     `json:"is_quarantine"`
	Harmfulness  *string  `json:"harmfulness"`
	ID           int32    `json:"id"`
}

func (q *Queries) UpdateWeed(ctx context.Context, arg UpdateWeedParams) (Weed, error) {
	row := q.db.QueryRow(ctx, updateWeed,
		arg.Name,
		arg.LatinName,
		arg.Description,
		arg.Length,
		arg.Width,
		arg.MainGroup,
		arg.MainSubgroup,
		arg.Subgroup,
		arg.IsQuarantine,
		arg.Harmfulness,
		arg.ID,
	)
	var i Weed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LatinName,
		&i.Description,
		&i.Length,
		&i.Width,
		&i.MainGroup,
		&i.MainSubgroup,
		&i.Subgroup,
		&i.IsQuarantine,
		&i.Harmfulness,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWeedStats = `-- name: UpdateWeedStats :one
UPDATE
    weed_stats
SET
    w_avg = $1,
    w_median = $2,
    w_min = $3,
    w_max = $4,
    l_avg = $5,
    l_median = $6,
    l_min = $7,
    l_max = $8,
    sq_avg = $9,
    sq_median = $10,
    sq_min = $11,
    sq_max = $12,
    r_avg = $13,
    r_median = $14,
    r_min = $15,
    r_max = $16,
    g_avg = $17,
    g_median = $18,
    g_min = $19,
    g_max = $20,
    b_avg = $21,
    b_median = $22,
    b_min = $23,
    b_max = $24,
    h_avg = $25,
    h_median = $26,
    h_min = $27,
    h_max = $28,
    s_avg = $29,
    s_median = $30,
    s_min = $31,
    s_max = $32,
    v_avg = $33,
    v_median = $34,
    v_min = $35,
    v_max = $36,
    lw_avg = $37,
    lw_median = $38,
    lw_min = $39,
    lw_max = $40,
    brt_avg = $41,
    brt_median = $42,
    brt_min = $43,
    brt_max = $44,
    solid_avg = $45,
    solid_median = $46,
    solid_min = $47,
    solid_max = $48,
    sq_sqcrl_avg = $49,
    sq_sqcrl_median = $50,
    sq_sqcrl_min = $51,
    sq_sqcrl_max = $52,
    excluded_objects = $53
WHERE
    weed_id = $54 RETURNING id, weed_id, w_avg, w_median, w_min, w_max, l_avg, l_median, l_min, l_max, sq_avg, sq_median, sq_min, sq_max, r_avg, r_median, r_min, r_max, g_avg, g_median, g_min, g_max, b_avg, b_median, b_min, b_max, h_avg, h_median, h_min, h_max, s_avg, s_median, s_min, s_max, v_avg, v_median, v_min, v_max, lw_avg, lw_median, lw_min, lw_max, brt_avg, brt_median, brt_min, brt_max, solid_avg, solid_median, solid_min, solid_max, sq_sqcrl_avg, sq_sqcrl_median, sq_sqcrl_min, sq_sqcrl_max, excluded_objects, created_at, updated_at
`

type UpdateWeedStatsParams struct {
	WAvg            float32 `json:"w_avg"`
	WMedian         float32 `json:"w_median"`
	WMin            float32 `json:"w_min"`
	WMax            float32 `json:"w_max"`
	LAvg            float32 `json:"l_avg"`
	LMedian         float32 `json:"l_median"`
	LMin            float32 `json:"l_min"`
	LMax            float32 `json:"l_max"`
	SqAvg           float32 `json:"sq_avg"`
	SqMedian        float32 `json:"sq_median"`
	SqMin           float32 `json:"sq_min"`
	SqMax           float32 `json:"sq_max"`
	RAvg            float32 `json:"r_avg"`
	RMedian         float32 `json:"r_median"`
	RMin            float32 `json:"r_min"`
	RMax            float32 `json:"r_max"`
	GAvg            float32 `json:"g_avg"`
	GMedian         float32 `json:"g_median"`
	GMin            float32 `json:"g_min"`
	GMax            float32 `json:"g_max"`
	BAvg            float32 `json:"b_avg"`
	BMedian         float32 `json:"b_median"`
	BMin            float32 `json:"b_min"`
	BMax            float32 `json:"b_max"`
	HAvg            float32 `json:"h_avg"`
	HMedian         float32 `json:"h_median"`
	HMin            float32 `json:"h_min"`
	HMax            float32 `json:"h_max"`
	SAvg            float32 `json:"s_avg"`
	SMedian         float32 `json:"s_median"`
	SMin            float32 `json:"s_min"`
	SMax            float32 `json:"s_max"`
	VAvg            float32 `json:"v_avg"`
	VMedian         float32 `json:"v_median"`
	VMin            float32 `json:"v_min"`
	VMax            float32 `json:"v_max"`
	LwAvg           float32 `json:"lw_avg"`
	LwMedian        float32 `json:"lw_median"`
	LwMin           float32 `json:"lw_min"`
	LwMax           float32 `json:"lw_max"`
	BrtAvg          float32 `json:"brt_avg"`
	BrtMedian       float32 `json:"brt_median"`
	BrtMin          float32 `json:"brt_min"`
	BrtMax          float32 `json:"brt_max"`
	SolidAvg        float32 `json:"solid_avg"`
	SolidMedian     float32 `json:"solid_median"`
	SolidMin        float32 `json:"solid_min"`
	SolidMax        float32 `json:"solid_max"`
	SqSqcrlAvg      float32 `json:"sq_sqcrl_avg"`
	SqSqcrlMedian   float32 `json:"sq_sqcrl_median"`
	SqSqcrlMin      float32 `json:"sq_sqcrl_min"`
	SqSqcrlMax      float32 `json:"sq_sqcrl_max"`
	ExcludedObjects []byte  `json:"excluded_objects"`
	WeedID          int32   `json:"weed_id"`
}

func (q *Queries) UpdateWeedStats(ctx context.Context, arg UpdateWeedStatsParams) (WeedStat, error) {
	row := q.db.QueryRow(ctx, updateWeedStats,
		arg.WAvg,
		arg.WMedian,
		arg.WMin,
		arg.WMax,
		arg.LAvg,
		arg.LMedian,
		arg.LMin,
		arg.LMax,
		arg.SqAvg,
		arg.SqMedian,
		arg.SqMin,
		arg.SqMax,
		arg.RAvg,
		arg.RMedian,
		arg.RMin,
		arg.RMax,
		arg.GAvg,
		arg.GMedian,
		arg.GMin,
		arg.GMax,
		arg.BAvg,
		arg.BMedian,
		arg.BMin,
		arg.BMax,
		arg.HAvg,
		arg.HMedian,
		arg.HMin,
		arg.HMax,
		arg.SAvg,
		arg.SMedian,
		arg.SMin,
		arg.SMax,
		arg.VAvg,
		arg.VMedian,
		arg.VMin,
		arg.VMax,
		arg.LwAvg,
		arg.LwMedian,
		arg.LwMin,
		arg.LwMax,
		arg.BrtAvg,
		arg.BrtMedian,
		arg.BrtMin,
		arg.BrtMax,
		arg.SolidAvg,
		arg.SolidMedian,
		arg.SolidMin,
		arg.SolidMax,
		arg.SqSqcrlAvg,
		arg.SqSqcrlMedian,
		arg.SqSqcrlMin,
		arg.SqSqcrlMax,
		arg.ExcludedObjects,
		arg.WeedID,
	)
	var i WeedStat
	err := row.Scan(
		&i.ID,
		&i.WeedID,
		&i.WAvg,
		&i.WMedian,
		&i.WMin,
		&i.WMax,
		&i.LAvg,
		&i.LMedian,
		&i.LMin,
		&i.LMax,
		&i.SqAvg,
		&i.SqMedian,
		&i.SqMin,
		&i.SqMax,
		&i.RAvg,
		&i.RMedian,
		&i.RMin,
		&i.RMax,
		&i.GAvg,
		&i.GMedian,
		&i.GMin,
		&i.GMax,
		&i.BAvg,
		&i.BMedian,
		&i.BMin,
		&i.BMax,
		&i.HAvg,
		&i.HMedian,
		&i.HMin,
		&i.HMax,
		&i.SAvg,
		&i.SMedian,
		&i.SMin,
		&i.SMax,
		&i.VAvg,
		&i.VMedian,
		&i.VMin,
		&i.VMax,
		&i.LwAvg,
		&i.LwMedian,
		&i.LwMin,
		&i.LwMax,
		&i.BrtAvg,
		&i.BrtMedian,
		&i.BrtMin,
		&i.BrtMax,
		&i.SolidAvg,
		&i.SolidMedian,
		&i.SolidMin,
		&i.SolidMax,
		&i.SqSqcrlAvg,
		&i.SqSqcrlMedian,
		&i.SqSqcrlMin,
		&i.SqSqcrlMax,
		&i.ExcludedObjects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weedHasPrimaryImage = `-- name: WeedHasPrimaryImage :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            weed_images
        WHERE
            weed_id = $1
            AND is_primary = TRUE
    )::bool AS has_primary
`

func (q *Queries) WeedHasPrimaryImage(ctx context.Context, weedID int32) (bool, error) {
	row := q.db.QueryRow(ctx, weedHasPrimaryImage, weedID)
	var has_primary bool
	err := row.Scan(&has_primary)
	return has_primary, err
}
