// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classifications.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClassification = `-- name: CreateClassification :one
INSERT INTO
    classifications (
        name,
        created_by,
        is_public,
        product_id
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4
    ) RETURNING id, name, created_by, is_public, product_id, created_at, updated_at
`

type CreateClassificationParams struct {
	Name      string    `json:"name"`
	CreatedBy int32     `json:"created_by"`
	IsPublic  bool      `json:"is_public"`
	ProductID uuid.UUID `json:"product_id"`
}

// Create a new classification
func (q *Queries) CreateClassification(ctx context.Context, arg CreateClassificationParams) (Classification, error) {
	row := q.db.QueryRow(ctx, createClassification,
		arg.Name,
		arg.CreatedBy,
		arg.IsPublic,
		arg.ProductID,
	)
	var i Classification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.IsPublic,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClassification = `-- name: DeleteClassification :exec
DELETE FROM
    classifications
WHERE
    id = $1
`

// Delete a classification by ID
func (q *Queries) DeleteClassification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClassification, id)
	return err
}

const getClassificationByID = `-- name: GetClassificationByID :one
SELECT
    id, name, created_by, is_public, product_id, created_at, updated_at
FROM
    classifications
WHERE
    id = $1
`

// Get a classification by its ID
func (q *Queries) GetClassificationByID(ctx context.Context, id uuid.UUID) (Classification, error) {
	row := q.db.QueryRow(ctx, getClassificationByID, id)
	var i Classification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.IsPublic,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassificationsWithFiltersAndActive = `-- name: GetClassificationsWithFiltersAndActive :many
SELECT
    c.id,
    c.name,
    c.created_by,
    c.is_public,
    c.product_id,
    c.created_at,
    c.updated_at,
    p.id AS product_id_full,
    p.name AS product_name,
    p.created_at AS product_created_at,
    p.updated_at AS product_updated_at,
    (uac.classification_id IS NOT NULL) AS is_user_active
FROM
    classifications AS c
    JOIN products p ON c.product_id = p.id
    LEFT JOIN user_active_classification uac ON uac.user_id = $1
    AND uac.classification_id = c.id
WHERE
    (
        $2::int IS NULL
        OR c.is_public = true
        OR c.created_by = $2
    )
    AND ($3::uuid IS NULL OR c.product_id = $3)
    AND ($4::text IS NULL OR c.name ILIKE '%' || $4 || '%')
`

type GetClassificationsWithFiltersAndActiveParams struct {
	UserID    int32       `json:"user_id"`
	CreatedBy *int32      `json:"created_by"`
	ProductID pgtype.UUID `json:"product_id"`
	Name      *string     `json:"name"`
}

type GetClassificationsWithFiltersAndActiveRow struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	CreatedBy        int32       `json:"created_by"`
	IsPublic         bool        `json:"is_public"`
	ProductID        uuid.UUID   `json:"product_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	ProductIDFull    uuid.UUID   `json:"product_id_full"`
	ProductName      string      `json:"product_name"`
	ProductCreatedAt time.Time   `json:"product_created_at"`
	ProductUpdatedAt time.Time   `json:"product_updated_at"`
	IsUserActive     interface{} `json:"is_user_active"`
}

// Get classifications with product and flag for user's active classification
func (q *Queries) GetClassificationsWithFiltersAndActive(ctx context.Context, arg GetClassificationsWithFiltersAndActiveParams) ([]GetClassificationsWithFiltersAndActiveRow, error) {
	rows, err := q.db.Query(ctx, getClassificationsWithFiltersAndActive,
		arg.UserID,
		arg.CreatedBy,
		arg.ProductID,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClassificationsWithFiltersAndActiveRow{}
	for rows.Next() {
		var i GetClassificationsWithFiltersAndActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.IsPublic,
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductIDFull,
			&i.ProductName,
			&i.ProductCreatedAt,
			&i.ProductUpdatedAt,
			&i.IsUserActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompleteClassificationByID = `-- name: GetCompleteClassificationByID :one
WITH classification_data AS (
    SELECT
        c.id as classification_id,
        c.name as classification_name,
        c.created_by,
        c.is_public,
        c.product_id,
        c.created_at,
        c.updated_at,
        CASE
            WHEN p.id IS NULL THEN NULL
            ELSE json_build_object(
                'id',
                p.id,
                'name',
                p.name
            )
        END AS product
    FROM
        classifications c
        LEFT JOIN products p ON c.product_id = p.id
    WHERE
        c.id = $1
),
fractions_base AS (
    SELECT
        f.id as fraction_id,
        f.name as fraction_name,
        f.classification_id,
        f.order_index
    FROM
        fractions f
    WHERE
        f.classification_id = $1
),
conditions_base AS (
    SELECT
        cond.id as condition_id,
        cond.name as condition_name,
        cond.operator,
        cond.connection,
        cond.order_index,
        cond.fraction_id
    FROM
        conditions cond
        JOIN fractions_base fb ON cond.fraction_id = fb.fraction_id
),
params_base AS (
    SELECT
        param.id as param_id,
        param.name as param_name,
        param.operator,
        param.value,
        param.condition_id
    FROM
        params param
        JOIN conditions_base cb ON param.condition_id = cb.condition_id
),
params_aggregated AS (
    SELECT
        p.condition_id,
        COALESCE(
            json_agg(
                json_build_object(
                    'id',
                    p.param_id,
                    'name',
                    p.param_name,
                    'operator',
                    p.operator,
                    'value',
                    p.value
                )
                ORDER BY
                    p.param_id
            ) FILTER (
                WHERE
                    p.param_id IS NOT NULL
            ),
            '[]' :: json
        ) as params_json
    FROM
        params_base p
    GROUP BY
        p.condition_id
),
conditions_aggregated AS (
    SELECT
        cond.fraction_id,
        COALESCE(
            json_agg(
                json_build_object(
                    'id',
                    cond.condition_id,
                    'name',
                    cond.condition_name,
                    'operator',
                    cond.operator,
                    'connection',
                    cond.connection,
                    'order_id',
                    cond.order_index,
                    'params',
                    pa.params_json
                )
                ORDER BY
                    cond.order_index
            ) FILTER (
                WHERE
                    cond.condition_id IS NOT NULL
            ),
            '[]' :: json
        ) as conditions_json
    FROM
        conditions_base cond
        LEFT JOIN params_aggregated pa ON pa.condition_id = cond.condition_id
    GROUP BY
        cond.fraction_id
),
fractions_aggregated AS (
    SELECT
        fb.classification_id,
        COALESCE(
            json_agg(
                json_build_object(
                    'id',
                    fb.fraction_id,
                    'name',
                    fb.fraction_name,
                    'conditions',
                    ca.conditions_json
                )
                ORDER BY
                    fb.order_index ASC
            ) FILTER (
                WHERE
                    fb.fraction_id IS NOT NULL
            ),
            '[]' :: json
        ) as fractions_json
    FROM
        fractions_base fb
        LEFT JOIN conditions_aggregated ca ON ca.fraction_id = fb.fraction_id
    GROUP BY
        fb.classification_id
)
SELECT
    json_build_object(
        'id',
        cd.classification_id,
        'name',
        cd.classification_name,
        'created_by',
        cd.created_by,
        'is_public',
        cd.is_public,
        'created_at',
        cd.created_at,
        'updated_at',
        cd.updated_at,
        'product',
        cd.product
    )::jsonb as classification,
    COALESCE(fa.fractions_json, '[]'::json)::text::bytea as fractions
FROM
    classification_data cd
    LEFT JOIN fractions_aggregated fa ON fa.classification_id = cd.classification_id
`

type GetCompleteClassificationByIDRow struct {
	Classification []byte `json:"classification"`
	Fractions      []byte `json:"fractions"`
}

// Get a classification by its ID with all related data
func (q *Queries) GetCompleteClassificationByID(ctx context.Context, id uuid.UUID) (GetCompleteClassificationByIDRow, error) {
	row := q.db.QueryRow(ctx, getCompleteClassificationByID, id)
	var i GetCompleteClassificationByIDRow
	err := row.Scan(&i.Classification, &i.Fractions)
	return i, err
}

const updateClassification = `-- name: UpdateClassification :one
UPDATE
    classifications
SET
    name = $1,
    is_public = $2,
    product_id = $3
WHERE
    id = $4 RETURNING id, name, created_by, is_public, product_id, created_at, updated_at
`

type UpdateClassificationParams struct {
	Name      string    `json:"name"`
	IsPublic  bool      `json:"is_public"`
	ProductID uuid.UUID `json:"product_id"`
	ID        uuid.UUID `json:"id"`
}

// Update an existing classification by ID
func (q *Queries) UpdateClassification(ctx context.Context, arg UpdateClassificationParams) (Classification, error) {
	row := q.db.QueryRow(ctx, updateClassification,
		arg.Name,
		arg.IsPublic,
		arg.ProductID,
		arg.ID,
	)
	var i Classification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.IsPublic,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClassificationPublic = `-- name: UpdateClassificationPublic :exec
UPDATE
    classifications
SET
    is_public = $1
WHERE
    id = $2
`

type UpdateClassificationPublicParams struct {
	IsPublic bool      `json:"is_public"`
	ID       uuid.UUID `json:"id"`
}

// Update the public status of a classification
func (q *Queries) UpdateClassificationPublic(ctx context.Context, arg UpdateClassificationPublicParams) error {
	_, err := q.db.Exec(ctx, updateClassificationPublic, arg.IsPublic, arg.ID)
	return err
}
