// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classification_params.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const classificationParamExistsByName = `-- name: ClassificationParamExistsByName :one
SELECT EXISTS (
  SELECT 1 FROM classification_params WHERE name = $1
) AS exists
`

func (q *Queries) ClassificationParamExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, classificationParamExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createClassificationParam = `-- name: CreateClassificationParam :one
INSERT INTO classification_params (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateClassificationParam(ctx context.Context, name string) (ClassificationParam, error) {
	row := q.db.QueryRow(ctx, createClassificationParam, name)
	var i ClassificationParam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClassificationParamByID = `-- name: DeleteClassificationParamByID :exec
DELETE FROM classification_params
WHERE id = $1
`

func (q *Queries) DeleteClassificationParamByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClassificationParamByID, id)
	return err
}

const getAllClassificationParams = `-- name: GetAllClassificationParams :many
SELECT id, name, created_at, updated_at
FROM classification_params
ORDER BY name ASC
`

func (q *Queries) GetAllClassificationParams(ctx context.Context) ([]ClassificationParam, error) {
	rows, err := q.db.Query(ctx, getAllClassificationParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassificationParam{}
	for rows.Next() {
		var i ClassificationParam
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
