// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conditions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const bulkCreateConditions = `-- name: BulkCreateConditions :many
INSERT INTO
  conditions (fraction_id, name, operator, connection, order_index)
SELECT
  unnest($1::uuid[]),
  unnest($2::varchar[]),
  unnest($3::logic_operator[]),
  unnest($4::logic_operator[]),
  unnest($5::int[])
RETURNING
  id, fraction_id, name, operator, connection, order_index, created_at, updated_at
`

type BulkCreateConditionsParams struct {
	FractionIds  []uuid.UUID     `json:"fraction_ids"`
	Names        []string        `json:"names"`
	Operators    []LogicOperator `json:"operators"`
	Connections  []LogicOperator `json:"connections"`
	OrderIndexes []int32         `json:"order_indexes"`
}

// Bulk create conditions
func (q *Queries) BulkCreateConditions(ctx context.Context, arg BulkCreateConditionsParams) ([]Condition, error) {
	rows, err := q.db.Query(ctx, bulkCreateConditions,
		arg.FractionIds,
		arg.Names,
		arg.Operators,
		arg.Connections,
		arg.OrderIndexes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Condition{}
	for rows.Next() {
		var i Condition
		if err := rows.Scan(
			&i.ID,
			&i.FractionID,
			&i.Name,
			&i.Operator,
			&i.Connection,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
