// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fractions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const bulkCreateFractions = `-- name: BulkCreateFractions :many
INSERT INTO
  fractions (name, classification_id, order_index)
SELECT
  unnest($1::varchar[]),
  $2,
  unnest($3::int[])
RETURNING
  id, name, classification_id, order_index, created_at, updated_at
`

type BulkCreateFractionsParams struct {
	Names            []string  `json:"names"`
	ClassificationID uuid.UUID `json:"classification_id"`
	OrderIndexes     []int32   `json:"order_indexes"`
}

// Bulk create fractions for a classification
func (q *Queries) BulkCreateFractions(ctx context.Context, arg BulkCreateFractionsParams) ([]Fraction, error) {
	rows, err := q.db.Query(ctx, bulkCreateFractions, arg.Names, arg.ClassificationID, arg.OrderIndexes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fraction{}
	for rows.Next() {
		var i Fraction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClassificationID,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllFractionsForClassification = `-- name: RemoveAllFractionsForClassification :exec
DELETE FROM
  fractions
WHERE
  classification_id = $1
`

// Remove all fractions for a specific classification
func (q *Queries) RemoveAllFractionsForClassification(ctx context.Context, classificationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllFractionsForClassification, classificationID)
	return err
}
