// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markup.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const bulkCreateMarkupAnalyses = `-- name: BulkCreateMarkupAnalyses :exec
INSERT INTO markup_analyses (markup_id, analysis_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type BulkCreateMarkupAnalysesParams struct {
	MarkupID    uuid.UUID `json:"markup_id"`
	AnalysisIds []int64   `json:"analysis_ids"`
}

func (q *Queries) BulkCreateMarkupAnalyses(ctx context.Context, arg BulkCreateMarkupAnalysesParams) error {
	_, err := q.db.Exec(ctx, bulkCreateMarkupAnalyses, arg.MarkupID, arg.AnalysisIds)
	return err
}

const createMarkup = `-- name: CreateMarkup :one
INSERT INTO markups (name, created_by)
VALUES ($1, $2)
RETURNING id, name, created_by, created_at, updated_at
`

type CreateMarkupParams struct {
	Name      string `json:"name"`
	CreatedBy int32  `json:"created_by"`
}

func (q *Queries) CreateMarkup(ctx context.Context, arg CreateMarkupParams) (Markup, error) {
	row := q.db.QueryRow(ctx, createMarkup, arg.Name, arg.CreatedBy)
	var i Markup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMarkup = `-- name: DeleteMarkup :exec
DELETE FROM markups WHERE id = $1
`

func (q *Queries) DeleteMarkup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarkup, id)
	return err
}

const deleteMarkupAnalyses = `-- name: DeleteMarkupAnalyses :exec
DELETE FROM markup_analyses WHERE markup_id = $1
`

func (q *Queries) DeleteMarkupAnalyses(ctx context.Context, markupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarkupAnalyses, markupID)
	return err
}

const getMarkupAnalysesByMarkupID = `-- name: GetMarkupAnalysesByMarkupID :many
SELECT analysis_id FROM markup_analyses WHERE markup_id = $1
`

func (q *Queries) GetMarkupAnalysesByMarkupID(ctx context.Context, markupID uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, getMarkupAnalysesByMarkupID, markupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var analysis_id int64
		if err := rows.Scan(&analysis_id); err != nil {
			return nil, err
		}
		items = append(items, analysis_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarkupAnalysesByMarkupIDs = `-- name: GetMarkupAnalysesByMarkupIDs :many
SELECT markup_id, analysis_id
FROM markup_analyses
WHERE markup_id = ANY($1::uuid[])
ORDER BY markup_id, analysis_id
`

func (q *Queries) GetMarkupAnalysesByMarkupIDs(ctx context.Context, markupIds []uuid.UUID) ([]MarkupAnalysis, error) {
	rows, err := q.db.Query(ctx, getMarkupAnalysesByMarkupIDs, markupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkupAnalysis{}
	for rows.Next() {
		var i MarkupAnalysis
		if err := rows.Scan(&i.MarkupID, &i.AnalysisID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarkupByID = `-- name: GetMarkupByID :one
SELECT id, name, created_by, created_at, updated_at FROM markups WHERE id = $1
`

func (q *Queries) GetMarkupByID(ctx context.Context, id uuid.UUID) (Markup, error) {
	row := q.db.QueryRow(ctx, getMarkupByID, id)
	var i Markup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarkups = `-- name: GetMarkups :many
SELECT id, name, created_by, created_at, updated_at FROM markups
WHERE ($1::int IS NULL OR created_by = $1)
  AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
`

type GetMarkupsParams struct {
	CreatedBy *int32  `json:"created_by"`
	Name      *string `json:"name"`
}

func (q *Queries) GetMarkups(ctx context.Context, arg GetMarkupsParams) ([]Markup, error) {
	rows, err := q.db.Query(ctx, getMarkups, arg.CreatedBy, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Markup{}
	for rows.Next() {
		var i Markup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarkup = `-- name: UpdateMarkup :one
UPDATE markups
SET name = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, name, created_by, created_at, updated_at
`

type UpdateMarkupParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateMarkup(ctx context.Context, arg UpdateMarkupParams) (Markup, error) {
	row := q.db.QueryRow(ctx, updateMarkup, arg.Name, arg.ID)
	var i Markup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
