// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markup_fractions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const bulkAddObjectsToMarkupFraction = `-- name: BulkAddObjectsToMarkupFraction :exec
INSERT INTO markup_fraction_objects (markup_fraction_id, object_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT (markup_fraction_id, object_id) DO NOTHING
`

type BulkAddObjectsToMarkupFractionParams struct {
	MarkupFractionID uuid.UUID `json:"markup_fraction_id"`
	Column2          []int64   `json:"column_2"`
}

func (q *Queries) BulkAddObjectsToMarkupFraction(ctx context.Context, arg BulkAddObjectsToMarkupFractionParams) error {
	_, err := q.db.Exec(ctx, bulkAddObjectsToMarkupFraction, arg.MarkupFractionID, arg.Column2)
	return err
}

const clearMarkupFractionObjects = `-- name: ClearMarkupFractionObjects :exec
DELETE FROM markup_fraction_objects
WHERE markup_fraction_id = $1
`

func (q *Queries) ClearMarkupFractionObjects(ctx context.Context, markupFractionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMarkupFractionObjects, markupFractionID)
	return err
}

const createMarkupFraction = `-- name: CreateMarkupFraction :one
INSERT INTO markup_fractions (markup_id, name)
VALUES ($1, $2)
RETURNING id, markup_id, name, created_at, updated_at
`

type CreateMarkupFractionParams struct {
	MarkupID uuid.UUID `json:"markup_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateMarkupFraction(ctx context.Context, arg CreateMarkupFractionParams) (MarkupFraction, error) {
	row := q.db.QueryRow(ctx, createMarkupFraction, arg.MarkupID, arg.Name)
	var i MarkupFraction
	err := row.Scan(
		&i.ID,
		&i.MarkupID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMarkupFraction = `-- name: DeleteMarkupFraction :exec
DELETE FROM markup_fractions
WHERE id = $1
`

func (q *Queries) DeleteMarkupFraction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarkupFraction, id)
	return err
}

const getMarkupFractionsByMarkupID = `-- name: GetMarkupFractionsByMarkupID :many
SELECT id, markup_id, name, created_at, updated_at FROM markup_fractions
WHERE markup_id = $1
ORDER BY id ASC
`

func (q *Queries) GetMarkupFractionsByMarkupID(ctx context.Context, markupID uuid.UUID) ([]MarkupFraction, error) {
	rows, err := q.db.Query(ctx, getMarkupFractionsByMarkupID, markupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkupFraction{}
	for rows.Next() {
		var i MarkupFraction
		if err := rows.Scan(
			&i.ID,
			&i.MarkupID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarkupFractionsByMarkupIDs = `-- name: GetMarkupFractionsByMarkupIDs :many
SELECT id, markup_id, name, created_at, updated_at FROM markup_fractions
WHERE markup_id = ANY($1::uuid[])
ORDER BY markup_id, id ASC
`

func (q *Queries) GetMarkupFractionsByMarkupIDs(ctx context.Context, markupIds []uuid.UUID) ([]MarkupFraction, error) {
	rows, err := q.db.Query(ctx, getMarkupFractionsByMarkupIDs, markupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkupFraction{}
	for rows.Next() {
		var i MarkupFraction
		if err := rows.Scan(
			&i.ID,
			&i.MarkupID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectsByMarkupFractionIDs = `-- name: GetObjectsByMarkupFractionIDs :many
SELECT markup_fraction_id, object_id
FROM markup_fraction_objects
WHERE markup_fraction_id = ANY($1::uuid[])
ORDER BY markup_fraction_id, object_id
`

func (q *Queries) GetObjectsByMarkupFractionIDs(ctx context.Context, markupFractionIds []uuid.UUID) ([]MarkupFractionObject, error) {
	rows, err := q.db.Query(ctx, getObjectsByMarkupFractionIDs, markupFractionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkupFractionObject{}
	for rows.Next() {
		var i MarkupFractionObject
		if err := rows.Scan(&i.MarkupFractionID, &i.ObjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
