// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merge.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const mergeGetUserActiveClassifications = `-- name: MergeGetUserActiveClassifications :many
SELECT user_id, classification_id, created_at, updated_at
FROM user_active_classification
WHERE user_id IN ($1, $2)
`

type MergeGetUserActiveClassificationsParams struct {
	FromUserID int32 `json:"from_user_id"`
	ToUserID   int32 `json:"to_user_id"`
}

type MergeGetUserActiveClassificationsRow struct {
	UserID           int32     `json:"user_id"`
	ClassificationID uuid.UUID `json:"classification_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// Get both users' active classification rows for conflict resolution (newer wins)
func (q *Queries) MergeGetUserActiveClassifications(ctx context.Context, arg MergeGetUserActiveClassificationsParams) ([]MergeGetUserActiveClassificationsRow, error) {
	rows, err := q.db.Query(ctx, mergeGetUserActiveClassifications, arg.FromUserID, arg.ToUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MergeGetUserActiveClassificationsRow{}
	for rows.Next() {
		var i MergeGetUserActiveClassificationsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ClassificationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeReassignClassifications = `-- name: MergeReassignClassifications :exec
UPDATE classifications
SET created_by = $1
WHERE created_by = $2
`

type MergeReassignClassificationsParams struct {
	ToUserID   int32 `json:"to_user_id"`
	FromUserID int32 `json:"from_user_id"`
}

// Reassign classifications from one user to another during account merge
func (q *Queries) MergeReassignClassifications(ctx context.Context, arg MergeReassignClassificationsParams) error {
	_, err := q.db.Exec(ctx, mergeReassignClassifications, arg.ToUserID, arg.FromUserID)
	return err
}

const mergeReassignMarkups = `-- name: MergeReassignMarkups :exec
UPDATE markups
SET created_by = $1
WHERE created_by = $2
`

type MergeReassignMarkupsParams struct {
	ToUserID   int32 `json:"to_user_id"`
	FromUserID int32 `json:"from_user_id"`
}

// Reassign markups from one user to another during account merge
func (q *Queries) MergeReassignMarkups(ctx context.Context, arg MergeReassignMarkupsParams) error {
	_, err := q.db.Exec(ctx, mergeReassignMarkups, arg.ToUserID, arg.FromUserID)
	return err
}

const mergeUserActiveClassificationDeleteByUserID = `-- name: MergeUserActiveClassificationDeleteByUserID :exec
DELETE FROM user_active_classification
WHERE user_id = $1
`

// Delete user_active_classification row by user_id
func (q *Queries) MergeUserActiveClassificationDeleteByUserID(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, mergeUserActiveClassificationDeleteByUserID, userID)
	return err
}

const mergeUserActiveClassificationReassign = `-- name: MergeUserActiveClassificationReassign :exec
UPDATE user_active_classification
SET user_id = $1,
    updated_at = NOW()
WHERE user_id = $2
`

type MergeUserActiveClassificationReassignParams struct {
	ToUserID   int32 `json:"to_user_id"`
	FromUserID int32 `json:"from_user_id"`
}

// Reassign user_active_classification from one user to another (used when from_user has the winning row)
func (q *Queries) MergeUserActiveClassificationReassign(ctx context.Context, arg MergeUserActiveClassificationReassignParams) error {
	_, err := q.db.Exec(ctx, mergeUserActiveClassificationReassign, arg.ToUserID, arg.FromUserID)
	return err
}
