// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LogicOperator string

const (
	LogicOperatorOR  LogicOperator = "OR"
	LogicOperatorAND LogicOperator = "AND"
)

func (e *LogicOperator) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogicOperator(s)
	case string:
		*e = LogicOperator(s)
	default:
		return fmt.Errorf("unsupported scan type for LogicOperator: %T", src)
	}
	return nil
}

type NullLogicOperator struct {
	LogicOperator LogicOperator `json:"logic_operator"`
	Valid         bool          `json:"valid"` // Valid is true if LogicOperator is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogicOperator) Scan(value interface{}) error {
	if value == nil {
		ns.LogicOperator, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogicOperator.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogicOperator) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogicOperator), nil
}

type ParamOperator string

const (
	ParamOperatorValue0 ParamOperator = "<"
	ParamOperatorValue1 ParamOperator = "<="
	ParamOperatorValue2 ParamOperator = "=="
	ParamOperatorValue3 ParamOperator = ">="
	ParamOperatorValue4 ParamOperator = ">"
	ParamOperatorValue5 ParamOperator = "!="
)

func (e *ParamOperator) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParamOperator(s)
	case string:
		*e = ParamOperator(s)
	default:
		return fmt.Errorf("unsupported scan type for ParamOperator: %T", src)
	}
	return nil
}

type NullParamOperator struct {
	ParamOperator ParamOperator `json:"param_operator"`
	Valid         bool          `json:"valid"` // Valid is true if ParamOperator is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParamOperator) Scan(value interface{}) error {
	if value == nil {
		ns.ParamOperator, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParamOperator.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParamOperator) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParamOperator), nil
}

type Classification struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedBy int32     `json:"created_by"`
	IsPublic  bool      `json:"is_public"`
	ProductID uuid.UUID `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ClassificationParam struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Condition struct {
	ID         uuid.UUID     `json:"id"`
	FractionID uuid.UUID     `json:"fraction_id"`
	Name       string        `json:"name"`
	Operator   LogicOperator `json:"operator"`
	Connection LogicOperator `json:"connection"`
	OrderIndex int32         `json:"order_index"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type Fraction struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	ClassificationID uuid.UUID `json:"classification_id"`
	OrderIndex       int32     `json:"order_index"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Markup struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedBy int32     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type MarkupAnalysis struct {
	MarkupID   uuid.UUID `json:"markup_id"`
	AnalysisID int64     `json:"analysis_id"`
}

type MarkupFraction struct {
	ID        uuid.UUID `json:"id"`
	MarkupID  uuid.UUID `json:"markup_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type MarkupFractionObject struct {
	MarkupFractionID uuid.UUID `json:"markup_fraction_id"`
	ObjectID         int64     `json:"object_id"`
}

type Param struct {
	ID          uuid.UUID      `json:"id"`
	ConditionID uuid.UUID      `json:"condition_id"`
	Name        string         `json:"name"`
	Operator    ParamOperator  `json:"operator"`
	Value       pgtype.Numeric `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Product struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserActiveClassification struct {
	ID               uuid.UUID `json:"id"`
	UserID           int32     `json:"user_id"`
	ClassificationID uuid.UUID `json:"classification_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
