// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: params.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateParams = `-- name: BulkCreateParams :many
INSERT INTO
  params (name, operator, value, condition_id)
SELECT
  unnest($1::varchar[]),
  unnest($2::param_operator[]),
  unnest($3::numeric[]),
  unnest($4::uuid[])
RETURNING
  id, condition_id, name, operator, value, created_at, updated_at
`

type BulkCreateParamsParams struct {
	Names        []string         `json:"names"`
	Operators    []ParamOperator  `json:"operators"`
	Values       []pgtype.Numeric `json:"values"`
	ConditionIds []uuid.UUID      `json:"condition_ids"`
}

// Bulk create params
func (q *Queries) BulkCreateParams(ctx context.Context, arg BulkCreateParamsParams) ([]Param, error) {
	rows, err := q.db.Query(ctx, bulkCreateParams,
		arg.Names,
		arg.Operators,
		arg.Values,
		arg.ConditionIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Param{}
	for rows.Next() {
		var i Param
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.Name,
			&i.Operator,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
