// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_active_classification.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserActiveClassification = `-- name: DeleteUserActiveClassification :exec
DELETE FROM
  user_active_classification
WHERE
  user_id = $1
`

// Remove the active classification for a user
func (q *Queries) DeleteUserActiveClassification(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserActiveClassification, userID)
	return err
}

const getUserActiveClassification = `-- name: GetUserActiveClassification :one
SELECT
  id, user_id, classification_id, created_at, updated_at
FROM
  user_active_classification
WHERE
  user_id = $1
`

// Get the active classification for a user
func (q *Queries) GetUserActiveClassification(ctx context.Context, userID int32) (UserActiveClassification, error) {
	row := q.db.QueryRow(ctx, getUserActiveClassification, userID)
	var i UserActiveClassification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClassificationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserActiveClassification = `-- name: SetUserActiveClassification :one
INSERT INTO
  user_active_classification (user_id, classification_id)
VALUES
  ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET
  classification_id = EXCLUDED.classification_id,
  updated_at = NOW()
RETURNING id, user_id, classification_id, created_at, updated_at
`

type SetUserActiveClassificationParams struct {
	UserID           int32     `json:"user_id"`
	ClassificationID uuid.UUID `json:"classification_id"`
}

// Set or update the active classification for a user
func (q *Queries) SetUserActiveClassification(ctx context.Context, arg SetUserActiveClassificationParams) (UserActiveClassification, error) {
	row := q.db.QueryRow(ctx, setUserActiveClassification, arg.UserID, arg.ClassificationID)
	var i UserActiveClassification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClassificationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
