// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package weed

import (
	database "csort.ru/coffeebot/internal/database"
	pgxconv "csort.ru/coffeebot/internal/pgxconv"
)

type queryConverterImpl struct{}

func (c *queryConverterImpl) ListWeedsParamsToCountDB(source database.ListWeedsParams) database.CountWeedsParams {
	var databaseCountWeedsParams database.CountWeedsParams
	if source.Name != nil {
		xstring := *source.Name
		databaseCountWeedsParams.Name = &xstring
	}
	if source.LMin != nil {
		xfloat32 := *source.LMin
		databaseCountWeedsParams.LMin = &xfloat32
	}
	if source.LMax != nil {
		xfloat322 := *source.LMax
		databaseCountWeedsParams.LMax = &xfloat322
	}
	if source.WMin != nil {
		xfloat323 := *source.WMin
		databaseCountWeedsParams.WMin = &xfloat323
	}
	if source.WMax != nil {
		xfloat324 := *source.WMax
		databaseCountWeedsParams.WMax = &xfloat324
	}
	if source.LwMin != nil {
		xfloat325 := *source.LwMin
		databaseCountWeedsParams.LwMin = &xfloat325
	}
	if source.LwMax != nil {
		xfloat326 := *source.LwMax
		databaseCountWeedsParams.LwMax = &xfloat326
	}
	if source.HMin != nil {
		xfloat327 := *source.HMin
		databaseCountWeedsParams.HMin = &xfloat327
	}
	if source.HMax != nil {
		xfloat328 := *source.HMax
		databaseCountWeedsParams.HMax = &xfloat328
	}
	if source.SMin != nil {
		xfloat329 := *source.SMin
		databaseCountWeedsParams.SMin = &xfloat329
	}
	if source.SMax != nil {
		xfloat3210 := *source.SMax
		databaseCountWeedsParams.SMax = &xfloat3210
	}
	if source.VMin != nil {
		xfloat3211 := *source.VMin
		databaseCountWeedsParams.VMin = &xfloat3211
	}
	if source.VMax != nil {
		xfloat3212 := *source.VMax
		databaseCountWeedsParams.VMax = &xfloat3212
	}
	if source.RMin != nil {
		xfloat3213 := *source.RMin
		databaseCountWeedsParams.RMin = &xfloat3213
	}
	if source.RMax != nil {
		xfloat3214 := *source.RMax
		databaseCountWeedsParams.RMax = &xfloat3214
	}
	if source.GMin != nil {
		xfloat3215 := *source.GMin
		databaseCountWeedsParams.GMin = &xfloat3215
	}
	if source.GMax != nil {
		xfloat3216 := *source.GMax
		databaseCountWeedsParams.GMax = &xfloat3216
	}
	if source.BMin != nil {
		xfloat3217 := *source.BMin
		databaseCountWeedsParams.BMin = &xfloat3217
	}
	if source.BMax != nil {
		xfloat3218 := *source.BMax
		databaseCountWeedsParams.BMax = &xfloat3218
	}
	if source.BrtMin != nil {
		xfloat3219 := *source.BrtMin
		databaseCountWeedsParams.BrtMin = &xfloat3219
	}
	if source.BrtMax != nil {
		xfloat3220 := *source.BrtMax
		databaseCountWeedsParams.BrtMax = &xfloat3220
	}
	if source.SqSqcrlMin != nil {
		xfloat3221 := *source.SqSqcrlMin
		databaseCountWeedsParams.SqSqcrlMin = &xfloat3221
	}
	if source.SqSqcrlMax != nil {
		xfloat3222 := *source.SqSqcrlMax
		databaseCountWeedsParams.SqSqcrlMax = &xfloat3222
	}
	if source.MainGroup != nil {
		xstring2 := *source.MainGroup
		databaseCountWeedsParams.MainGroup = &xstring2
	}
	if source.MainSubgroup != nil {
		xstring3 := *source.MainSubgroup
		databaseCountWeedsParams.MainSubgroup = &xstring3
	}
	if source.Subgroup != nil {
		xstring4 := *source.Subgroup
		databaseCountWeedsParams.Subgroup = &xstring4
	}
	if source.IsQuarantine != nil {
		xbool := *source.IsQuarantine
		databaseCountWeedsParams.IsQuarantine = &xbool
	}
	return databaseCountWeedsParams
}
func (c *queryConverterImpl) ListWeedsParamsToListDB(source ListWeedsParams) database.ListWeedsParams {
	var databaseListWeedsParams database.ListWeedsParams
	databaseListWeedsParams.Name = pgxconv.NonEmptyStringPtr(source.Name)
	databaseListWeedsParams.MainGroup = pgxconv.NonEmptyStringPtr(source.MainGroup)
	databaseListWeedsParams.MainSubgroup = pgxconv.NonEmptyStringPtr(source.MainSubgroup)
	databaseListWeedsParams.Subgroup = pgxconv.NonEmptyStringPtr(source.Subgroup)
	if source.IsQuarantine != nil {
		xbool := *source.IsQuarantine
		databaseListWeedsParams.IsQuarantine = &xbool
	}
	if source.LMin != nil {
		xfloat32 := *source.LMin
		databaseListWeedsParams.LMin = &xfloat32
	}
	if source.LMax != nil {
		xfloat322 := *source.LMax
		databaseListWeedsParams.LMax = &xfloat322
	}
	if source.WMin != nil {
		xfloat323 := *source.WMin
		databaseListWeedsParams.WMin = &xfloat323
	}
	if source.WMax != nil {
		xfloat324 := *source.WMax
		databaseListWeedsParams.WMax = &xfloat324
	}
	if source.LWMin != nil {
		xfloat325 := *source.LWMin
		databaseListWeedsParams.LwMin = &xfloat325
	}
	if source.LWMax != nil {
		xfloat326 := *source.LWMax
		databaseListWeedsParams.LwMax = &xfloat326
	}
	if source.HMin != nil {
		xfloat327 := *source.HMin
		databaseListWeedsParams.HMin = &xfloat327
	}
	if source.HMax != nil {
		xfloat328 := *source.HMax
		databaseListWeedsParams.HMax = &xfloat328
	}
	if source.SMin != nil {
		xfloat329 := *source.SMin
		databaseListWeedsParams.SMin = &xfloat329
	}
	if source.SMax != nil {
		xfloat3210 := *source.SMax
		databaseListWeedsParams.SMax = &xfloat3210
	}
	if source.VMin != nil {
		xfloat3211 := *source.VMin
		databaseListWeedsParams.VMin = &xfloat3211
	}
	if source.VMax != nil {
		xfloat3212 := *source.VMax
		databaseListWeedsParams.VMax = &xfloat3212
	}
	if source.RMin != nil {
		xfloat3213 := *source.RMin
		databaseListWeedsParams.RMin = &xfloat3213
	}
	if source.RMax != nil {
		xfloat3214 := *source.RMax
		databaseListWeedsParams.RMax = &xfloat3214
	}
	if source.GMin != nil {
		xfloat3215 := *source.GMin
		databaseListWeedsParams.GMin = &xfloat3215
	}
	if source.GMax != nil {
		xfloat3216 := *source.GMax
		databaseListWeedsParams.GMax = &xfloat3216
	}
	if source.BMin != nil {
		xfloat3217 := *source.BMin
		databaseListWeedsParams.BMin = &xfloat3217
	}
	if source.BMax != nil {
		xfloat3218 := *source.BMax
		databaseListWeedsParams.BMax = &xfloat3218
	}
	if source.BrtMin != nil {
		xfloat3219 := *source.BrtMin
		databaseListWeedsParams.BrtMin = &xfloat3219
	}
	if source.BrtMax != nil {
		xfloat3220 := *source.BrtMax
		databaseListWeedsParams.BrtMax = &xfloat3220
	}
	if source.SqSqcrlMin != nil {
		xfloat3221 := *source.SqSqcrlMin
		databaseListWeedsParams.SqSqcrlMin = &xfloat3221
	}
	if source.SqSqcrlMax != nil {
		xfloat3222 := *source.SqSqcrlMax
		databaseListWeedsParams.SqSqcrlMax = &xfloat3222
	}
	databaseListWeedsParams.SortOrder = source.SortOrder
	databaseListWeedsParams.Offset = source.PaginatedRequest.Offset
	databaseListWeedsParams.Limit = source.PaginatedRequest.Limit
	return databaseListWeedsParams
}
